import {BOARDING_DOCTRINES,BOARDING_OBJECTIVES,setBoardingDoctrine,setBoardingObjective,boardingSummary} from './boarding-system.js';

function battle(){return window.__fleetBattle||null}
function selectedShips(){const b=battle(),who=document.querySelector('#orderShips')?.value||'all';if(!b)return[];return b.ships.filter(s=>s.team==='P'&&!s.dead&&(who==='all'||s.uid===who))}
function focusedShip(){const b=battle(),uid=document.querySelector('#focusShip')?.value;if(!b)return null;return b.ships.find(s=>s.uid===uid)||null}
function pct(v){return `${Math.max(0,Math.min(100,Math.round(v*100)))}%`}

function install(){const orders=document.querySelector('.orders');if(!orders||document.querySelector('#boardingControls'))return;const box=document.createElement('div');box.id='boardingControls';box.className='boardingControls';box.innerHTML=`<h3>Boarding</h3><label>Boarding doctrine<select id="boardingDoctrine">${Object.entries(BOARDING_DOCTRINES).map(([id,d])=>`<option value="${id}"${id==='opportunistic'?' selected':''}>${d.label}</option>`).join('')}</select></label><label>Preferred objective<select id="boardingObjective">${Object.entries(BOARDING_OBJECTIVES).map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select></label><small>Captains launch physical boarding shuttles only when doctrine says the target is vulnerable enough. Multiple simultaneous breaches split the defenders.</small>`;orders.append(box);document.querySelector('#boardingDoctrine').onchange=e=>{for(const s of selectedShips())setBoardingDoctrine(s,e.target.value)};document.querySelector('#boardingObjective').onchange=e=>{for(const s of selectedShips())setBoardingObjective(s,e.target.value)}}

function render(){const s=focusedShip(),host=document.querySelector('#hudShipInfo');if(!host)return;host.querySelector('.focusedBoarding')?.remove();if(!s)return;const b=battle(),st=boardingSummary(s),incoming=st.activeFronts||[],outbound=(b?.ordnance||[]).filter(o=>o.kind==='boardingShuttle'&&o.owner===s&&o.hp>0),hasCapability=(s.modules||[]).some(m=>m.type==='hangar'||m.type==='marineBerth')||incoming.length||outbound.length;if(!hasCapability)return;const split=incoming.length>1?` · defenders split ${incoming.length} ways`:'';const el=document.createElement('section');el.className='focusedBoarding';el.innerHTML=`<div class="boardingHead"><b>BOARDING</b><span>${s.team==='P'?(BOARDING_DOCTRINES[s.boardingDoctrine||'opportunistic']?.label||'Opportunistic'):'SECURITY'}</span></div><div class="boardingStats"><span>Security ${Math.max(0,Math.round(st.defenderStrength-st.casualties))}/${Math.round(st.defenderStrength)}</span><span>Available personnel ${Math.max(0,Math.round(st.personnelAvailable))}</span></div>${incoming.length?`<div class="boardingAlert">${incoming.length} active breach${incoming.length===1?'':'es'}${split}</div>${incoming.map(f=>`<div class="boardingFront"><div><b>${BOARDING_OBJECTIVES[f.objective]||f.objective}</b><span>${f.sourceName}</span></div><small>${f.phase==='breaching'?`Breaching ${pct(f.breach)}`:`Control ${pct(f.control)} · ${Math.max(0,f.attackers).toFixed(1)} attackers`}</small><div class="boardingTrack"><i style="width:${pct(f.phase==='breaching'?f.breach:f.control)}"></i></div></div>`).join('')}`:''}${outbound.length?`<div class="boardingOutbound"><b>Boarding shuttles in flight</b>${outbound.map(o=>`<span>${o.target?.name||'returning'} · ${o.marines||0} marines · fuel ${pct((o.fuel||0)/(o.maxFuel||1))}</span>`).join('')}</div>`:''}`;host.append(el)}
install();setInterval(render,220);
