import {Battle} from './sim.js';
import {CRAFT,craftSpace} from './craft-catalog.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const BASE_UPDATE=Battle.prototype.updateProjectiles,BASE_STEP=Battle.prototype.step;
export const BOARDING_DOCTRINES={never:{label:'Never board',max:0,cut:99},opportunistic:{label:'Opportunistic',max:1,cut:.72},capture:{label:'Capture if practical',max:2,cut:.52},aggressive:{label:'Aggressive capture',max:3,cut:.30}};
export const BOARDING_OBJECTIVES={capture:'Capture ship',bridge:'Seize bridge',engine:'Disable engines',reactor:'Sabotage reactor'};
const alive=(s,t)=>(s.modules||[]).filter(m=>m.type===t&&m.hp>0&&!m.disabled);
const frac=(s,ts)=>{const ms=(s.modules||[]).filter(m=>ts.includes(m.type));if(!ms.length)return 0;const max=ms.reduce((n,m)=>n+(m.maxHp||m.hp||1),0)||1;return ms.reduce((n,m)=>n+Math.max(0,m.hp||0),0)/max};
const hpFrac=s=>{const ms=s.modules||[],max=ms.reduce((n,m)=>n+(m.maxHp||m.hp||0),0)||1;return ms.reduce((n,m)=>n+Math.max(0,m.hp||0),0)/max};
export function ensureBoardingState(s){if(!s.boardingState){const cells=s.grid?.validCells?.length||20,base=3+Math.ceil(Math.sqrt(cells)*.8),marines=Math.round(alive(s,'marineBerth').reduce((n,m)=>n+(m.marineCapacity||0),0)),bonus=Math.round(alive(s,'marineBerth').reduce((n,m)=>n+(m.securityBonus||0),0));s.boardingState={personnelAvailable:Math.max(4,base+marines),personnelInitial:Math.max(4,base+marines),defenderStrength:Math.max(4,base+marines+bonus),casualties:0,fronts:[],capturedSystems:{}}}s.boardingDoctrine??='opportunistic';s.boardingObjective??='capture';return s.boardingState}
function initHangar(h){h.craftInventory??={...(h.defaultCraft||{})};h.craftService??=[];return h}
function used(h){let n=0;for(const[k,v]of Object.entries(h.craftInventory||{}))n+=v*craftSpace(k);for(const x of h.craftService||[])n+=craftSpace(x.kind);return n}
const sourceHangar=s=>alive(s,'hangar').map(initHangar).find(h=>(h.craftInventory?.boardingShuttle||0)>0)||null;
const freeHangar=s=>alive(s,'hangar').map(initHangar).find(h=>(h.hangarSpaces||0)-used(h)>=2-.001)||null;
function baySlot(s,t,recovery=false){for(const bay of alive(s,'launchBay')){bay._slotUntil??=[];while(bay._slotUntil.length<(bay.launchSlots||1))bay._slotUntil.push(0);const i=bay._slotUntil.findIndex(x=>x<=t);if(i<0)continue;const factor=recovery?CRAFT.boardingShuttle.recoveryTime:CRAFT.boardingShuttle.launchTime,cycle=(recovery?(bay.recoveryCycle||3):(bay.launchCycle||2))*factor;return{bay,i,cycle}}return null}
function steer(o,t,dt){if(!t||o.fuel<=0)return;const wanted=Math.atan2(t.y-o.y,t.x-o.x),err=wrap(wanted-o.angle);o.angle=wrap(o.angle+clamp(err,-o.turnRate*dt,o.turnRate*dt));o.vx+=Math.cos(o.angle)*o.accel*dt;o.vy+=Math.sin(o.angle)*o.accel*dt;o.fuel=Math.max(0,o.fuel-dt)}
export function launchBoardingShuttle(b,s,target,objective=s.boardingObjective||'capture'){const st=ensureBoardingState(s),h=sourceHangar(s),slot=baySlot(s,b.t);if(!h||!slot||!target||target.dead||s.runSilent||st.personnelAvailable<2)return false;const troops=Math.min(CRAFT.boardingShuttle.troopCapacity,st.personnelAvailable);h.craftInventory.boardingShuttle--;st.personnelAvailable-=troops;slot.bay._slotUntil[slot.i]=b.t+slot.cycle;const a=s.angle+(slot.bay.mountDir||0),serial=(s._boardingSerial=(s._boardingSerial||0)+1);b.ordnance??=[];b.ordnance.push({kind:'boardingShuttle',team:s.team,owner:s,homeShip:s,name:`${s.name} boarding shuttle ${serial}`,x:s.x,y:s.y,vx:s.vx+Math.cos(a)*70,vy:s.vy+Math.sin(a)*70,angle:a,hp:CRAFT.boardingShuttle.hp,maxHp:CRAFT.boardingShuttle.hp,accel:CRAFT.boardingShuttle.accel,turnRate:CRAFT.boardingShuttle.turnRate,r:CRAFT.boardingShuttle.r,fuel:CRAFT.boardingShuttle.maxFuel,maxFuel:CRAFT.boardingShuttle.maxFuel,returnFuel:CRAFT.boardingShuttle.returnFuel,target,objective,marines:troops,state:'approach',ttl:9999});b.log(`${s.name}: boarding shuttle launched toward ${target.name}.`);return true}
function vulnerability(t){const surrender=t.outcome==='surrendered'||t.surrendered;return clamp((1-frac(t,['engine']))*.36+(1-frac(t,['gun','laser','missile']))*.34+(1-hpFrac(t))*.20+(surrender ? .35 : 0),0,1.4)}
function activeSorties(b,s){return (b.ordnance||[]).filter(o=>o.kind==='boardingShuttle'&&o.owner===s&&o.hp>0).length+b.ships.reduce((n,t)=>n+ensureBoardingState(t).fronts.filter(f=>f.sourceShipUid===s.uid&&!f.resolved&&f.attackers>0).length,0)}
function doctrineStep(b){for(const s of b.ships){if(s.dead)continue;const d=BOARDING_DOCTRINES[s.boardingDoctrine||'opportunistic'];if(!d||d.max===0||activeSorties(b,s)>=d.max||!sourceHangar(s))continue;const q=b.ships.filter(t=>!t.dead&&t.team!==s.team).map(t=>({t,v:vulnerability(t)})).filter(x=>x.v>=d.cut).sort((a,c)=>c.v-a.v||dist(s,a.t)-dist(s,c.t));if(q[0])launchBoardingShuttle(b,s,q[0].t,s.boardingObjective||'capture')}}
function attach(b,o,t){ensureBoardingState(t).fronts.push({team:o.team,sourceShipUid:o.owner.uid,sourceName:o.owner.name,attackers:o.marines,objective:o.objective,phase:'breaching',breach:0,control:0,resolved:false});o.hp=0;b.log(`${o.name} forced docking with ${t.name}; breaching underway.`)}
function recover(b,o){const home=o.homeShip;if(!home||home.dead){o.hp=0;return}steer(o,home,b._boardingDt);o.x+=o.vx*b._boardingDt;o.y+=o.vy*b._boardingDt;const rv=Math.hypot(o.vx-home.vx,o.vy-home.vy);if(dist(o,home)<50&&rv<80){const h=freeHangar(home),slot=baySlot(home,b.t,true);if(h&&slot){slot.bay._slotUntil[slot.i]=b.t+slot.cycle;h.craftService.push({kind:'boardingShuttle',readyAt:b.t+slot.cycle+CRAFT.boardingShuttle.serviceTime});ensureBoardingState(home).personnelAvailable+=o.marines||0;o.hp=0;o.recovered=true}}}
function updateShuttle(b,o,dt){b._boardingDt=dt;const t=o.target;if((!t||t.dead)&&o.state!=='returning')o.state='returning';if(o.state==='returning'){recover(b,o);return}steer(o,t,dt);o.x+=o.vx*dt;o.y+=o.vy*dt;const rv=Math.hypot(o.vx-t.vx,o.vy-t.vy);if(dist(o,t)<Math.max(32,(t.radius||15)+18)&&rv<=CRAFT.boardingShuttle.dockRelativeSpeed)attach(b,o,t);else if(o.fuel<=o.returnFuel)o.state='returning'}
function damageObjective(t,obj,amt){const type=obj==='bridge'?'bridge':obj==='engine'?'engine':obj==='reactor'?'reactor':null;if(!type)return;const m=(t.modules||[]).find(x=>x.type===type&&x.hp>0);if(m)m.hp=Math.max(0,m.hp-amt)}
function resolveFronts(b,t,dt){const st=ensureBoardingState(t),fs=st.fronts.filter(f=>!f.resolved&&f.attackers>0);if(!fs.length)return;const defenders=Math.max(0,st.defenderStrength-st.casualties);for(const f of fs){if(f.phase==='breaching'){f.breach+=(.10+.018*f.attackers)*dt;if(f.breach>=1){f.breach=1;f.phase='fighting';b.log(`${t.name}: breach established; defenders split across ${fs.length} incursion${fs.length===1?'':'s'}.`)}continue}const def=defenders/fs.length*.72,atk=f.attackers*(.78+.10*Math.min(3,fs.length)),pressure=(atk-def)/Math.max(4,atk+def);f.control=clamp(f.control+(.025+.055*pressure)*dt,0,1);f.attackers=Math.max(0,f.attackers-(.012+.020*def/Math.max(1,atk))*dt);st.casualties=Math.min(st.defenderStrength,st.casualties+(.010+.023*atk/Math.max(1,def||1))*dt);if(f.objective!=='capture'&&f.control>.72)damageObjective(t,f.objective,5*dt);if(f.attackers<=.35){f.resolved=true;f.phase='repelled';b.log(`${t.name}: boarding party repelled.`)}else if(f.control>=1){f.resolved=true;f.phase='success';if(f.objective==='capture'){t.outcome='captured';t.surrendered=true;t.throttle=0;t.boardedByTeam=f.team;b.log(`${t.name} captured by boarding action.`)}else{st.capturedSystems[f.objective]=true;b.log(`${t.name}: boarders secured ${BOARDING_OBJECTIVES[f.objective]}.`)}}}}
Battle.prototype.updateProjectiles=function(dt){const out=BASE_UPDATE.call(this,dt);for(const o of this.ordnance||[])if(o.kind==='boardingShuttle'&&o.hp>0)updateShuttle(this,o,dt);for(const s of this.ships)if(!s.dead)resolveFronts(this,s,dt);this.ordnance=(this.ordnance||[]).filter(o=>o.hp>0&&o.ttl>0);return out};
Battle.prototype.step=function(dt){const out=BASE_STEP.call(this,dt);this._boardingClock=(this._boardingClock||0)+dt;if(this._boardingClock>=1){this._boardingClock=0;doctrineStep(this)}return out};
export function setBoardingDoctrine(s,id){if(BOARDING_DOCTRINES[id])s.boardingDoctrine=id;return s.boardingDoctrine}
export function setBoardingObjective(s,id){if(BOARDING_OBJECTIVES[id])s.boardingObjective=id;return s.boardingObjective}
export function boardingSummary(s){const st=ensureBoardingState(s);return{...st,activeFronts:st.fronts.filter(f=>!f.resolved&&f.attackers>0)}}
