import {blueprintToShip,MODULES} from './shipyard.js';
import {makePremade} from './premades.js';

const KEY='spaceFleet.campaign.v1';
const nowId=()=>Math.random().toString(36).slice(2,8)+Date.now().toString(36).slice(-4);
function starterShip(name,hullId,ai='pursuit'){const bp=makePremade(hullId);bp.name=name;bp.ai=ai;return{id:'ship_'+nowId(),name,blueprint:bp,status:'active',xp:0,battles:0,kills:0,state:null,history:[]}}
function defaultCampaign(){return{version:3,day:1,credits:1200,supplies:100,reputation:0,plotStage:0,location:'Haven Reach',ships:[starterShip('Resolute','frigate_line','broadside'),starterShip('Vigilant','frigate_sparrow','pursuit'),starterShip('Wayfarer','frigate_dart','pursuit')],activeShipIds:[],central:{standing:20,lawfulness:0,militaryPermit:false,auxiliary:false,violations:0},factionRep:{haven:5,pelagosA:0,pelagosB:0,kestrel:0,nadir:0},cargo:{},contractsCompleted:{trade:0,escort:0,scout:0,mercenary:0,smuggling:0,antiPiracy:0},knownSystems:['Sol Gateway','Haven Reach','Pelagos','Kestrel','Nadir'],log:['Commissioned to independent fleet command at Haven Reach. Central authority recognises the fleet as a lawful private naval concern, within limits.'],pendingEncounter:null}}
export function loadCampaign(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x?.ships?.length)return x}catch{}const c=defaultCampaign();c.activeShipIds=c.ships.slice(0,3).map(s=>s.id);saveCampaign(c);return c}
export function saveCampaign(c){localStorage.setItem(KEY,JSON.stringify(c));return c}
export function resetCampaign(){const c=defaultCampaign();c.activeShipIds=c.ships.slice(0,3).map(s=>s.id);saveCampaign(c);return c}
export let campaign=loadCampaign();
export function refreshCampaign(){campaign=loadCampaign();return campaign}
function clone(x){return x==null?x:JSON.parse(JSON.stringify(x))}
export function applySavedState(ship,entry){const st=entry.state;if(!st)return ship;const byId=new Map(ship.modules.map(m=>[m.id,m]));for(const sm of st.modules||[]){const m=byId.get(sm.id);if(!m)continue;m.hp=Math.min(m.maxHp||m.hp,sm.hp);if(Number.isFinite(sm.ammo)&&Number.isFinite(m.ammo))m.ammo=sm.ammo;if(Number.isFinite(sm.energyMWh))m.energyMWh=sm.energyMWh;if(Number.isFinite(sm.charge))m.charge=sm.charge;if(sm.craftInventory)m.craftInventory=clone(sm.craftInventory);if(sm.initialCraft)m.initialCraft=clone(sm.initialCraft);m.craftService=[];}ship.doctrineId=st.doctrineId||ship.doctrineId;ship.formationDiscipline=st.formationDiscipline||ship.formationDiscipline;return ship}
export function instantiateCampaignShip(entry,team='P'){const ship=blueprintToShip(entry.blueprint,team);ship.name=entry.name;ship.campaignShipId=entry.id;ship.campaignXp=entry.xp||0;return ship}
export function activePlayerShips(){const ids=new Set(campaign.activeShipIds||[]);return campaign.ships.filter(s=>ids.has(s.id)&&s.status==='active')}
function recoveredInventory(m){const inv=clone(m.craftInventory||m.defaultCraft||{});for(const x of m.craftService||[])inv[x.kind]=(inv[x.kind]||0)+1;return inv}
export function snapshotShip(ship){return{modules:ship.modules.map(m=>({id:m.id,hp:Math.max(0,m.hp||0),ammo:m.ammo,energyMWh:m.energyMWh,charge:m.charge,craftInventory:m.type==='hangar'?recoveredInventory(m):undefined,initialCraft:m.type==='hangar'?clone(m.initialCraft||m.defaultCraft||{}):undefined})),doctrineId:ship.doctrineId,formationDiscipline:ship.formationDiscipline}}
function recoverSurvivingCraft(battle,ship){const craft=(battle.ordnance||[]).filter(o=>['fighter','sensorDrone'].includes(o.kind)&&o.owner===ship&&o.hp>0);for(const o of craft){const hangars=ship.modules.filter(m=>m.type==='hangar'&&m.hp>0&&!m.disabled);let placed=false;for(const h of hangars){h.craftInventory??={...(h.defaultCraft||{})};const used=Object.entries(h.craftInventory).reduce((n,[k,v])=>n+v*(k==='sensorDrone'?.5:1),0);if(used+(o.kind==='sensorDrone'?.5:1)<=(h.hangarSpaces||0)+.001){h.craftInventory[o.kind]=(h.craftInventory[o.kind]||0)+1;placed=true;break}}if(!placed)ship.historyNote=`Unable to recover ${o.name}; no surviving hangar space.`;o.hp=0}}
export function persistBattleResults(battle){if(!battle?.campaignBattle||battle._campaignPersisted)return;battle._campaignPersisted=true;for(const ship of battle.ships.filter(s=>s.team==='P')){const entry=campaign.ships.find(x=>x.id===ship.campaignShipId);if(!entry)continue;if(!ship.dead&&ship.outcome!=='captured')recoverSurvivingCraft(battle,ship);entry.state=snapshotShip(ship);entry.battles=(entry.battles||0)+1;entry.xp=(entry.xp||0)+1;const keel=ship.modules.find(m=>m.id==='keel');if(ship.outcome==='captured')entry.status='captured';else if(ship.dead&&(!keel||keel.hp<=0))entry.status='lost';entry.history??=[];entry.history.push(`Day ${campaign.day}: ${ship.outcome||(ship.dead?'combat ineffective':'survived')} at ${campaign.location}.`);if(ship.historyNote)entry.history.push(ship.historyNote);entry.history=entry.history.slice(-20)}campaign.log??=[];campaign.log.push(`Day ${campaign.day}: battle concluded (${battle.winner||'no decisive winner'}).`);campaign.log=campaign.log.slice(-50);saveCampaign(campaign)}
function resupplyCost(entry){if(!entry.state)return 0;let cost=0;for(const sm of entry.state.modules||[]){const placement=entry.blueprint?.placements?.find((p,i)=>`m${i}`===sm.id);const spec=placement?MODULES[placement.moduleId]:null;if(spec&&Number.isFinite(spec.ammo)&&Number.isFinite(sm.ammo))cost+=Math.max(0,spec.ammo-sm.ammo)*(spec.type==='missile'?9:.08);if(sm.initialCraft&&sm.craftInventory){cost+=Math.max(0,(sm.initialCraft.fighter||0)-(sm.craftInventory.fighter||0))*38;cost+=Math.max(0,(sm.initialCraft.sensorDrone||0)-(sm.craftInventory.sensorDrone||0))*16}}return Math.ceil(cost)}
export function repairShip(id){const s=campaign.ships.find(x=>x.id===id);if(!s||s.status!=='active')return false;const structural=80+(s.state?.modules?.filter(m=>m.hp<=0).length||0)*20,resupply=resupplyCost(s),cost=structural+resupply;if(campaign.credits<cost)return false;campaign.credits-=cost;s.state=null;s.history.push(`Day ${campaign.day}: repaired, serviced and replenished for ${cost} cr.`);saveCampaign(campaign);return true}
export function setActiveShips(ids){campaign.activeShipIds=[...new Set(ids)].slice(0,6);saveCampaign(campaign)}
export function advanceDay(n=1){campaign.day+=n;saveCampaign(campaign)}
