import {campaign,saveCampaign} from './campaign-core.js';
import {FACTIONS,playerStanding} from './factions-system.js?v=77';
import {factionStrategicSummary,factionForcePlan,commitFactionForce,advanceFactionStrategy} from './faction-strategy.js?v=77';
import {corridorSummary} from './lacuna-corridor.js?v=97';

const GOODS={
 precisionParts:{label:'precision components',basePrice:34,demand:1.35},
 reactorParts:{label:'reactor spares',basePrice:42,demand:1.45},
 medicine:{label:'medical supplies',basePrice:28,demand:1.25},
 electronics:{label:'specialist electronics',basePrice:38,demand:1.30},
 machinery:{label:'replacement machinery',basePrice:31,demand:1.20},
 archiveData:{label:'archival datasets',basePrice:55,demand:.55,export:true},
 fabrication:{label:'specialist fabrication',basePrice:48,demand:.62,export:true},
 continuityComponents:{label:'continuity-standard components',basePrice:64,demand:.50,export:true}
};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rand(tag){let x=hash(`${campaign.seed||1}|${campaign.day}|${tag}`);x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}
function sourceSystem(id){return FACTIONS[id]?.home||'Sol Gateway'}
function freshMarket(){return{populationBand:'400–800',demand:{precisionParts:1.35,reactorParts:1.45,medicine:1.25,electronics:1.30,machinery:1.20},exports:{archiveData:.55,fabrication:.62,continuityComponents:.50},volume:0,lastDay:campaign.day}}
function fresh(){return{initialised:false,nextId:1,missions:[],history:[],market:freshMarket(),pressure:{traffic:0,military:0,political:0},lastScheduledDay:0,lastResolvedDay:0,trustWarning:false}}
function state(){campaign.corridorTraffic??=fresh();const s=campaign.corridorTraffic;s.missions??=[];s.history??=[];s.market??=freshMarket();s.pressure??={traffic:0,military:0,political:0};return s}
function log(text){const s=state();s.history.push({day:campaign.day,text});s.history=s.history.slice(-60);campaign.log??=[];campaign.log.push(`Day ${campaign.day}: CORRIDOR TRAFFIC — ${text}`);campaign.log=campaign.log.slice(-100)}
function activePermitEntries(){const c=corridorSummary();return Object.entries(c.permits||{}).filter(([,p])=>p?.status==='active')}
function missionType(id,permit){if(id==='central')return'inspection';if(id==='meridian')return permit.type==='trade'?'commercial':'logistics';if(id==='orpheus')return permit.type==='trade'?'industrial':'survey';if(id==='blackWake')return'courier';if(FACTIONS[id]?.kind==='government'||FACTIONS[id]?.kind==='militia')return'security';if(permit.type==='trade')return'commercial';return'diplomatic'}
function pickImport(id,n){const keys=Object.keys(state().market.demand);return keys[Math.floor(rand(`import:${id}:${n}`)*keys.length)]}
function pickExport(id,n){const keys=Object.keys(state().market.exports);return keys[Math.floor(rand(`export:${id}:${n}`)*keys.length)]}
function etaFor(id,n){const posture=factionStrategicSummary(id,sourceSystem(id))?.posture||'normal';const base=posture==='strained'?6:posture==='defensive'?8:posture==='critical'?12:4;return Math.round(base+rand(`eta:${id}:${n}`)*4)}
function canProject(id){const x=factionStrategicSummary(id,sourceSystem(id));return x&&x.posture!=='critical'&&x.readiness>=22&&x.wealth>=8}
function scheduleMission(id,permit){const s=state(),n=s.nextId++,type=missionType(id,permit),source=sourceSystem(id),strategic=factionStrategicSummary(id,source);if(!strategic||!canProject(id))return null;const plan=factionForcePlan(id,source,1,type==='security'||type==='inspection'?'defence':'general');if((plan.count||0)<1)return null;commitFactionForce(id,plan);const trade=permit.type==='trade',cargo=trade?{import:pickImport(id,n),export:pickExport(id,n),units:2+Math.floor(rand(`cargo:${id}:${n}`)*5)}:null;const m={id:`CT${n}`,factionId:id,type,permit:permit.type,origin:source,createdDay:campaign.day,etaDay:campaign.day+etaFor(id,n),status:'enroute',cargo,escortShips:plan.count,maxClass:plan.maxClass,postureAtLaunch:strategic.posture,standingAtLaunch:playerStanding(id)};s.missions.push(m);log(`${FACTIONS[id]?.name||id} dispatches a ${type} mission from ${source} toward Lacuna (ETA day ${m.etaDay}).`);return m}
function maybeSchedule(){const s=state();if(s.lastScheduledDay===campaign.day)return[];advanceFactionStrategy(campaign.day);const made=[];for(const [id,permit] of activePermitEntries()){if(s.missions.some(m=>m.factionId===id&&['enroute','arrived','holding'].includes(m.status)))continue;const strategic=factionStrategicSummary(id,sourceSystem(id));if(!strategic)continue;let p=.18+(permit.type==='trade'?.18:.06)+(strategic.wealth||0)/500+(strategic.readiness||0)/700;if(strategic.posture==='strained')p-=.08;if(strategic.posture==='defensive')p-=.16;if(strategic.posture==='critical')p=0;if(rand(`schedule:${id}:${campaign.day}`)<clamp(p,0,.72)){const m=scheduleMission(id,permit);if(m)made.push(m)}}s.lastScheduledDay=campaign.day;return made}
function marketPrice(key){const m=state().market;const g=GOODS[key];if(!g)return 0;const pressure=g.export?(m.exports[key]??g.demand):(m.demand[key]??g.demand);return Math.round(g.basePrice*clamp(pressure,.45,1.8))}
function resolveMission(m){if(m.status!=='enroute'||m.etaDay>campaign.day)return false;const s=state(),corr=corridorSummary(),routeOpen=corr.routeStatus!=='closed'&&corr.security.integrity>=70;if(!routeOpen){m.status='holding';m.outcome='route-closed';log(`${FACTIONS[m.factionId]?.name||m.factionId} mission reaches Lacuna but holds outside the corridor because ORISON is closed.`);return true}m.status='arrived';m.arrivalDay=campaign.day;s.pressure.traffic=clamp(s.pressure.traffic+4+(m.permit==='trade'?5:2),0,100);if(['security','inspection'].includes(m.type))s.pressure.military=clamp(s.pressure.military+7,0,100);if(m.cargo){const buy=marketPrice(m.cargo.import),sell=marketPrice(m.cargo.export),units=m.cargo.units,flow=Math.round((buy+sell)*units*.12);campaign.credits=(campaign.credits||0)+flow;campaign.supplies=(campaign.supplies||0)+Math.max(1,Math.floor(units/2));s.market.volume+=units;s.market.demand[m.cargo.import]=clamp((s.market.demand[m.cargo.import]||1)-.04*units,.7,1.6);s.market.exports[m.cargo.export]=clamp((s.market.exports[m.cargo.export]||.6)+.025*units,.45,1.35);log(`${FACTIONS[m.factionId]?.name||m.factionId} ${m.type} mission arrives with ${units} units of ${GOODS[m.cargo.import].label}; controlled exchange generates ${flow} credits.`)}else log(`${FACTIONS[m.factionId]?.name||m.factionId} ${m.type} mission arrives under its ${m.permit} permit.`);return true}
function settleDepartures(){const s=state();for(const m of s.missions)if(m.status==='arrived'&&campaign.day-(m.arrivalDay||campaign.day)>=2){m.status='departed';m.departureDay=campaign.day;s.pressure.traffic=clamp(s.pressure.traffic-2,0,100);if(['security','inspection'].includes(m.type))s.pressure.military=clamp(s.pressure.military-3,0,100)}}
function updatePressure(){const s=state(),corr=corridorSummary();s.pressure.traffic=clamp(s.pressure.traffic*.97+(corr.traffic?.licensedTrips||0)*.08,0,100);s.pressure.political=clamp((corr.interested?.filter(x=>!x.permit).length||0)*5+s.pressure.military*.35,0,100);const t=campaign.mainPlot?.peregrineContact;if(t&&s.pressure.traffic>55&&!s.trustWarning){t.trust=(t.trust||0)-1;s.trustWarning=true;log('PEREGRINE warns that outside traffic is becoming too dense for the original continuity safeguards; trust falls by 1.')}if(s.pressure.traffic<35)s.trustWarning=false}
export function syncCorridorTraffic(){const s=state();maybeSchedule();let changed=false;for(const m of s.missions)changed=resolveMission(m)||changed;settleDepartures();updatePressure();s.lastResolvedDay=campaign.day;s.missions=s.missions.filter(m=>m.status!=='departed'||campaign.day-(m.departureDay||0)<30);if(changed)saveCampaign(campaign);return trafficSummary()}
export function advanceCorridorTraffic(days=1){days=Math.max(1,Math.min(14,Math.floor(days||1)));campaign.day+=days;advanceFactionStrategy(campaign.day);const out=syncCorridorTraffic();saveCampaign(campaign);return{ok:true,days,summary:out}}
export function trafficSummary(){const s=state(),missions=s.missions.map(m=>({...m,factionName:FACTIONS[m.factionId]?.name||m.factionId}));const prices={};for(const k of Object.keys(GOODS))prices[k]={label:GOODS[k].label,price:marketPrice(k),export:!!GOODS[k].export};return{...s,missions,prices,enroute:missions.filter(m=>m.status==='enroute'),present:missions.filter(m=>m.status==='arrived'||m.status==='holding'),strategic:activePermitEntries().map(([id,p])=>({id,name:FACTIONS[id]?.name||id,permit:p.type,source:sourceSystem(id),...factionStrategicSummary(id,sourceSystem(id))}))}}
if(typeof window!=='undefined')window.__corridorTraffic={syncCorridorTraffic,advanceCorridorTraffic,trafficSummary};
