import {campaign,saveCampaign} from './campaign-core.js';
import {FACTIONS,relation,changePlayerStanding} from './factions-system.js?v=77';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CORE_SYSTEMS=['Sol Gateway','Haven Reach','Pelagos','Kestrel','Nadir'];
const PREFS={
 central:['secure','trade','suppress'],haven:['trade','secure','diplomacy'],pelagosA:['influence','secure','trade'],pelagosB:['trade','diplomacy','secure'],kestrel:['industry','secure','influence'],nadir:['secure','trade','suppress'],
 meridian:['trade','influence','diplomacy'],orpheus:['industry','influence','trade'],frontierGuard:['suppress','secure','trade'],redKnives:['raid','influence','network'],blackWake:['network','trade','raid']
};
const TYPE={
 secure:{label:'Secure home system',summary:'Protect the faction core, shipping lanes and local freedom of movement.'},
 trade:{label:'Protect commercial access',summary:'Keep profitable routes open and reduce disruption to ordinary traffic.'},
 industry:{label:'Expand industrial capacity',summary:'Build and feed productive capacity instead of relying on abstract wealth alone.'},
 suppress:{label:'Suppress strategic rival',summary:'Apply bounded pressure to a hostile rival without requiring faction extermination.'},
 influence:{label:'Expand regional influence',summary:'Build a durable local presence where the faction already has a plausible foothold.'},
 raid:{label:'Raid vulnerable commerce',summary:'Exploit weakly protected traffic and logistics while avoiding ruinous fleet losses.'},
 network:{label:'Protect covert network',summary:'Preserve underworld access, hidden logistics and deniable commercial links.'},
 diplomacy:{label:'Stabilise key relationship',summary:'Improve a useful relationship and reduce the chance of unnecessary strategic escalation.'}
};
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(tag){let x=hash(`${campaign.seed||1}|${tag}`);x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}
function fresh(){return{version:1,lastDay:campaign.day||1,nextId:1,byFaction:{},history:[]}}
function state(){campaign.factionGoals??=fresh();const s=campaign.factionGoals;s.byFaction??={};s.history??=[];s.nextId??=1;s.lastDay??=campaign.day||1;return s}
function log(text){const s=state();s.history.push({day:campaign.day,text});s.history=s.history.slice(-100);campaign.log??=[];campaign.log.push(`Day ${campaign.day}: STRATEGIC GOALS — ${text}`);campaign.log=campaign.log.slice(-180)}
function presence(id,system){return campaign.factionPresence?.[system]?.[id]||0}
function econ(system){return campaign.strategicEconomy?.nodes?.[system]||null}
function worstRival(id){return Object.keys(FACTIONS).filter(x=>x!==id).map(x=>({id:x,r:relation(id,x)})).sort((a,b)=>a.r-b.r)[0]?.id||null}
function bestPartner(id){return Object.keys(FACTIONS).filter(x=>x!==id&&FACTIONS[x]?.lawful===FACTIONS[id]?.lawful).map(x=>({id:x,r:relation(id,x)})).sort((a,b)=>b.r-a.r)[0]?.id||null}
function sharedSystem(a,b){return CORE_SYSTEMS.map(system=>({system,score:Math.min(presence(a,system),presence(b,system))})).sort((x,y)=>y.score-x.score)[0]?.system||FACTIONS[a]?.home||'Haven Reach'}
function systemReachableByIdentity(id,system){const kind=FACTIONS[id]?.kind;if(kind==='merchant'||kind==='industrial'||kind==='militia')return system!=='Sol Gateway'||id==='meridian';if(kind==='pirate')return['Pelagos','Kestrel','Nadir'].includes(system);return FACTIONS[id]?.home===system}
function marketWeight(system){if(system==='Pelagos')return 1;if(system==='Haven Reach')return .8;if(system==='Kestrel')return .5;if(system==='Nadir')return .45;return .2}
function targetSystem(id,type,cycle=0){const home=FACTIONS[id]?.home||'Haven Reach';if(['secure','industry'].includes(type))return home;if(type==='suppress')return sharedSystem(id,worstRival(id));if(type==='diplomacy')return sharedSystem(id,bestPartner(id));const options=CORE_SYSTEMS.map(system=>({system,p:presence(id,system),market:econ(system)?.tradeSecurity??.7,output:econ(system)?.industrialOutput??.7})).filter(x=>x.p>.025||systemReachableByIdentity(id,x.system));if(type==='trade')options.sort((a,b)=>(b.p*(1-b.market*.35))-(a.p*(1-a.market*.35)));else if(type==='raid')options.sort((a,b)=>(b.market+marketWeight(b.system))-(a.market+marketWeight(a.system)));else if(type==='network')options.sort((a,b)=>b.p-a.p||marketWeight(b.system)-marketWeight(a.system));else options.sort((a,b)=>(a.p||0)-(b.p||0)||marketWeight(b.system)-marketWeight(a.system));const count=Math.max(1,options.length),i=(cycle+Math.floor(rnd(`${id}:${type}:${cycle}`)*count))%count;return options[i]?.system||home}
function makeGoal(id,slot,cycle=0){const prefs=PREFS[id]||['secure','trade','diplomacy'],type=prefs[(slot+cycle)%prefs.length],targetFaction=(type==='suppress'||type==='raid')?worstRival(id):type==='diplomacy'?bestPartner(id):null,target=targetSystem(id,type,cycle),priority=clamp(.62+slot*.13+rnd(`${id}:${type}:${cycle}:priority`)*.18,.55,.96),duration=Math.round(85+rnd(`${id}:${type}:${cycle}:duration`)*55),s=state();return{id:`FG${s.nextId++}`,factionId:id,type,title:TYPE[type].label,text:TYPE[type].summary,targetSystem:target,targetFaction,priority:+priority.toFixed(2),progress:0,status:'active',createdDay:campaign.day,deadline:campaign.day+duration,playerContribution:0,lastPlayerTaskDay:null,cycle}}
function ensureGoals(){const s=state();let dirty=false;for(const id of Object.keys(FACTIONS)){s.byFaction[id]??=[];const active=s.byFaction[id].filter(g=>g.status==='active');for(let slot=active.length;slot<2;slot++){s.byFaction[id].push(makeGoal(id,slot,Math.floor((campaign.day||1)/90)));dirty=true}}if(dirty)saveCampaign(campaign);return s}
function fleetFront(f){return(campaign.strategicFronts?.fronts||[]).find(x=>x.id===f.frontId&&x.status==='active')||null}
function fleetGoal(id,system){return(state().byFaction[id]||[]).filter(g=>g.status==='active'&&g.targetSystem===system).sort((a,b)=>b.priority-a.priority)[0]||null}
function missionFor(goal,f,front){if(!goal)return null;if(goal.type==='secure')return front&&f.role==='defend'?'reinforce':'patrol';if(goal.type==='trade'||goal.type==='industry'||goal.type==='network')return'convoyEscort';if(goal.type==='suppress')return front&&Math.abs(front.control||0)>8?'blockade':'raid';if(goal.type==='raid')return'raid';if(goal.type==='influence'||goal.type==='diplomacy')return'patrol';return null}
function steerFleets(day){for(const f of campaign.strategicFronts?.fleets||[]){if(f.status!=='deployed'||f.lastGoalSteerDay===day)continue;const goal=fleetGoal(f.factionId,f.system);if(!goal)continue;const front=fleetFront(f),mission=missionFor(goal,f,front);if(!mission)continue;const due=!f.missionUntil||day>=f.missionUntil-1,override=rnd(`${f.id}:${goal.id}:${day}`)<.18*goal.priority;if(!due&&!override)continue;const changed=f.mission!==mission;f.mission=mission;f.missionTarget=goal.targetSystem;f.missionSince=day;f.missionUntil=day+3+Math.floor(rnd(`${f.id}:${goal.id}:duration:${day}`)*4);f.goalId=goal.id;f.lastGoalSteerDay=day;if(changed)log(`${FACTIONS[f.factionId]?.short||f.factionId} task force ${f.id} adopts ${mission} duty in support of “${goal.title}”.`)}}
function progressRate(g){const node=econ(g.targetSystem),own=presence(g.factionId,g.targetSystem),rival=g.targetFaction?presence(g.targetFaction,g.targetSystem):0,front=(campaign.strategicFronts?.fronts||[]).find(f=>f.status==='active'&&f.system===g.targetSystem&&(f.a===g.factionId||f.b===g.factionId)),fleet=(campaign.strategicFronts?.fleets||[]).find(f=>f.status==='deployed'&&f.factionId===g.factionId&&f.system===g.targetSystem);if(g.type==='secure'){const p=campaign.factions?.[g.factionId]?.pressure||0;return .25+.32*(1-clamp(p/100,0,1))+.18*clamp(own/.7,0,1)}if(g.type==='trade')return .18+.42*(node?.tradeSecurity??.55)+(node?.shortages?.length?-.08:.05);if(g.type==='industry')return .12+.42*clamp(node?.industrialOutput??.45,0,1.1);if(g.type==='suppress'){const activeFront=front?.status==='active'? .12:0,mission=(fleet&&['raid','blockade','patrol'].includes(fleet.mission))? .18:0;return .12+activeFront+mission+.12*clamp(own-rival+.5,0,1)}if(g.type==='influence')return .12+.36*clamp(own/.6,0,1);if(g.type==='raid'){const mission=(fleet&&['raid','blockade'].includes(fleet.mission))? .28:0;return .08+mission+.14*(1-(node?.tradeSecurity??.7))}if(g.type==='network')return .15+.28*clamp(own/.55,0,1)+.08*clamp((node?.stocks?.restricted??40)/70,0,1);if(g.type==='diplomacy')return .16+.30*clamp((relation(g.factionId,g.targetFaction)+100)/200,0,1);return .2}
function applyGoalEconomics(g){const fs=campaign.factions?.[g.factionId];if(!fs)return;if(['secure','suppress'].includes(g.type)&&fs.wealth>14&&fs.readiness<82){fs.wealth=Math.max(8,fs.wealth-.018*g.priority);fs.readiness=clamp(fs.readiness+.025*g.priority,10,100)}else if(['trade','industry','influence','network'].includes(g.type)&&fs.wealth>10){fs.wealth=Math.max(8,fs.wealth-.012*g.priority)}}
function applyDiplomacy(g,day){if(!g.targetFaction||day%10!==0)return;const key=[g.factionId,g.targetFaction].sort().join('|'),cur=campaign.factionRelations?.[key];if(!Number.isFinite(cur))return;if(g.type==='diplomacy'||g.type==='trade')campaign.factionRelations[key]=clamp(cur+1,-100,100);else if((g.type==='suppress'||g.type==='raid')&&cur>-85)campaign.factionRelations[key]=clamp(cur-1,-100,100)}
function retireAndReplace(day){const s=state();for(const id of Object.keys(FACTIONS)){const arr=s.byFaction[id]||[];for(const g of arr.filter(x=>x.status==='active')){if(g.progress>=100){g.status='complete';g.completedDay=day;log(`${FACTIONS[id]?.short||id} completes strategic goal “${g.title}” in ${g.targetSystem}.`)}else if(day>g.deadline){g.status='expired';g.completedDay=day;log(`${FACTIONS[id]?.short||id} lets strategic goal “${g.title}” lapse and reprioritises.`)}}const active=arr.filter(g=>g.status==='active');while(active.length<2){const slot=active.length,cycle=Math.max(...arr.map(g=>g.cycle||0),0)+1,g=makeGoal(id,slot,cycle);arr.push(g);active.push(g);log(`${FACTIONS[id]?.short||id} adopts strategic goal “${g.title}” in ${g.targetSystem}.`)}s.byFaction[id]=arr.filter(g=>g.status==='active'||day-(g.completedDay||day)<90)}}
function stepDay(day){ensureGoals();for(const goals of Object.values(state().byFaction))for(const g of goals.filter(x=>x.status==='active')){g.progress=clamp(g.progress+progressRate(g)*g.priority,0,100);g.lastProgressDay=day;applyGoalEconomics(g);applyDiplomacy(g,day)}steerFleets(day);retireAndReplace(day)}
export function advanceFactionGoals(targetDay=campaign.day){ensureGoals();const s=state();let d=Math.floor(s.lastDay||targetDay),end=Math.max(d,Math.floor(targetDay||d)),steps=0;while(d<end&&steps<365){d++;stepDay(d);s.lastDay=d;steps++}if(steps)saveCampaign(campaign);return steps}
export function activeFactionGoals(id){advanceFactionGoals(campaign.day);return(state().byFaction[id]||[]).filter(g=>g.status==='active').map(g=>({...g}))}
export function factionGoalSummary(system=campaign.location){advanceFactionGoals(campaign.day);const goals=[];for(const [id,arr] of Object.entries(state().byFaction))for(const g of arr)if(g.status==='active'&&(g.targetSystem===system||presence(id,system)>.12))goals.push({...g,factionName:FACTIONS[id]?.short||id,targetFactionName:g.targetFaction?FACTIONS[g.targetFaction]?.short||g.targetFaction:null});return goals.sort((a,b)=>b.priority-a.priority||b.progress-a.progress)}
export function systemEconomicGoalBias(system){ensureGoals();let production=0,imports=0,security=0,weight=0;for(const [id,arr] of Object.entries(state().byFaction)){const p=presence(id,system);if(p<=.02)continue;for(const g of arr.filter(x=>x.status==='active'&&x.targetSystem===system)){const w=p*g.priority;weight+=w;if(g.type==='industry')production+=.12*w;if(g.type==='trade')imports+=.10*w;if(g.type==='secure')security+=.04*w;if(g.type==='network')imports+=.035*w;if(g.type==='influence')production+=.025*w}}return{production:clamp(production,0,.18),imports:clamp(imports,0,.16),security:clamp(security,0,.08),weight}}
function taskText(g){if(g.type==='secure'||g.type==='suppress')return'Support patrol planning, escort movements and local reconnaissance for this strategic priority.';if(g.type==='trade'||g.type==='network')return'Carry time-sensitive routing, manifests and stores needed to keep this network functioning.';if(g.type==='industry')return'Deliver engineering stores and survey data to bottlenecked industrial sites.';if(g.type==='raid')return'Provide scouting and targeting intelligence for a bounded commerce-raiding operation.';if(g.type==='diplomacy')return'Carry authenticated messages and technical data needed for the current negotiation.';return'Conduct a survey and presence mission that advances this long-term objective.'}
export function goalContracts(system=campaign.location){advanceFactionGoals(campaign.day);return factionGoalSummary(system).filter(g=>g.targetSystem===system&&((g.lastPlayerTaskDay??-999)+5<=campaign.day)&&(campaign.factionRep?.[g.factionId]??0)>-35).slice(0,4).map(g=>({id:`goal:${g.id}`,goalId:g.id,factionId:g.factionId,issuerName:g.factionName,title:`Strategic tasking: ${g.title}`,text:taskText(g),pay:Math.round(170+g.priority*180),supplyCost:['industry','secure','trade'].includes(g.type)?2:1,targetFaction:g.targetFaction,targetFactionName:g.targetFactionName}))}
export function completeGoalContract(goalId){advanceFactionGoals(campaign.day);let g=null;for(const arr of Object.values(state().byFaction)){g=arr.find(x=>x.id===goalId&&x.status==='active');if(g)break}if(!g)return{ok:false,reason:'That strategic tasking is no longer active.'};if(g.targetSystem!==campaign.location)return{ok:false,reason:`Travel to ${g.targetSystem} before undertaking this tasking.`};if((g.lastPlayerTaskDay??-999)+5>campaign.day)return{ok:false,reason:'That organisation needs time to act on your last contribution before issuing another tasking.'};const supplyCost=['industry','secure','trade'].includes(g.type)?2:1;if((campaign.supplies||0)<supplyCost)return{ok:false,reason:`You need ${supplyCost} supplies to carry out this task.`};const pay=Math.round(170+g.priority*180);campaign.supplies-=supplyCost;campaign.credits=(campaign.credits||0)+pay;campaign.day+=1;g.progress=clamp(g.progress+9+g.priority*4,0,100);g.playerContribution=(g.playerContribution||0)+1;g.lastPlayerTaskDay=campaign.day;changePlayerStanding(g.factionId,2);if(g.targetFaction)changePlayerStanding(g.targetFaction,-1);log(`Your fleet completes tasking for ${FACTIONS[g.factionId]?.short||g.factionId}: “${g.title}” (+${pay} cr).`);saveCampaign(campaign);return{ok:true,pay,goal:{...g}}}
export function goalHistory(){return[...state().history]}

ensureGoals();advanceFactionGoals(campaign.day);
if(typeof window!=='undefined'){window.__factionGoals={activeFactionGoals,factionGoalSummary,goalContracts,completeGoalContract,systemEconomicGoalBias,advanceFactionGoals};setInterval(()=>advanceFactionGoals(campaign.day),1250)}
