import {registerBattleHook} from './battle-hooks.js';
import {launchBoardingShuttle,ensureBoardingState} from './boarding-core.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const scenario=b=>b?.nonCombatScenario==='smugglerInterdiction';
const runners=b=>(b.ships||[]).filter(s=>s.interdictionRunner);
const pursuers=b=>(b.ships||[]).filter(s=>s.team==='P'&&!s.dead&&!s.civilianEscort);
function engines(s){return(s.modules||[]).filter(m=>m.type==='engine')}
function engineFrac(s){const ms=engines(s),max=ms.reduce((n,m)=>n+(m.maxHp||m.hp||1),0)||1;return ms.reduce((n,m)=>n+Math.max(0,m.hp||0),0)/max}
function sensorStrength(s){let v=(s.modules||[]).some(m=>m.type==='bridge'&&m.hp>0&&!m.disabled)?0.65:0;for(const m of s.modules||[])if(m.type==='sensor'&&m.hp>0&&!m.disabled)v+=(m.sensitivity||1)*(m.hp/Math.max(1,m.maxHp||m.hp));return v*clamp(s.sensorPowerFraction??1,.2,1)}
function ensure(b){if(!scenario(b))return null;if(b.interdictionState)return b.interdictionState;const rs=runners(b),carrier=rs[Math.floor(b.rng.next()*rs.length)];rs.forEach((s,i)=>{s.contrabandCarrier=s===carrier;s.scanQuality=0;s.scanClues=[];s.inspected=false;s.runnerIndex=i;s.exitX=7600+s.runnerIndex*160;s.compliance='fleeing';s.outcome=null});b.interdictionState={startedAt:b.t,carrierUid:carrier?.uid||null,initial:rs.length,escaped:0,destroyed:0,inspected:0,wrongBoardings:0,complete:false,deadline:96};b.log('Interdiction: five outbound civilian contacts are breaking inspection. Intelligence says one carries restricted high-value cargo. Identify, stop and board it intact.');return b.interdictionState}
function nearestPlayer(b,s){return pursuers(b).sort((a,c)=>dist(a,s)-dist(c,s))[0]||null}
function steer({battle:b,ship:s}){if(!scenario(b)||!s.interdictionRunner||s.dead||s.escaped||s.surrendered)return;ensure(b);const e=engineFrac(s),near=nearestPlayer(b,s);s.desiredAngle=0;s.throttle=e<.15?0:1;s.order=e<.15?'Drives disabled — drifting':'Flee inspection cordon';if(near&&dist(near,s)<1500&&e>.2){const side=((s.runnerIndex%2)?1:-1),offset=side*(.10+.05*(s.runnerIndex%3));s.desiredAngle=offset;s.order='Evasive escape burn'}if(e<.18&&Math.hypot(s.vx,s.vy)<260){s.surrendered=true;s.compliance='stopped';s.throttle=0;s.order='Stopped for boarding';b.log(`${s.name}: propulsion disabled; vessel is submitting to inspection.`)}}
function scan(b,dt){const st=ensure(b);if(!st)return;const ps=pursuers(b);for(const r of runners(b)){if(r.dead||r.escaped||r.inspected)continue;let best=0;for(const p of ps){const strength=sensorStrength(p),range=1400+strength*950,q=1-dist(p,r)/Math.max(1,range);if(q>0)best=Math.max(best,q*(.35+strength*.13))}r.scanQuality=clamp((r.scanQuality||0)+best*dt*.36,0,1);const q=r.scanQuality;if(q>.18&&!r.scanClues.includes('mass'))r.scanClues.push('mass');if(q>.42&&!r.scanClues.includes('thermal'))r.scanClues.push('thermal');if(q>.72&&!r.scanClues.includes('registry'))r.scanClues.push('registry')}}
function suspicion(r){let n=0;if(r.scanClues?.includes('mass'))n+=r.contrabandCarrier?2:((r.runnerIndex===1||r.runnerIndex===4)?2:0);if(r.scanClues?.includes('thermal'))n+=r.contrabandCarrier?2:(r.runnerIndex===3?2:r.runnerIndex===1?1:0);if(r.scanClues?.includes('registry'))n+=r.contrabandCarrier?3:(r.runnerIndex===0?3:0);return n}
function inspectCaptured(b,r){const st=ensure(b);if(r.inspected)return;r.inspected=true;st.inspected++;if(r.contrabandCarrier){st.complete=true;b.interdictionResult={success:true,carrier:r.uid,payoutFactor:r.dead?0:.95,wrongBoardings:st.wrongBoardings,destroyed:st.destroyed,escaped:st.escaped};b.winner='P';b.log(`${r.name}: boarding team confirms restricted high-value cargo. Target secured intact.`)}else{st.wrongBoardings++;b.log(`${r.name}: boarding inspection finds no target cargo. Intelligence assessment was wrong for this vessel.`)}}
function checkBoarding(b){for(const r of runners(b)){if(r.dead||r.escaped||r.inspected)continue;if(r.outcome==='captured'||r.boardedByTeam==='P')inspectCaptured(b,r)}}
function escapeAndFailure(b){const st=ensure(b);if(!st||st.complete)return;for(const r of runners(b)){if(r.dead&&!r._countedDead){r._countedDead=true;st.destroyed++;if(r.contrabandCarrier){st.complete=true;b.interdictionResult={success:false,reason:'carrierDestroyed',payoutFactor:0,wrongBoardings:st.wrongBoardings,destroyed:st.destroyed,escaped:st.escaped};b.winner='E';b.log('Interdiction failed: the suspected cargo carrier was destroyed before inspection.');return}}if(!r.dead&&!r.escaped&&r.x>=r.exitX){r.escaped=true;r._countedEscape=true;st.escaped++;b.log(`${r.name}: escaped the interception volume.`);if(r.contrabandCarrier){st.complete=true;b.interdictionResult={success:false,reason:'carrierEscaped',payoutFactor:0,wrongBoardings:st.wrongBoardings,destroyed:st.destroyed,escaped:st.escaped};b.winner='E';b.log('Interdiction failed: the contraband carrier escaped.');return}}}if(b.t-st.startedAt>=st.deadline){st.complete=true;b.interdictionResult={success:false,reason:'timeout',payoutFactor:0,wrongBoardings:st.wrongBoardings,destroyed:st.destroyed,escaped:st.escaped};b.winner='E';b.log('Interdiction failed: inspection window closed.')}}

registerBattleHook('beforeStep','interdiction-init-scan',({battle,dt})=>{if(!scenario(battle))return;ensure(battle);scan(battle,dt)},225);
registerBattleHook('beforeApplySystems','interdiction-runner-flight',steer,230);
registerBattleHook('beforeFireWeapons','interdiction-runner-ceasefire',(ctx)=>{if(scenario(ctx.battle)&&ctx.ship?.interdictionRunner)ctx.handled=true},230);
registerBattleHook('afterStep','interdiction-objective',({battle})=>{if(!scenario(battle))return;checkBoarding(battle);escapeAndFailure(battle);if(!battle.interdictionState?.complete&&battle.winner)battle.winner=null},210);

export function interdictionSummary(b){const st=scenario(b)?ensure(b):null;if(!st)return null;return{...st,timeRemaining:Math.max(0,st.deadline-(b.t-st.startedAt)),runners:runners(b).map(r=>({uid:r.uid,name:r.name,dead:r.dead,escaped:r.escaped,stopped:r.surrendered||engineFrac(r)<.18,engineFrac:+engineFrac(r).toFixed(2),scanQuality:+(r.scanQuality||0).toFixed(2),clues:[...(r.scanClues||[])],suspicion:suspicion(r),inspected:!!r.inspected}))}}
export function orderBoarding(b,uid){if(!scenario(b))return{ok:false,reason:'No interdiction is active.'};const r=runners(b).find(x=>x.uid===uid&&!x.dead&&!x.escaped);if(!r)return{ok:false,reason:'Target is unavailable.'};if(!(r.surrendered||engineFrac(r)<.18))return{ok:false,reason:'Disable or compel the vessel to stop before boarding.'};const ships=pursuers(b).sort((a,c)=>dist(a,r)-dist(c,r));for(const s of ships){ensureBoardingState(s);if(launchBoardingShuttle(b,s,r,'capture'))return{ok:true,source:s.name,method:'shuttle'}}const close=ships.find(s=>{const rv=Math.hypot((s.vx||0)-(r.vx||0),(s.vy||0)-(r.vy||0));return dist(s,r)<85&&rv<65});if(close){r.outcome='captured';r.boardedByTeam='P';r.surrendered=true;b.log(`${close.name}: matched vectors and completed direct-dock boarding of ${r.name}.`);inspectCaptured(b,r);return{ok:true,source:close.name,method:'direct dock'}}return{ok:false,reason:'No ready boarding shuttle. Match vectors within 85 m and below 65 m/s relative speed for direct-dock inspection.'}}
if(typeof window!=='undefined'){window.__interdictionSummary=()=>interdictionSummary(window.__fleetBattle);window.__orderInterdictionBoarding=uid=>orderBoarding(window.__fleetBattle,uid)}
