import {campaign,saveCampaign} from './campaign-core.js';

const RECORDS={
 arrivals:{name:'Founding arrivals',cost:4,days:1,text:'The Founding Vault confirms Concord formed from multiple independent arrival waves over decades. Survey crews, failed expeditions, defectors and civilian families reached Lacuna through several damaged or improvised route solutions. No single founding government or colony charter exists.'},
 burn:{name:'The Burn telemetry',cost:7,days:2,text:'Closure telemetry shows two obsolete route keys were energised within minutes of each other. Their field solutions interfered at the Lacuna endpoint, producing a runaway resonance, lethal shear events and several transient arrival signatures that did not correspond to any scheduled vessel.'},
 ledger:{name:'Sealed routing ledger',cost:9,days:2,text:'The final routing ledger shows that after the Burn, Concord deliberately destroyed public route keys and scattered the surviving technical archive. One complete copy left Lacuna aboard a small courier bound for a continuity site identified only as ORISON. The courier never returned.'}
};
function fresh(){return{opened:false,access:null,records:{arrivals:false,burn:false,ledger:false},history:[],appendixGranted:false,remoteReconstruction:false,complete:false,nextLead:null}}
function ensure(){campaign.mainPlot??={};campaign.mainPlot.vault??=fresh();const v=campaign.mainPlot.vault;v.records??={arrivals:false,burn:false,ledger:false};v.history??=[];return v}
function concord(){return campaign.mainPlot?.concord}
function available(){return campaign.location==='Lacuna Reach'&&!!concord()?.complete}
function add(text){const v=ensure();v.history.push({day:campaign.day,text});campaign.log??=[];campaign.log.push(`Day ${campaign.day}: Founding Vault — ${text}`)}
function trust(){return campaign.mainPlot?.lacunaInner?.trust??0}
function canRead(id,v){if(v.access==='full')return true;if(v.access==='restricted')return id!=='ledger'||v.appendixGranted;if(v.access==='remote')return true;return false}
function finishIfReady(){const v=ensure();if(v.complete)return;if(Object.values(v.records).every(Boolean)){v.complete=true;v.nextLead='ORISON';campaign.mainPlot.act='lacuna-orison';add('Archive synthesis complete. The Burn was real, the route closure was deliberate, and a full surviving copy of the route archive departed for a continuity site called ORISON. Its location is not present in Concord’s surviving public charts.')}}
export function vaultSummary(){const v=ensure(),c=concord();return{...v,available:available(),concordAccess:c?.archiveAccess||'denied',trust:trust(),records:Object.entries(RECORDS).map(([id,r])=>({id,...r,resolved:!!v.records[id],available:v.opened&&canRead(id,v)})),canOpen:available()&&!v.opened,canRequestAppendix:v.opened&&v.access==='restricted'&&!v.appendixGranted,canRemote:v.opened&&v.access==='denied'&&!v.remoteReconstruction}}
export function openVault(){const v=ensure(),c=concord();if(!available())return{ok:false,reason:'Concord diplomacy has not yet reached a settled state.'};if(v.opened)return{ok:false,reason:'The closure archive is already open.'};v.opened=true;v.access=c?.archiveAccess==='invited'?'full':c?.archiveAccess==='restricted'?'restricted':'denied';campaign.day+=1;if(v.access==='full')add('Concord grants supervised physical access to the Founding Vault. Speaker Rhee assigns an archivist and opens the original closure-era records.');else if(v.access==='restricted')add('Concord transmits selected extracts from the Founding Vault. The sealed routing appendix remains withheld.');else add('Concord denies archive access. The fleet can only reconstruct fragments from captured telemetry, relay timing and the outer station’s surviving buffers.');saveCampaign(campaign);return{ok:true}}
export function inspectVaultRecord(id){const v=ensure(),r=RECORDS[id];if(!v.opened)return{ok:false,reason:'Open the closure archive first.'};if(!r)return{ok:false,reason:'Unknown archive record.'};if(v.records[id])return{ok:false,reason:'That record has already been reconstructed.'};if(!canRead(id,v))return{ok:false,reason:'That record is still sealed under the current Concord arrangement.'};if(campaign.supplies<r.cost)return{ok:false,reason:`Reconstructing this record requires ${r.cost} supplies.`};campaign.supplies-=r.cost;campaign.day+=r.days;v.records[id]=true;add(`${r.name}: ${r.text}`);finishIfReady();saveCampaign(campaign);return{ok:true}}
export function requestSealedAppendix(){const v=ensure();if(!v.opened||v.access!=='restricted')return{ok:false,reason:'There is no restricted appendix to request under the current arrangement.'};if(v.appendixGranted)return{ok:false,reason:'The sealed appendix is already available.'};campaign.day+=2;if(trust()>=3){v.appendixGranted=true;add('After two days of review, Concord grants one-time supervised access to the sealed routing appendix. The Limited Contact Protocol remains unchanged.');}else{add('Concord refuses access to the sealed routing appendix. Speaker Rhee says the current trust level does not justify releasing a complete route record.');}saveCampaign(campaign);return{ok:true,granted:v.appendixGranted}}
export function reconstructDeniedArchive(){const v=ensure();if(!v.opened||v.access!=='denied')return{ok:false,reason:'Remote reconstruction is only relevant while Concord denies archive access.'};if(v.remoteReconstruction)return{ok:false,reason:'Remote archive reconstruction has already been attempted.'};if(campaign.supplies<18)return{ok:false,reason:'Remote reconstruction requires 18 supplies.'};campaign.supplies-=18;campaign.day+=3;v.remoteReconstruction=true;v.access='remote';add('The fleet cross-correlates outer-station logs, captured picket telemetry and relay timing. The result is incomplete and provenance is weaker than direct Vault access, but enough structure survives to reconstruct the closure record without Concord cooperation.');saveCampaign(campaign);return{ok:true}}
export function respectArchiveBoundary(){const v=ensure();if(v.access!=='restricted'||v.records.ledger)return{ok:false,reason:'There is no unresolved restricted archive boundary.'};v.complete=true;v.nextLead=null;campaign.mainPlot.act='lacuna-concord-limited';add('Fleet accepts the archive boundary and closes the Lacuna investigation without obtaining the sealed routing ledger. Concord notes the restraint positively.');if(campaign.mainPlot?.lacunaInner)campaign.mainPlot.lacunaInner.trust=Math.min(8,(campaign.mainPlot.lacunaInner.trust||0)+1);saveCampaign(campaign);return{ok:true}}
if(typeof window!=='undefined')window.__lacunaVault={vaultSummary,openVault,inspectVaultRecord,requestSealedAppendix,reconstructDeniedArchive,respectArchiveBoundary};
