import {campaign,saveCampaign,persistBattleResults} from './campaign-core.js';
import {registerBattleHook} from './battle-hooks.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SEARCH={
 departure:{name:'Courier departure vector',summary:'Reconstruct the courier’s last verified burn from closure-era tracking fragments.',cost:5,days:1,text:'The courier departed on a deliberately inefficient high-inclination burn. Its trajectory was designed to hide the destination from ordinary Lacuna traffic rather than reach another gate.'},
 timing:{name:'Pulsar timing residue',summary:'Use the courier recorder timestamps and old timing standards to recover a deep-system navigation baseline.',cost:6,days:2,text:'A timing correction embedded in the departure packet references a pulsar pair only useful far outside the inhabited inner system. The baseline narrows ORISON to a distant dark-body orbit.'},
 drift:{name:'Closure-era ephemeris drift',summary:'Propagate the old solution forward through decades of orbital drift and missing survey updates.',cost:8,days:2,text:'The corrected solution converges on a cold dwarf planetoid well beyond normal Lacuna shipping. A weak artificial occultation pattern is consistent with a buried or heavily shielded facility.'}
};
function fresh(){return{search:{departure:false,timing:false,drift:false},located:false,locationDay:null,disclosure:null,approaches:0,accessGranted:false,forcedEntry:false,siteStatus:null,courierFound:false,continuityLock:false,clues:[],history:[],complete:false}}
function ensure(){campaign.mainPlot??={};campaign.mainPlot.orison??=fresh();const o=campaign.mainPlot.orison;o.search??={departure:false,timing:false,drift:false};o.clues??=[];o.history??=[];return o}
function vault(){return campaign.mainPlot?.vault}
function concord(){return campaign.mainPlot?.concord}
function inner(){return campaign.mainPlot?.lacunaInner}
function unlocked(){return campaign.location==='Lacuna Reach'&&vault()?.complete&&vault()?.nextLead==='ORISON'}
function add(text){const o=ensure();o.history.push({day:campaign.day,text});campaign.log??=[];campaign.log.push(`Day ${campaign.day}: ORISON — ${text}`)}
function locateIfReady(){const o=ensure();if(o.located)return;if(Object.values(o.search).every(Boolean)){o.located=true;o.locationDay=campaign.day;o.clues.push({day:campaign.day,text:'ORISON is a continuity facility hidden beneath the thermal profile of a cold dwarf planetoid far outside Lacuna’s inhabited traffic envelope. No active beacon is transmitting, but something periodically occults the background exactly where the old solution predicts.'});add('ORISON location reconstructed. Conventional transit is possible, but the site appears to be under deliberate emission control.')}}
function credentialQuality(){const v=vault(),c=concord();if(c?.archiveAccess==='invited'&&v?.records?.ledger)return 1;if(v?.appendixGranted&&v?.records?.ledger)return .9;if(v?.access==='remote'&&v?.records?.ledger)return .45;return .2}
export function orisonSummary(){const o=ensure();return{...o,available:unlocked(),pending:campaign.pendingEncounter?.kind==='orisonApproach',credentialQuality:credentialQuality(),canShare:o.located&&!o.disclosure,search:Object.entries(SEARCH).map(([id,r])=>({id,...r,resolved:!!o.search[id],available:unlocked()&&!o.search[id]})),canApproach:o.located&&!o.accessGranted&&!campaign.pendingEncounter}}
export function investigateOrisonLead(id){const o=ensure(),r=SEARCH[id];if(!unlocked())return{ok:false,reason:'The Founding Vault has not produced the ORISON lead.'};if(!r)return{ok:false,reason:'Unknown ORISON search operation.'};if(o.search[id])return{ok:false,reason:'That search operation is already complete.'};if(campaign.supplies<r.cost)return{ok:false,reason:`This reconstruction requires ${r.cost} supplies.`};campaign.supplies-=r.cost;campaign.day+=r.days;o.search[id]=true;o.clues.push({day:campaign.day,text:`${r.name}: ${r.text}`});locateIfReady();saveCampaign(campaign);return{ok:true}}
export function setOrisonDisclosure(choice){const o=ensure();if(!o.located)return{ok:false,reason:'Locate ORISON first.'};if(o.disclosure)return{ok:false,reason:'The ORISON disclosure decision is already recorded.'};if(!['share','compartment'].includes(choice))return{ok:false,reason:'Unknown disclosure choice.'};o.disclosure=choice;if(choice==='share'){if(inner())inner().trust=clamp((inner().trust||0)+1,-8,8);add('ORISON coordinates shared with Concord under the existing contact arrangement. Speaker Rhee provides the oldest surviving continuity-authentication checksum and asks that the site not be damaged.')}else add('ORISON coordinates kept compartmented aboard the fleet. Concord is not told that the continuity site has been located.');saveCampaign(campaign);return{ok:true}}
export function queueOrisonApproach(){const o=ensure();if(!o.located)return{ok:false,reason:'ORISON has not been located.'};if(!o.disclosure)return{ok:false,reason:'Decide whether to disclose the ORISON location to Concord before departing.'};if(o.accessGranted)return{ok:false,reason:'ORISON access has already been secured.'};if(campaign.pendingEncounter)return{ok:false,reason:'Another encounter is pending.'};o.approaches=(o.approaches||0)+1;campaign.pendingEncounter={kind:'orisonApproach',title:'ORISON continuity-site approach',attempt:o.approaches,credentialQuality:credentialQuality(),shared:o.disclosure==='share'};campaign.day+=4;add('Fleet departs Concord space for the reconstructed ORISON orbit. The four-day transit is uneventful until three cold objects begin manoeuvring around the predicted site.');saveCampaign(campaign);return{ok:true,encounter:campaign.pendingEncounter}}

function scenario(b){return b?.nonCombatScenario==='orisonApproach'}
function players(b){return(b.ships||[]).filter(s=>s.team==='P'&&!s.dead&&!s.civilianEscort)}
function sentries(b){return(b.ships||[]).filter(s=>s.orisonSentry&&!s.dead)}
function init(b){if(b.orisonState)return b.orisonState;const enc=campaign.pendingEncounter||{};b.orisonState={startedAt:b.t,track:0,challenge:false,response:null,checksumSent:false,spoofSent:false,forceEntry:false,weaponsFree:false,finished:false,result:null,credentialQuality:enc.credentialQuality??credentialQuality(),shared:!!enc.shared};b.log('ORISON approach: three dormant objects warm simultaneously and begin matching the fleet’s vector. Weapons remain held.');return b.orisonState}
function steer(ship,x,y){const dx=x-ship.x,dy=y-ship.y,d=Math.hypot(dx,dy);ship.desiredAngle=Math.atan2(dy,dx);ship.throttle=d>700?.55:d>320?.18:-.12}
registerBattleHook('beforeApplySystems','orison-sentry-flight',({battle,ship})=>{if(!scenario(battle))return;const st=init(battle),ss=sentries(battle),ps=players(battle);if(ship.orisonSentry&&!st.weaponsFree){const i=Math.max(0,ss.indexOf(ship)),anchorX=650,anchorY=(i-(ss.length-1)/2)*760;steer(ship,anchorX,anchorY);ship.order=st.forceEntry?'Blocking continuity boundary':'Automated authentication screen';return}if(ship.team==='P'&&!st.weaponsFree){const lead=ss[0];if(st.forceEntry&&lead){steer(ship,lead.x+900,lead.y);ship.order='Press ORISON boundary'}else{ship.throttle=.2;ship.desiredAngle=.02;ship.order='Approach ORISON authentication screen'}}},198);
registerBattleHook('beforeFireWeapons','orison-roe',ctx=>{if(!scenario(ctx.battle))return;const st=init(ctx.battle);if(!st.weaponsFree){ctx.handled=true;ctx.result=undefined}},250);
registerBattleHook('afterStep','orison-authentication',({battle,dt})=>{if(!scenario(battle))return;const st=init(battle);if(st.finished)return;const ps=players(battle),ss=sentries(battle);if(!ps.length){st.finished=true;st.result='fleetLost';battle.winner='E';return}if(!ss.length&&st.weaponsFree){st.finished=true;st.result='sentriesDestroyed';battle.winner='P';return}if(!ss.length)return;const range=Math.min(...ps.flatMap(p=>ss.map(s=>Math.hypot(p.x-s.x,p.y-s.y))));if(range<5200)st.track=clamp(st.track+dt*.014,0,1);if(!st.challenge&&range<2800){st.challenge=true;st.response='CONTINUITY NODE ORISON. PRESENT ARCHIVE AUTHENTICATOR. MAINTAIN EXCLUSION VECTOR.';battle.log(st.response)}if(st.forceEntry&&range<900&&!st.weaponsFree){st.weaponsFree=true;for(const s of ss)s.missionNonHostile=false;battle.log('ORISON sentry lattice rejects boundary violation. Automated weapons release detected.')}if(!st.weaponsFree&&battle.t-st.startedAt>115){st.finished=true;st.result='timedOut';battle.winner='E';battle.log('ORISON sentries maintain the exclusion screen. The fleet withdraws before automatic escalation.')}else if(!st.weaponsFree)battle.winner=null},238);
registerBattleHook('afterStep','orison-outcome',({battle})=>{if(!scenario(battle)||!battle.winner||battle._orisonResolved)return;const enc=campaign.pendingEncounter;if(enc?.kind!=='orisonApproach')return;battle._orisonResolved=true;battle._campaignPersisted=true;persistBattleResults(battle);campaign.pendingEncounter=null;campaign.day+=1;const o=ensure(),st=init(battle);if(battle.winner==='P'){
 o.accessGranted=true;o.forcedEntry=st.result==='sentriesDestroyed';o.siteStatus='powered_silent';o.courierFound=true;o.continuityLock=true;o.complete=true;campaign.mainPlot.act='orison-core';
 if(st.result==='authenticated'){o.clues.push({day:campaign.day,text:'The archival checksum is accepted. ORISON’s sentries stand down and expose a docking corridor through the planetoid’s artificial thermal masking.'});add('ORISON authentication accepted. Inside the masked dock, the missing closure-era courier is still present — cold, damaged, and physically clamped to the station. Facility power remains active.')}
 else if(st.result==='spoofed'){o.clues.push({day:campaign.day,text:'The reconstructed handshake is accepted with degraded confidence. ORISON opens one service corridor but keeps most defence nodes armed and isolated.'});add('ORISON admits the fleet under an obsolete courier credential. The missing courier is docked inside; its reactor is cold, but the continuity facility itself is still powered.')}
 else{o.clues.push({day:campaign.day,text:'Destroyed sentry telemetry reveals the concealed docking geometry. The approach works, but several defence buses deeper in the planetoid remain active.'});add('ORISON outer sentries destroyed and the concealed dock forced. The missing courier is present inside. The facility is powered and has entered a hardened continuity-lock state.');if(o.disclosure==='share'&&inner())inner().trust=clamp((inner().trust||0)-3,-8,8)}
 o.clues.push({day:campaign.day,text:'Dock logs confirm the courier reached ORISON and uploaded the complete Lacuna closure archive. Minutes later, ORISON detected a second Burn-like field signature associated with an outbound route solution. The station then entered Continuity Lock and ceased all external transmissions.'});
 }else add('ORISON approach aborted. The automated sentry screen remains intact and the continuity site stays sealed.');saveCampaign(campaign)},-106);
export function transmitOrisonChecksum(){const b=window.__fleetBattle;if(!scenario(b))return{ok:false,reason:'No ORISON approach is active.'};const st=init(b);if(!st.challenge)return{ok:false,reason:'Wait for ORISON to issue its authentication challenge.'};if(st.weaponsFree)return{ok:false,reason:'Authentication is no longer available during active combat.'};if(st.checksumSent)return{ok:false,reason:'The archive checksum has already been transmitted.'};st.checksumSent=true;if(st.credentialQuality>=.75){st.finished=true;st.result='authenticated';b.winner='P';st.response='ARCHIVE AUTHENTICATOR ACCEPTED. CONTINUITY ACCESS CORRIDOR OPEN.';b.log(st.response);return{ok:true,accepted:true}}st.response='AUTHENTICATOR INCOMPLETE. LEGACY COURIER PROOF REQUIRED.';b.log(st.response);return{ok:true,accepted:false}}
export function transmitOrisonSpoof(){const b=window.__fleetBattle;if(!scenario(b))return{ok:false,reason:'No ORISON approach is active.'};const st=init(b);if(!st.challenge)return{ok:false,reason:'Wait for the authentication challenge.'};if(st.weaponsFree)return{ok:false,reason:'The sentry lattice is already in combat mode.'};if(st.spoofSent)return{ok:false,reason:'A legacy proof has already been attempted.'};if(st.track<.45)return{ok:false,reason:'Build at least a 45% sentry track before attempting to synthesise the obsolete courier handshake.'};st.spoofSent=true;const quality=st.credentialQuality+st.track*.45;if(quality>=.62){st.finished=true;st.result='spoofed';b.winner='P';st.response='LEGACY COURIER PROOF ACCEPTED WITH EXCEPTIONS. SERVICE CORRIDOR ONE OPEN.';b.log(st.response);return{ok:true,accepted:true}}st.response='LEGACY PROOF REJECTED. MAINTAIN EXCLUSION VECTOR.';b.log(st.response);return{ok:true,accepted:false}}
export function forceOrisonEntry(){const b=window.__fleetBattle;if(!scenario(b))return{ok:false,reason:'No ORISON approach is active.'};const st=init(b);if(st.weaponsFree)return{ok:false,reason:'ORISON defences are already active.'};st.forceEntry=true;b.log('Fleet orders: press through the continuity exclusion screen. Prepare for automated defence response.');return{ok:true}}
export function orisonBattleSummary(b){if(!scenario(b))return null;const st=init(b),ps=players(b),ss=sentries(b),range=ps.length&&ss.length?Math.min(...ps.flatMap(p=>ss.map(s=>Math.hypot(p.x-s.x,p.y-s.y)))):null;return{track:st.track,range,challenge:st.challenge,response:st.response,checksumSent:st.checksumSent,spoofSent:st.spoofSent,forceEntry:st.forceEntry,weaponsFree:st.weaponsFree,timeRemaining:Math.max(0,115-(b.t-st.startedAt)),result:st.result,credentialQuality:st.credentialQuality}}
if(typeof window!=='undefined')window.__lacunaOrison={orisonSummary,investigateOrisonLead,setOrisonDisclosure,queueOrisonApproach,transmitOrisonChecksum,transmitOrisonSpoof,forceOrisonEntry,orisonBattleSummary:()=>orisonBattleSummary(window.__fleetBattle)};
