import {campaign,saveCampaign,persistBattleResults,instantiateCampaignShip} from './campaign-core.js';
import {registerBattleHook} from './battle-hooks.js';
import {playerStanding,FACTIONS} from './factions-system.js?v=77';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);

export const LACUNA_LEGS=[
 {id:'debris',name:'The debris wake',brief:'The reconstructed route opens through a fast-moving debris wake. It is unlikely to stop a prepared fleet, but point defence, ammunition and damaged armour all matter later.'},
 {id:'shear',name:'The unstable throat',brief:'Mass solutions drift as the fleet penetrates the unmaintained route. Repeated field shear loads the hulls and propulsion systems; there is nowhere to dock.'},
 {id:'contact',name:'The route shadow',brief:'Anything that followed the reconstruction now has its last practical chance to contest the route. If nobody hostile followed, the fleet still has to cross a second unstable throat.'},
 {id:'terminal',name:'Terminal approach',brief:'The Lacuna endpoint is buried behind dense high-velocity debris and a collapsing exit solution. Turn back now or accept whatever condition the fleet reaches the far side in.'}
];

function ensure(){campaign.mainPlot??={};const p=campaign.mainPlot;p.gauntlet??={active:false,stage:0,completed:[],attempt:0,patchUsed:false,failed:false,arrived:false,pursuer:null};return p.gauntlet}
function hostileObserver(){const p=campaign.mainPlot||{},seen=p.attention||[];const candidates=seen.map(x=>({...x,standing:playerStanding(x.factionId)})).filter(x=>x.factionId&&x.standing<=-15).sort((a,b)=>a.standing-b.standing);return candidates[0]||null}
function encounterFor(stage){const g=ensure(),leg=LACUNA_LEGS[stage];if(!leg)return null;if(leg.id==='contact'){
 const hostile=hostileObserver();g.pursuer=hostile?{id:hostile.factionId,name:hostile.factionName||FACTIONS[hostile.factionId]?.name||hostile.factionId,standing:hostile.standing}:null;
 return{kind:'lacunaTransit',lacunaLeg:hostile?'pursuit':'shearHard',stage,title:hostile?`${g.pursuer.name} route interception`:'Deep-route shear',factionId:hostile?.factionId||null};
 }
 return{kind:'lacunaTransit',lacunaLeg:leg.id,stage,title:leg.name};
}
function queue(stage){campaign.pendingEncounter=encounterFor(stage);saveCampaign(campaign);return campaign.pendingEncounter}
export function transitSummary(){const g=ensure(),leg=LACUNA_LEGS[g.stage]||null;return{...g,current:leg,total:LACUNA_LEGS.length,pending:campaign.pendingEncounter?.kind==='lacunaTransit',canStart:!!campaign.mainPlot?.routeReady&&!g.active&&!g.arrived&&campaign.location==='Nadir',canPatch:g.active&&g.stage===2&&!g.patchUsed&&!campaign.pendingEncounter};}
export function beginLacunaTransit(){const g=ensure();if(!campaign.mainPlot?.routeReady)return{ok:false,reason:'The Lacuna route has not been calibrated.'};if(campaign.location!=='Nadir')return{ok:false,reason:'The reconstructed route must be entered from the N-17 volume in Nadir.'};if(g.active)return{ok:false,reason:'Transit is already underway.'};if(g.arrived)return{ok:false,reason:'The fleet has already reached Lacuna Reach.'};
 g.active=true;g.stage=0;g.completed=[];g.attempt=(g.attempt||0)+1;g.patchUsed=false;g.failed=false;g.pursuer=null;campaign.log??=[];campaign.log.push(`Day ${campaign.day}: LACUNA TRANSIT — attempt ${g.attempt} committed. Normal repair, trade and gate diversion are unavailable until the fleet aborts or reaches the far endpoint.`);return{ok:true,encounter:queue(0)};}
export function queueLacunaLeg(){const g=ensure();if(!g.active)return{ok:false,reason:'No Lacuna transit is active.'};if(campaign.pendingEncounter)return{ok:false,reason:'An encounter is already pending.'};if(g.stage>=LACUNA_LEGS.length)return{ok:false,reason:'No transit legs remain.'};return{ok:true,encounter:queue(g.stage)};}
export function emergencyPatch(){const g=ensure();if(!g.active||g.stage!==2||campaign.pendingEncounter)return{ok:false,reason:'The emergency patch window is only available after clearing the unstable throat.'};if(g.patchUsed)return{ok:false,reason:'The fleet has already used its carried repair stock.'};if(campaign.supplies<18)return{ok:false,reason:'Emergency patching requires 18 supplies.'};
 let restored=0,modules=0;for(const entry of campaign.ships){if(entry.status!=='active'||!entry.state)continue;const fresh=instantiateCampaignShip(entry,'P'),maxById=new Map((fresh.modules||[]).map(m=>[m.id,m.maxHp||m.hp||1]));for(const sm of entry.state.modules||[]){const max=maxById.get(sm.id);if(!max||sm.hp<=0||sm.hp>=max)continue;const add=Math.min(max-sm.hp,max*.15);sm.hp+=add;restored+=add;modules++;}entry.history??=[];entry.history.push(`Day ${campaign.day}: emergency deep-route patching restored limited structural integrity; no ammunition, craft or destroyed modules replaced.`)}
 campaign.supplies-=18;campaign.day+=1;g.patchUsed=true;campaign.log??=[];campaign.log.push(`Day ${campaign.day}: LACUNA TRANSIT — emergency patch window used. ${modules} damaged modules received field repairs; ${Math.round(restored)} integrity restored. Ammunition and lost craft were not replenished.`);saveCampaign(campaign);return{ok:true,modules,restored};}

function scenario(b){return b?.nonCombatScenario==='lacunaTransit'}
function living(b){return(b.ships||[]).filter(s=>s.team==='P'&&!s.dead&&!s.civilianEscort)}
function leg(b){return b.lacunaLeg||campaign.pendingEncounter?.lacunaLeg}
function hazardCfg(kind){if(kind==='debris')return{duration:42,spawnUntil:35,interval:[.8,1.45],radius:[.8,3.1],speed:[520,900],damage:[28,58],label:'Debris wake'};if(kind==='terminal')return{duration:66,spawnUntil:58,interval:[.48,.95],radius:[1.1,4.2],speed:[650,1080],damage:[42,82],label:'Terminal debris'};return null}
function initHazard(b){if(b.lacunaHazard)return b.lacunaHazard;const cfg=hazardCfg(leg(b));if(!cfg)return null;b.lacunaHazard={...cfg,startedAt:b.t,spawnClock:0,spawned:0,impacts:0,destroyed:0,finished:false};b.ordnance??=[];b.log(`${cfg.label}: high-velocity tracks ahead. This leg is attritional; every round of point-defence ammunition spent now is unavailable later.`);return b.lacunaHazard}
function meteor(b,h){const ships=living(b),c=ships.length?{x:ships.reduce((n,s)=>n+s.x,0)/ships.length,y:ships.reduce((n,s)=>n+s.y,0)/ships.length}:{x:0,y:0},r=b.rng.range(h.radius[0],h.radius[1]),speed=b.rng.range(h.speed[0],h.speed[1]),hp=Math.round(12+r*r*5);return{kind:'meteor',neutralHazard:true,team:'H',x:c.x+b.rng.range(3800,5600),y:c.y+b.rng.range(-1300,1300),vx:-speed,vy:b.rng.range(-100,100),r,hp,maxHp:hp,mass:800*r*r*r,damage:Math.round(b.rng.range(h.damage[0],h.damage[1])+r*r*9),penetration:.65+r*.1,ttl:16,detectedBy:{P:true},detectionQuality:1,lacunaMeteor:true};}
function segmentCircle(ax,ay,bx,by,cx,cy,r){const dx=bx-ax,dy=by-ay,fx=ax-cx,fy=ay-cy,a=dx*dx+dy*dy;if(a<1e-9)return Math.hypot(fx,fy)<=r?0:null;const bb=2*(fx*dx+fy*dy),cc=fx*fx+fy*fy-r*r,d=bb*bb-4*a*cc;if(d<0)return null;const q=Math.sqrt(d),ts=[(-bb-q)/(2*a),(-bb+q)/(2*a)].filter(t=>t>=0&&t<=1);return ts.length?Math.min(...ts):null}
function impact(b,h,m,s,x,y){const rvx=m.vx-(s.vx||0),rvy=m.vy-(s.vy||0),attacker={name:'Route debris',team:'H',x:m.x,y:m.y,damageDone:0};b.hitRay(attacker,s,m.damage,'meteor',{x,y,dx:rvx,dy:rvy,penetration:m.penetration||1});const impulse=Math.min(16000000,m.mass*Math.hypot(rvx,rvy)),mag=Math.max(1,Math.hypot(rvx,rvy));s.vx+=(rvx/mag)*impulse/Math.max(1,s.mass);s.vy+=(rvy/mag)*impulse/Math.max(1,s.mass);m.hp=0;h.impacts++;b.log(`${s.name}: high-velocity debris impact.`)}
function hazardStep(b,dt){const h=initHazard(b);if(!h||h.finished)return;const elapsed=b.t-h.startedAt;if(elapsed<h.spawnUntil){h.spawnClock-=dt;while(h.spawnClock<=0){b.ordnance.push(meteor(b,h));h.spawned++;h.spawnClock+=b.rng.range(h.interval[0],h.interval[1]);}}
 for(const m of b.ordnance.filter(o=>o.lacunaMeteor&&o.hp>0)){const ax=m.x,ay=m.y,bx=ax+m.vx*dt,by=ay+m.vy*dt;let hit=null;for(const s of living(b)){const t=segmentCircle(ax,ay,bx,by,s.x,s.y,(s.radius||15)+(m.r||1));if(t!=null&&(!hit||t<hit.t))hit={s,t}}if(hit)impact(b,h,m,hit.s,ax+(bx-ax)*hit.t,ay+(by-ay)*hit.t);else{m.x=bx;m.y=by}m.ttl-=dt;}
 b.ordnance=b.ordnance.filter(o=>!o.lacunaMeteor||o.hp>0&&o.ttl>0);h.destroyed=Math.max(0,h.spawned-h.impacts-b.ordnance.filter(o=>o.lacunaMeteor&&o.hp>0).length);
 if(!living(b).length){h.finished=true;b.winner='E';b.log(`${h.label}: no fleet ship remains combat-effective.`);return}if(elapsed<h.duration){if(b.winner)b.winner=null;return}h.finished=true;b.winner='P';b.log(`${h.label} cleared. ${h.impacts} impact${h.impacts===1?'':'s'} recorded; ${h.destroyed} tracked object${h.destroyed===1?'':'s'} destroyed or deflected.`)}
function shearCfg(kind){return kind==='shearHard'?{duration:62,pulse:[3.8,6.2],damage:[.035,.075],label:'Deep-route shear'}:{duration:50,pulse:[5,8],damage:[.025,.055],label:'Unstable throat'}}
function initShear(b){if(b.lacunaShear)return b.lacunaShear;const kind=leg(b);if(kind!=='shear'&&kind!=='shearHard')return null;const c=shearCfg(kind);b.lacunaShear={...c,startedAt:b.t,nextPulse:b.t+3,pulses:0,finished:false};b.log(`${c.label}: the calculated mass solution is drifting. Engines and hull structure will take repeated transient loads.`);return b.lacunaShear}
function shearStep(b){const h=initShear(b);if(!h||h.finished)return;const elapsed=b.t-h.startedAt;if(!living(b).length){h.finished=true;b.winner='E';return}if(b.t>=h.nextPulse){h.pulses++;for(const s of living(b)){const candidates=(s.modules||[]).filter(m=>m.hp>0&&m.id!=='keel');if(!candidates.length)continue;const m=candidates[Math.floor(b.rng.next()*candidates.length)],max=m.maxHp||m.hp,frac=b.rng.range(h.damage[0],h.damage[1]);m.hp=Math.max(1,m.hp-max*frac);s.vx+=b.rng.range(-28,28);s.vy+=b.rng.range(-34,34);}h.nextPulse=b.t+b.rng.range(h.pulse[0],h.pulse[1]);b.log(`${h.label}: field transient ${h.pulses}; damage-control reports scattered overloads.`)}if(elapsed<h.duration){if(b.winner)b.winner=null;return}h.finished=true;b.winner='P';b.log(`${h.label} cleared after ${h.pulses} major field transients.`)}

registerBattleHook('afterProjectiles','lacuna-route-hazards',({battle,dt})=>{if(!scenario(battle))return;const k=leg(battle);if(k==='debris'||k==='terminal')hazardStep(battle,dt)},145);
registerBattleHook('afterStep','lacuna-route-shear',({battle})=>{if(!scenario(battle))return;const k=leg(battle);if(k==='shear'||k==='shearHard')shearStep(battle)},205);
registerBattleHook('afterStep','lacuna-campaign-leg-outcome',({battle})=>{if(!battle?.campaignBattle||!battle.winner||battle._lacunaResolved)return;const enc=campaign.pendingEncounter;if(enc?.kind!=='lacunaTransit')return;battle._lacunaResolved=true;persistBattleResults(battle);const g=ensure(),won=battle.winner==='P';campaign.pendingEncounter=null;campaign.day+=1;if(won){g.completed.push(LACUNA_LEGS[g.stage]?.id||`leg${g.stage}`);g.stage++;if(g.stage>=LACUNA_LEGS.length){g.active=false;g.arrived=true;g.failed=false;campaign.location='Lacuna Reach';campaign.mainPlot.act='lacuna';campaign.log??=[];campaign.log.push(`Day ${campaign.day}: LACUNA TRANSIT — surviving fleet elements emerge into Lacuna Reach. No repair dock, resupply base or registered gate authority is available.`);}else{campaign.log??=[];campaign.log.push(`Day ${campaign.day}: LACUNA TRANSIT — leg ${g.stage}/${LACUNA_LEGS.length} cleared. Damage, ammunition expenditure and lost craft carry forward.`);}}else{g.active=false;g.failed=true;g.stage=0;g.completed=[];campaign.location='Nadir';campaign.log??=[];campaign.log.push(`Day ${campaign.day}: LACUNA TRANSIT — attempt aborted. Surviving ships fall back to Nadir; all damage and expenditure remain. The route can be attempted again after recovery.`);}saveCampaign(campaign);},-120);

export function lacunaBattleSummary(b){if(!scenario(b))return null;const h=b.lacunaHazard,s=b.lacunaShear;return h?{kind:'debris',label:h.label,timeRemaining:Math.max(0,h.duration-(b.t-h.startedAt)),spawned:h.spawned,impacts:h.impacts,destroyed:h.destroyed}:s?{kind:'shear',label:s.label,timeRemaining:Math.max(0,s.duration-(b.t-s.startedAt)),pulses:s.pulses}:null}
if(typeof window!=='undefined')window.__lacunaTransit={transitSummary,beginLacunaTransit,queueLacunaLeg,emergencyPatch,lacunaBattleSummary:()=>lacunaBattleSummary(window.__fleetBattle)};
