import {campaign,saveCampaign} from './campaign-core.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function fresh(){return{opened:false,openDay:null,speaker:'Speaker Anika Rhee',topics:{identity:false,closure:false,terms:false},history:[],arrangement:null,archiveAccess:null,reparationsPaid:false,ceasefireAttempted:false,hostile:false,complete:false}}
function ensure(){campaign.mainPlot??={};campaign.mainPlot.concord??=fresh();const c=campaign.mainPlot.concord;c.topics??={identity:false,closure:false,terms:false};c.history??=[];return c}
function inner(){return campaign.mainPlot?.lacunaInner}
function unlocked(){return campaign.location==='Lacuna Reach'&&!!inner()?.encountered}
function trust(){return inner()?.trust??0}
function setTrust(v){if(!inner())return;inner().trust=clamp(v,-8,8)}
function add(text){const c=ensure();c.history.push({day:campaign.day,text});campaign.log??=[];campaign.log.push(`Day ${campaign.day}: Concord — ${text}`)}
function routeContext(){const truth=campaign.mainPlot?.truth||campaign.investigation?.truth||campaign.mysteryTruth||null;if(truth==='gateEcho')return'Concord records describe repeated ships arriving with impossible clock offsets before the route was shut.';if(truth==='blackProject')return'One closure-era record mentions unmarked survey craft using Central-format telemetry, but Concord does not claim they caused the crisis.';if(truth==='lostColony')return'Concord archivists recognise the pattern of isolation but insist their population formed from several unrelated arrivals, not one founding colony.';return'Concord says its history contains several unrelated arrivals and warns against forcing every old anomaly into a single explanation.'}
export function concordSummary(){const c=ensure(),t=trust();return{...c,available:unlocked(),trust:t,stance:t>=3?'guarded cooperation':t>=1?'cautious contact':t>=-1?'armed neutrality':t>=-4?'hostile suspicion':'open hostility',canOpen:unlocked()&&!c.opened,canTalk:c.opened&&!c.complete&&!c.hostile,canRepairRelations:c.opened&&t<1&&!c.reparationsPaid,canCeasefire:c.opened&&t<0&&!c.ceasefireAttempted,routeContext:routeContext()}}
export function openConcordChannel(){const c=ensure();if(!unlocked())return{ok:false,reason:'Reach the inner-system contact phase first.'};if(c.opened)return{ok:false,reason:'The Concord channel is already open.'};c.opened=true;c.openDay=campaign.day;campaign.day+=1;const t=trust();if(t<=-4){c.hostile=true;add('Outer Watch accepts only a narrow ceasefire channel. Concord Habitat refuses direct audience after the exclusion-line fighting.')}else if(t<1)add('Outer Watch opens a remote, delayed parley. No docking clearance is offered.');else{inner().settlementRevealed=true;inner().settlementName='Concord Habitat';add(`${c.speaker} opens a controlled direct channel from Concord Habitat.`)}saveCampaign(campaign);return{ok:true}}
export function payReparations(){const c=ensure();if(!c.opened)return{ok:false,reason:'Open the Concord channel first.'};if(c.reparationsPaid)return{ok:false,reason:'Reparations have already been offered.'};if(campaign.supplies<20)return{ok:false,reason:'The reparations package requires 20 supplies.'};campaign.supplies-=20;campaign.day+=1;c.reparationsPaid=true;setTrust(trust()+3);c.hostile=trust()<=-4;add('Transferred emergency stores and replacement material as reparations for the exclusion-line incident. Concord accepts the material without recognising any legal settlement.');saveCampaign(campaign);return{ok:true}}
export function requestCeasefire(){const c=ensure();if(!c.opened)return{ok:false,reason:'Open the Concord channel first.'};if(c.ceasefireAttempted)return{ok:false,reason:'A ceasefire request has already been made.'};campaign.day+=2;c.ceasefireAttempted=true;setTrust(trust()+1);c.hostile=trust()<=-4;add('Fleet holds outside the inner corridor for two days while requesting a standing ceasefire. Outer Watch acknowledges the restraint.');saveCampaign(campaign);return{ok:true}}
export function threatenConcord(){const c=ensure();if(!c.opened)return{ok:false,reason:'Open the Concord channel first.'};setTrust(trust()-3);c.hostile=true;c.complete=true;c.arrangement='coercive_standoff';c.archiveAccess='denied';campaign.mainPlot.act='lacuna-vault-hostile';add('Fleet transmits an ultimatum demanding inner-system access. Concord rejects it and places the habitat under general defence alert.');saveCampaign(campaign);return{ok:true}}
export function discussConcordTopic(id){const c=ensure();if(!c.opened)return{ok:false,reason:'Open the Concord channel first.'};if(c.hostile)return{ok:false,reason:'Concord is not conducting substantive talks under the current hostile posture.'};if(c.topics[id])return{ok:false,reason:'That topic has already been discussed.'};if(!['identity','closure','terms'].includes(id))return{ok:false,reason:'Unknown discussion topic.'};campaign.day+=1;c.topics[id]=true;
 if(id==='identity'){inner().settlementRevealed=true;inner().settlementName='Concord Habitat';add(`${c.speaker}: “Concord is not a lost colony. It is a refuge built in layers — survey crews, failed expeditions, defectors and families who arrived through different broken routes over decades. We owe no modern government a founding charter.”`);setTrust(trust()+1)}
 if(id==='closure'){add(`${c.speaker}: “The route was closed deliberately after the Burn. Reopening attempts destabilised the endpoint, killed people here and drew competing outside claims. Our predecessors destroyed navigation records rather than let another fleet turn Lacuna into a prize.” ${routeContext()}`);if(trust()>=2)setTrust(trust()+1)}
 if(id==='terms'){add(`${c.speaker}: “We want the dead route to stay difficult to find. No sovereignty claim, no open beacon, no commercial traffic until we choose otherwise. In return, we can keep your people alive and show you records no one outside Lacuna has seen.”`)}
 saveCampaign(campaign);return{ok:true}}
export function concludeConcordTerms(choice){const c=ensure();if(!c.opened||c.hostile)return{ok:false,reason:'There is no cooperative negotiation to conclude.'};if(!c.topics.terms)return{ok:false,reason:'Discuss Concord’s terms first.'};if(c.complete)return{ok:false,reason:'The Concord arrangement is already settled.'};campaign.day+=1;
 if(choice==='recognise'){setTrust(trust()+3);c.arrangement='sanctuary_accord';c.archiveAccess='invited';c.complete=true;campaign.supplies+=10;add('Sanctuary Accord reached: the fleet recognises Concord’s de facto autonomy and agrees not to broadcast the route. Concord grants escorted habitat access, emergency stores (+10 supplies) and supervised access to the Founding Vault.');campaign.mainPlot.act='lacuna-vault'}
 else if(choice==='limited'){setTrust(trust()+1);c.arrangement='limited_contact';c.archiveAccess='restricted';c.complete=true;add('Limited Contact Protocol reached: neither side concedes sovereignty. The fleet may use the outer anchorage and request humanitarian support, but Founding Vault access remains restricted to selected extracts.');campaign.mainPlot.act='lacuna-vault'}
 else if(choice==='openRoute'){setTrust(trust()-3);c.arrangement='route_dispute';c.archiveAccess='denied';c.complete=true;c.hostile=trust()<=-2;add('Fleet rejects permanent route secrecy and insists on freedom to report the discovery. Concord ends substantive talks and locks down the inner habitat archives.');campaign.mainPlot.act='lacuna-vault-hostile'}
 else return{ok:false,reason:'Unknown settlement choice.'};saveCampaign(campaign);return{ok:true}}
if(typeof window!=='undefined')window.__lacunaConcord={concordSummary,openConcordChannel,payReparations,requestCeasefire,threatenConcord,discussConcordTopic,concludeConcordTerms};
