import {campaign} from './campaign-core.js';
import {plotSummary,resolveNadir,investigateThread,synthesizeArchive,chooseArchiveCustody,calibrateRoute} from './main-plot.js?v=80';
import {transitSummary,beginLacunaTransit,queueLacunaLeg,emergencyPatch,LACUNA_LEGS} from './lacuna-transit.js?v=81';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let signature='';
function host(){const inv=document.querySelector('#investigationPanel');if(!inv)return null;let h=document.querySelector('#mainPlotPanel');if(!h){h=document.createElement('section');h.id='mainPlotPanel';h.className='investigationPanel mainPlotPanel';inv.after(h)}return h}
function resolutionHtml(p){if(p.nadirResolution)return `<article class="mysteryDirective"><b>NADIR DISPOSITION</b><p>${esc(p.nadirResolution.label)}</p><small>Decision recorded day ${p.nadirResolution.day}. The case has moved beyond N-17 into older unresolved navigation records.</small></article>`;if(!p.canResolve)return'';return `<div class="mysteryBlock"><b>STRATEGIC DISPOSITION // NADIR</b><p>The immediate N-17 contact is understood well enough to force a political and operational choice. This choice will affect who trusts you and how the wider frontier learns about the incident.</p><div class="plotChoices">${p.resolutionOptions.map(o=>`<article class="lead available"><span>${esc(o.label)}</span><p>${esc(o.text)}</p><button data-resolution="${esc(o.id)}">Choose this disposition</button></article>`).join('')}</div></div>`}
function threadCard(t){const findings=(t.findings||[]).map(f=>`<li>Day ${f.day}: ${esc(f.text)}</li>`).join('');return `<article class="lead ${t.available?'available':''}"><span>${esc(t.name)} // ${esc(t.system)}</span><p>${esc(t.summary)}</p><small>${t.resolved?'RESOLVED':`INVESTIGATION ${t.progress||0}%`}</small>${findings?`<ul>${findings}</ul>`:''}${!t.resolved?(t.available?`<button data-thread="${esc(t.id)}">Continue investigation · ${5+(t.stage||0)*3} supplies</button>`:`<small>Travel to ${esc(t.system)} to continue.</small>`):''}</article>`}
function synthesisHtml(p){
 if(!p.threadsComplete)return'';
 if(!p.synthesis)return `<div class="mysteryBlock"><b>ARCHIVE SYNTHESIS</b><p>All three references are resolved. Isolated comparison can now separate genuine shared route-key lineage from coincidences and copied software.</p><button data-synthesise>Run archive synthesis · 12 supplies · 2 days</button></div>`;
 const connected=p.synthesis.connected.map(id=>p.threads.find(t=>t.id===id)?.name||id);
 return `<article class="mysteryDirective"><b>ARCHIVE SYNTHESIS // ${esc(p.synthesis.confidence.toUpperCase())} CONFIDENCE</b><p>${esc(p.synthesis.summary)}</p><small>Genuine connected record${connected.length===1?'':'s'}: ${esc(connected.join(' · '))}</small></article>`;
}
function custodyHtml(p){if(!p.synthesis||p.custody)return p.custody?`<article class="mysteryDirective"><b>ROUTE CUSTODY</b><p>${esc(p.custody.label)}</p><small>Arrangement recorded day ${p.custody.day}. Route calibration is now an operational project.</small></article>`:'';return `<div class="mysteryBlock"><b>WHO GETS THE ROUTE?</b><p>The synthesis contains enough structure to reconstruct a route, but whoever supplies the final navigation work will gain leverage over the result.</p><div class="plotChoices">${p.custodyOptions.map(o=>`<article class="lead ${o.available?'available':''}"><span>${esc(o.label)}</span><p>${esc(o.text)}</p><small>Calibration logistics: ${o.cost} supplies per site</small>${o.available?`<button data-custody="${esc(o.id)}">Choose custody</button>`:'<small>Relationship insufficient.</small>'}</article>`).join('')}</div></div>`}
function routeTaskCard(t){return `<article class="lead ${t.available?'available':''}"><span>${esc(t.name)} // ${esc(t.system)}</span><p>${esc(t.text)}</p><small>${t.done?`COMPLETE · DAY ${t.day}`:'PENDING'}</small>${t.finding?`<p>${esc(t.finding)}</p>`:''}${!t.done?(t.available?`<button data-route-task="${esc(t.id)}">Calibrate route · ${t.cost} supplies</button>`:`<small>Travel to ${esc(t.system)} to continue.</small>`):''}</article>`}
function routeHtml(p){if(!p.custody)return'';if(p.routeReady)return `<article class="mysteryDirective"><b>UNREGISTERED ROUTE CONFIRMED // ${esc(p.destination||'UNKNOWN ENDPOINT')}</b><p>The three independent calibrations converge. This is not a charting error: the recovered route solution points to a dormant endpoint absent from the modern gate network.</p><small>Several factions know enough to realise your fleet has found something strategically significant.</small></article>${p.attention?.length?`<div class="mysteryBlock"><b>WHO NOTICED</b>${p.attention.map(a=>`<article class="lead"><span>${esc(a.factionName)} // ${esc(a.system)}</span><small>Interest recorded day ${a.day}</small></article>`).join('')}</div>`:''}`;return `<div class="mysteryBlock"><b>ROUTE RECONSTRUCTION</b><p>A route seed is not safe transit data. Reconstruct it against three independent frames before risking a ship.</p>${p.routeTasks.map(routeTaskCard).join('')}</div>`}
function transitHtml(g){if(!campaign.mainPlot?.routeReady)return'';if(g.arrived)return `<article class="mysteryDirective"><b>LACUNA REACH // ARRIVED</b><p>The surviving fleet has crossed the dormant route. Whatever Lacuna Reach contains, there is no registered port, repair yard or authority waiting to restore the ships that made it through.</p><small>ACT IV CONTINUES IN LACUNA REACH.</small></article>`;
 if(!g.active){const where=campaign.location==='Nadir'?'The fleet is at the N-17 entry volume.':'Return to Nadir to enter the reconstructed route.';return `<div class="mysteryBlock"><b>ATTEMPT THE LACUNA TRANSIT</b><p>This is not ordinary gate travel. Four sequential legs must be crossed with persistent hull damage, ammunition expenditure and craft losses. There is no normal repair or resupply between legs. A single emergency field-patch window opens halfway through, and it cannot replace destroyed modules, ammunition or lost craft.</p><small>${esc(where)}${g.failed?' The previous attempt failed; surviving damage remains until repaired in normal space.':''}</small>${campaign.location==='Nadir'?'<button data-lacuna-start>Commit fleet to Lacuna transit</button>':''}</div>`;}
 const cards=LACUNA_LEGS.map((l,i)=>`<article class="lead ${i===g.stage?'available':''}"><span>${i+1}. ${esc(l.name)}</span><p>${esc(l.brief)}</p><small>${g.completed.includes(l.id)?'CLEARED':i===g.stage?'CURRENT LEG':'AHEAD'}</small></article>`).join('');
 const current=g.current;return `<div class="mysteryBlock"><b>LACUNA TRANSIT // LEG ${Math.min(g.stage+1,g.total)} OF ${g.total}</b><p>Fleet condition carries forward. Normal gate diversion, trading and repair are locked until the fleet reaches Lacuna Reach or aborts back to Nadir.</p>${cards}${g.pursuer?`<article class="mysteryDirective"><b>ROUTE SHADOW IDENTIFIED</b><p>${esc(g.pursuer.name)} has followed the route work far enough to contest the transit. Their standing with the fleet is ${g.pursuer.standing}.</p></article>`:''}${g.canPatch?'<button data-lacuna-patch>Use emergency field patch · 18 supplies</button>':''}${!g.pending&&current?`<button data-lacuna-next>${g.stage===0?'Begin first leg':`Continue into ${esc(current.name)}`}</button>`:'<small>Transit encounter is committed. Return to the battle display.</small>'}</div>`}
function actTitle(p,g){if(g.arrived)return'Lacuna Reach';if(g.active)return'Lacuna transit';if(p.routeReady)return'The Lacuna route';if(p.custody)return'Reconstructing the route';if(p.synthesis)return'Archive synthesis';if(p.archiveRecovered)return'Echoes in the archive';return'Nadir resolution'}
function actBadge(p,g){if(g.arrived)return'ACT IV';if(g.active)return`ACT IV · ${g.stage+1}/${g.total}`;if(p.routeReady)return'ACT IV READY';if(p.custody||p.synthesis)return'ACT III';if(p.archiveRecovered)return'ACT II';return'ACT I'}
function launchTransitBattle(){if(!(campaign.activeShipIds||[]).length){alert('Assign at least one active ship before committing to the route.');return}window.__campaignActive=true;document.querySelector('#reset')?.click();const b=window.__fleetBattle;if(b)b.campaignBattle=true;window.__campaignActive=false;document.querySelector('[data-tab="battle"]')?.click()}
function render(){const h=host();if(!h)return;const p=plotSummary(),g=transitSummary(),sig=JSON.stringify([campaign.location,campaign.day,campaign.supplies,p,g,campaign.pendingEncounter]);if(sig===signature)return;signature=sig;const unlocked=p.archiveRecovered;
 h.innerHTML=`<div class="mysteryHead"><div><small>MAIN PLOT</small><h3>${esc(actTitle(p,g))}</h3></div><strong>${esc(actBadge(p,g))}</strong></div>${resolutionHtml(p)}${unlocked?`<p class="mysterySummary">The N-17 archive contains older references. Some may share a real cause; others may only look related because human records, copied software and secrecy overlap.</p><div class="mysteryBlock"><b>FOLLOW-ON THREADS</b>${p.threads.map(threadCard).join('')}</div>${synthesisHtml(p)}${custodyHtml(p)}${routeHtml(p)}${transitHtml(g)}`:''}`;
 h.querySelectorAll('[data-resolution]').forEach(b=>b.onclick=()=>{if(!confirm('Commit to this Nadir disposition? The political consequences will persist.'))return;const r=resolveNadir(b.dataset.resolution);if(!r.ok)alert(r.reason||'Unable to resolve Nadir.');signature='';render()});
 h.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>{const r=investigateThread(b.dataset.thread);if(!r.ok)alert(r.reason||'Unable to investigate this thread.');signature='';render()});
 h.querySelectorAll('[data-synthesise]').forEach(b=>b.onclick=()=>{const r=synthesizeArchive();if(!r.ok)alert(r.reason||'Archive synthesis failed.');signature='';render()});
 h.querySelectorAll('[data-custody]').forEach(b=>b.onclick=()=>{if(!confirm('Commit the route reconstruction to this custody arrangement?'))return;const r=chooseArchiveCustody(b.dataset.custody);if(!r.ok)alert(r.reason||'Unable to establish custody.');signature='';render()});
 h.querySelectorAll('[data-route-task]').forEach(b=>b.onclick=()=>{const r=calibrateRoute(b.dataset.routeTask);if(!r.ok)alert(r.reason||'Route calibration failed.');signature='';render()});
 h.querySelectorAll('[data-lacuna-start]').forEach(b=>b.onclick=()=>{if(!confirm('Commit this fleet to a four-leg transit with no normal repair or resupply between encounters?'))return;const r=beginLacunaTransit();if(!r.ok){alert(r.reason||'Unable to begin transit.');return}signature='';render();launchTransitBattle()});
 h.querySelectorAll('[data-lacuna-next]').forEach(b=>b.onclick=()=>{const r=queueLacunaLeg();if(!r.ok){alert(r.reason||'Unable to continue transit.');return}signature='';render();launchTransitBattle()});
 h.querySelectorAll('[data-lacuna-patch]').forEach(b=>b.onclick=()=>{const r=emergencyPatch();if(!r.ok)alert(r.reason||'Emergency patching failed.');signature='';render()});
}
render();setInterval(render,500);
