import {campaign} from './campaign-core.js';
import {plotSummary,resolveNadir,investigateThread,plotComplete} from './main-plot.js?v=79';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let signature='';
function host(){const inv=document.querySelector('#investigationPanel');if(!inv)return null;let h=document.querySelector('#mainPlotPanel');if(!h){h=document.createElement('section');h.id='mainPlotPanel';h.className='investigationPanel mainPlotPanel';inv.after(h)}return h}
function resolutionHtml(p){if(p.nadirResolution)return `<article class="mysteryDirective"><b>NADIR DISPOSITION</b><p>${esc(p.nadirResolution.label)}</p><small>Decision recorded day ${p.nadirResolution.day}. The case has moved beyond N-17 into older unresolved navigation records.</small></article>`;if(!p.canResolve)return'';return `<div class="mysteryBlock"><b>STRATEGIC DISPOSITION // NADIR</b><p>The immediate N-17 contact is understood well enough to force a political and operational choice. This choice will affect who trusts you and how the wider frontier learns about the incident.</p><div class="plotChoices">${p.resolutionOptions.map(o=>`<article class="lead available"><span>${esc(o.label)}</span><p>${esc(o.text)}</p><button data-resolution="${esc(o.id)}">Choose this disposition</button></article>`).join('')}</div></div>`}
function threadCard(t){const findings=(t.findings||[]).map(f=>`<li>Day ${f.day}: ${esc(f.text)}</li>`).join('');return `<article class="lead ${t.available?'available':''}"><span>${esc(t.name)} // ${esc(t.system)}</span><p>${esc(t.summary)}</p><small>${t.resolved?'RESOLVED':`INVESTIGATION ${t.progress||0}%`}</small>${findings?`<ul>${findings}</ul>`:''}${!t.resolved?(t.available?`<button data-thread="${esc(t.id)}">Continue investigation · ${5+(t.stage||0)*3} supplies</button>`:`<small>Travel to ${esc(t.system)} to continue.</small>`):''}</article>`}
function render(){const h=host();if(!h)return;const p=plotSummary(),sig=JSON.stringify([campaign.location,campaign.day,campaign.supplies,p]);if(sig===signature)return;signature=sig;const unlocked=p.archiveRecovered;
 h.innerHTML=`<div class="mysteryHead"><div><small>MAIN PLOT</small><h3>${unlocked?'Echoes in the archive':'Nadir resolution'}</h3></div><strong>${unlocked?(plotComplete()?'THREADS RESOLVED':'ACT II'):'ACT I'}</strong></div>${resolutionHtml(p)}${unlocked?`<p class="mysterySummary">The N-17 archive contains three older references. They may be parts of one story, human secrets mistaken for the same phenomenon, or coincidences. The fleet has to establish which.</p><div class="mysteryBlock"><b>FOLLOW-ON THREADS</b>${p.threads.map(threadCard).join('')}</div>${plotComplete()?'<article class="mysteryDirective"><b>ARCHIVE SYNTHESIS READY</b><p>All three references have been investigated. The surviving connections now define the next campaign act.</p></article>':''}`:''}`;
 h.querySelectorAll('[data-resolution]').forEach(b=>b.onclick=()=>{if(!confirm('Commit to this Nadir disposition? The political consequences will persist.'))return;const r=resolveNadir(b.dataset.resolution);if(!r.ok)alert(r.reason||'Unable to resolve Nadir.');signature='';render()});
 h.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>{const r=investigateThread(b.dataset.thread);if(!r.ok)alert(r.reason||'Unable to investigate this thread.');signature='';render()});
}
render();setInterval(render,500);
