import {Battle,buildBroadsideFrigate,buildPursuitFrigate,G,runBattle} from './sim.js';
const canvas=document.querySelector('#space'),ctx=canvas.getContext('2d');
const logEl=document.querySelector('#log'),statsEl=document.querySelector('#stats'),speedEl=document.querySelector('#speed'),pauseBtn=document.querySelector('#pause'),resetBtn=document.querySelector('#reset'),batchBtn=document.querySelector('#batch');
let battle,paused=false,scale=0.14,simSpeed=1,last=performance.now();
function reset(seed=Math.floor(Math.random()*1e9)){battle=new Battle(buildBroadsideFrigate('A'),buildPursuitFrigate('B'),seed);logEl.innerHTML='';}
reset(7);
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)} addEventListener('resize',resize);resize();
function drawShip(s){ctx.save();ctx.translate(canvas.clientWidth/2+s.x*scale,canvas.clientHeight/2+s.y*scale);ctx.rotate(s.angle);ctx.globalAlpha=s.dead?.35:1;ctx.strokeStyle=s.team==='A'?'#d7b96d':'#79b8ff';ctx.lineWidth=2;ctx.strokeRect(-s.length*scale/2,-s.width*scale/2,s.length*scale,s.width*scale);
 for(const m of s.modules){const x=m.x*scale,y=m.y*scale,w=7,h=5;ctx.globalAlpha=m.hp>0?1:.2;if(m.type==='engine'){ctx.strokeStyle='#56b6ff';ctx.strokeRect(x-w/2,y-h/2,w,h);const a=m.dir||0;ctx.beginPath();ctx.moveTo(x+Math.cos(a)*5,y+Math.sin(a)*5);ctx.lineTo(x+Math.cos(a+2.5)*3,y+Math.sin(a+2.5)*3);ctx.moveTo(x+Math.cos(a)*5,y+Math.sin(a)*5);ctx.lineTo(x+Math.cos(a-2.5)*3,y+Math.sin(a-2.5)*3);ctx.stroke();if(m.active){ctx.beginPath();ctx.moveTo(x-Math.cos(a)*4,y-Math.sin(a)*4);ctx.lineTo(x-Math.cos(a)*12*(m.output||1),y-Math.sin(a)*12*(m.output||1));ctx.stroke();}}
 else {ctx.fillStyle=m.type==='gun'?'#ddd':m.type==='armor'?'#777':m.type==='reactor'?'#f4cf63':m.type==='shield'?'#79e0ff':m.type==='laser'?'#ff7c7c':'#aaa';ctx.fillRect(x-w/2,y-h/2,w,h)}}
 ctx.restore();ctx.globalAlpha=1;ctx.fillStyle='#ddd';ctx.font='12px system-ui';ctx.fillText(s.name,canvas.clientWidth/2+s.x*scale-70,canvas.clientHeight/2+s.y*scale-18);}
function render(){ctx.fillStyle='#080d14';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);for(const p of battle.projectiles){ctx.fillStyle='#ffe7a2';ctx.beginPath();ctx.arc(canvas.clientWidth/2+p.x*scale,canvas.clientHeight/2+p.y*scale,1.6,0,Math.PI*2);ctx.fill()}battle.ships.forEach(drawShip);
 const sum=battle.summary();statsEl.innerHTML=sum.ships.map(s=>`<div class="shipstat"><b>${s.name}</b><br>speed ${s.speed.toFixed(1)} m/s · shots ${s.shots} · hits ${s.hits}<br>${s.modules.filter(m=>m.hp>0).length}/${s.modules.length} modules functional<br><small>${battle.ships.find(x=>x.name===s.name).order}</small></div>`).join('')+`<div><b>T+${sum.time.toFixed(1)} s</b>${sum.winner?` · winner: ${sum.winner}`:''}</div>`;
 logEl.innerHTML=battle.events.slice(-8).reverse().map(e=>`<div><span>${e.t.toFixed(1)}s</span> ${e.text}</div>`).join('');}
function loop(now){const elapsed=Math.min(.1,(now-last)/1000);last=now;if(!paused&&!battle.winner){let steps=Math.max(1,Math.round(simSpeed*elapsed/G.dt));for(let i=0;i<steps;i++)battle.step(G.dt)}render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
pauseBtn.onclick=()=>{paused=!paused;pauseBtn.textContent=paused?'Resume':'Pause'};resetBtn.onclick=()=>reset();speedEl.oninput=()=>simSpeed=Number(speedEl.value);batchBtn.onclick=()=>{let A=0,B=0,D=0,t=0;for(let i=1;i<=100;i++){const r=runBattle(i);if(r.winner==='A')A++;else if(r.winner==='B')B++;else D++;t+=r.time}alert(`100 battles\nBroadside: ${A}\nPursuit: ${B}\nDraws: ${D}\nMean duration: ${(t/100).toFixed(1)} s`)};
