import {campaign,saveCampaign} from './campaign-core.js';
import {investigationSummary,resolveLead,migrateLegacyMystery} from './mystery-system.js?v=73';
import {expeditionSummary,searchSite,contactActions,resolveContactAction,reportDiscovery} from './expedition-system.js?v=73';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let signature='',migrated=false;
function ensureHost(){const law=document.querySelector('#lawPanel');if(!law)return null;let host=document.querySelector('#investigationPanel');if(!host){host=document.createElement('section');host.id='investigationPanel';host.className='investigationPanel';law.after(host)}return host}
function contextCard(c){if(!c)return'';return `<article class="mysteryDirective"><b>${esc(c.title)}</b><p>${esc(c.text)}</p>${c.rules?`<ul>${c.rules.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</article>`}
function syncStatus(s){const clues=document.querySelector('#bridgeClues');if(clues){const label=clues.previousElementSibling;if(label)label.textContent='INTEL';clues.textContent=String(s.evidence.length)}const st=document.querySelector('#campaignStatus');if(st)st.innerHTML=st.innerHTML.replace(/mystery clues\s+\d+/i,`${s.evidence.length} intel item${s.evidence.length===1?'':'s'}`)}
function launchMysteryBattle(){if(!(campaign.activeShipIds||[]).length){alert('Assign at least one active ship before beginning the operation.');return false}saveCampaign(campaign);window.__campaignActive=true;document.querySelector('#reset')?.click();const b=window.__fleetBattle;if(b)b.campaignBattle=true;window.__campaignActive=false;document.querySelector('[data-tab="battle"]')?.click();return !!b}
function expeditionHtml(x){
 if(campaign.location!=='Nadir'&&!x.site.contactFound)return `<div class="mysteryBlock expeditionBlock"><b>EXPEDITION</b><article class="lead"><span>${esc(x.site.name)} // NADIR</span><p>Travel to Nadir once your evidence is strong enough to mount a dedicated off-lane search.</p></article></div>`;
 if(!x.unlocked&&!x.site.contactFound)return `<div class="mysteryBlock expeditionBlock"><b>EXPEDITION</b><article class="lead"><span>${esc(x.site.name)}</span><p>The N-17 volume is still too broad. Narrow it through records, witnesses or the initial wreck search.</p></article></div>`;
 const profile=`${x.profile.grade.toUpperCase()} // ${x.profile.sensorRating} SENSOR RATING // ${x.profile.ships} SHIP${x.profile.ships===1?'':'S'}${x.profile.drones?` // ${x.profile.drones} SENSOR DRONE${x.profile.drones===1?'':'S'}`:''}`;
 if(!x.site.contactFound)return `<div class="mysteryBlock expeditionBlock"><b>EXPEDITION // SEARCH VOLUME</b><article class="expeditionSite"><span>${esc(x.site.name)}</span><small>${esc(profile)}</small><p>Search solution <strong>${x.site.searchProgress}%</strong>. Better fitted sensor arrays reduce the time and supplies needed to localise a contact.</p><div class="searchMeter"><i style="width:${x.site.searchProgress}%"></i></div><div class="expeditionActions"><button data-search="cautious">Passive sweep · 4 supplies</button><button data-search="standard">Standard search · 7 supplies</button><button data-search="deep">Deep active survey · 12 supplies</button></div></article></div>`;
 const c=x.contact,done=['seized','destroyed','recovered','contained'].includes(x.site.contactOutcome),actions=done?'':contactActions().map(a=>`<button data-contact-action="${esc(a.id)}">${esc(a.label)}</button>`).join('');
 const reports=[x.context.navy&&!x.site.reportedTo.includes('Navy')?'<button data-report="Navy">Report to Central Navy</button>':'',x.context.merchant&&!x.site.reportedTo.includes('Meridian')?'<button data-report="Meridian">Send evidence to Meridian</button>':'',x.context.underworld&&!x.site.reportedTo.includes('Black Wake')?'<button data-report="Black Wake">Send route intelligence to Black Wake</button>':''].filter(Boolean).join('');
 return `<div class="mysteryBlock expeditionBlock"><b>EXPEDITION CONTACT</b><article class="expeditionContact"><small>${esc(c.classification)}</small><h4>${esc(c.title)}</h4><p>${esc(c.text)}</p><div class="expeditionTelemetry">SEARCH ${x.site.searchProgress}% // CONTACT ${esc((x.site.contactState||'detected').toUpperCase())} // ${esc(profile)}</div>${actions?`<div class="expeditionActions">${actions}</div>`:''}${reports?`<div class="expeditionReports"><span>DISCLOSURE CHANNELS</span>${reports}</div>`:''}</article></div>`;
}
function bindExpedition(host){
 host.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{const r=searchSite(b.dataset.search);if(!r.ok)alert(r.reason||'Search could not be conducted.');signature='';render()});
 host.querySelectorAll('[data-contact-action]').forEach(b=>b.onclick=()=>{const id=b.dataset.contactAction;if((id==='seize'||id==='destroy')&&!confirm(`${id==='seize'?'Begin a seizure':'Open fire on the contact'}? This can trigger a fleet engagement.`))return;const r=resolveContactAction(id);if(!r.ok){alert(r.reason||'Action unavailable.');return}signature='';if(r.battle)launchMysteryBattle();else render()});
 host.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const r=reportDiscovery(b.dataset.report);if(!r.ok)alert(r.reason||'Unable to send report.');signature='';render()});
}
function render(){
 const host=ensureHost();if(!host)return;if(!migrated){migrateLegacyMystery();migrated=true}const s=investigationSummary(),x=expeditionSummary();syncStatus(s);const sig=JSON.stringify([campaign.location,campaign.day,campaign.supplies,s.evidence.map(x=>x.id),s.resolvedLeads,s.hypotheses,campaign.factionRep,campaign.central?.auxiliary,x.site.searchProgress,x.site.contactFound,x.site.contactState,x.site.reportedTo,x.profile]);if(sig===signature)return;signature=sig;
 host.innerHTML=`<div class="mysteryHead"><div><small>ACTIVE INVESTIGATION</small><h3>${esc(s.name)}</h3></div><strong>${s.evidence.length} evidence item${s.evidence.length===1?'':'s'}</strong></div><p class="mysterySummary">${esc(s.summary)}</p>
 ${contextCard(s.context.navy)}${contextCard(s.context.merchant)}${contextCard(s.context.underworld)}
 ${expeditionHtml(x)}
 <div class="mysteryBlock"><b>EVIDENCE</b>${s.evidence.length?s.evidence.map(e=>`<article class="evidence"><span>${esc(e.title)}</span><small>${esc(e.confidence.toUpperCase())} CONFIDENCE // ${esc(e.source)}</small><p>${esc(e.text)}</p></article>`).join(''):'<p>No hard evidence logged yet. The disappearances are currently only a frontier rumour. Better faction access may expose useful records or witnesses.</p>'}</div>
 <div class="mysteryBlock"><b>WORKING HYPOTHESES</b><div class="hypothesisGrid">${s.hypotheses.map(h=>`<div><span>${esc(h.label)}</span><strong>${esc(h.strength.toUpperCase())}</strong></div>`).join('')}</div></div>
 <div class="mysteryBlock"><b>LEADS</b>${s.leads.length?s.leads.map(l=>`<article class="lead ${l.available?'available':''}"><span>${esc(l.title)}${l.system?` // ${esc(l.system)}`:''}</span><p>${esc(l.description)}</p>${l.available?`<button data-lead="${esc(l.id)}">Pursue lead${l.cost?` · ${l.cost} supplies`:''}</button>`:'<small>Not currently in-system.</small>'}</article>`).join(''):'<p>No current conventional leads. The expedition itself may now be the best source of evidence.</p>'}</div>`;
 host.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{const r=resolveLead(b.dataset.lead);if(!r.ok)alert(r.reason||'Unable to pursue that lead.');signature='';render()});bindExpedition(host);
}
render();setInterval(render,400);
