import {Battle} from './sim.js';
import {CRAFT,craftSpace} from './craft-catalog.js';

const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const rot=(x,y,a)=>[x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const BASE_FIRE=Battle.prototype.fireWeapons;
const BASE_UPDATE=Battle.prototype.updateProjectiles;
const BASE_HIT=Battle.prototype.hitRay;
const GROUP=m=>['gun','laser','missile','fighterBay'].includes(m.type)?'weapons':m.type;
const SPENT_MISSILE_GRACE=10;
const MISSILE_CLEARANCE_TIME=.38;
const MISSILE_LAUNCH_SPEED=170;
const MISSILE_TERMINAL_RESERVE=1;
const CAP_RADIUS=2600;
const CAP_INTERCEPT_RADIUS=6200;

export const FIGHTER_DOCTRINES={
 defensive:{label:'Defensive CAP',launchFraction:.55,pounce:false,weakness:.28},
 balanced:{label:'Balanced CAP',launchFraction:.75,pounce:true,weakness:.48},
 strike:{label:'Strike-heavy',launchFraction:.9,pounce:true,weakness:.68}
};

function worldPoint(s,m){const [x,y]=rot(m.x,m.y,s.angle);return{x:s.x+x,y:s.y+y}}
function aliveEnemies(b,s){return b.ships.filter(o=>!o.dead&&o.team!==s.team)}
function chosenEnemy(b,s){const es=aliveEnemies(b,s);return es.find(e=>e.uid===s.commandTargetId)||es.sort((a,c)=>dist(a,s)-dist(c,s))[0]||null}
function chosenModule(attacker,target){const alive=target.modules.filter(m=>m.hp>0&&!m.disabled);for(const p of attacker.targetPriority||[]){const m=alive.find(x=>GROUP(x)===p);if(m)return m}return alive.find(m=>m.type!=='hull')||alive[0]}
function payPower(s,m,kind='offence'){if(!s.requestPower||!(m.powerUse>0))return true;const ok=s.requestPower(m.powerUse,kind);if(ok)m._powerPaidBus=s.powerBus;return ok}
function launchMissile(b,s,m,target,targetOrdnance=null,kind='offence'){if(!payPower(s,m,kind))return false;b.ordnance??=[];const p=worldPoint(s,m),a=wrap(s.angle+(m.mountDir||0)),accel=Math.max(120,(m.missileThrust||85000)/320),fuel=m.missileFuel||9;b.ordnance.push({kind:'missile',team:s.team,owner:s,x:p.x,y:p.y,vx:s.vx+Math.cos(a)*MISSILE_LAUNCH_SPEED,vy:s.vy+Math.sin(a)*MISSILE_LAUNCH_SPEED,angle:a,launchAngle:a,launchTime:b.t,guidanceActiveAt:b.t+MISSILE_CLEARANCE_TIME,ownerSafeUntil:b.t+MISSILE_CLEARANCE_TIME+.18,hp:m.missileHp||24,maxHp:m.missileHp||24,damage:m.damage||100,fuel,maxFuel:fuel,terminalReserve:MISSILE_TERMINAL_RESERVE,motorMode:'clearance',accel,turnRate:1.9,target,targetOrdnance,r:1.3,ttl:Infinity,penetration:m.penetration||1.3,shieldHardness:m.shieldHardness||1});m.ammo--;m.cooldownLeft=m.cooldown||4;return true}

function hangars(s){return s.modules.filter(m=>m.type==='hangar'&&m.hp>0&&!m.disabled)}
function launchBays(s){return s.modules.filter(m=>m.type==='launchBay'&&m.hp>0&&!m.disabled)}
function initialiseHangar(h){if(!h.craftInventory)h.craftInventory={...(h.defaultCraft||{})};h.initialCraft??={...h.craftInventory};h.craftService??=[];return h}
function serviceHangars(s,t){for(const h of hangars(s)){initialiseHangar(h);const ready=h.craftService.filter(x=>x.readyAt<=t),waiting=h.craftService.filter(x=>x.readyAt>t);for(const x of ready)h.craftInventory[x.kind]=(h.craftInventory[x.kind]||0)+1;h.craftService=waiting}}
function hangarUsed(h){initialiseHangar(h);let used=0;for(const [k,n] of Object.entries(h.craftInventory||{}))used+=n*craftSpace(k);for(const x of h.craftService||[])used+=craftSpace(x.kind);return used}
function freeHangarFor(s,kind){const need=craftSpace(kind);return hangars(s).map(initialiseHangar).filter(h=>(h.hangarSpaces||0)-hangarUsed(h)>=need-.001).sort((a,b)=>((b.hangarSpaces||0)-hangarUsed(b))-((a.hangarSpaces||0)-hangarUsed(a)))[0]||null}
function sourceHangarFor(s,kind){return hangars(s).map(initialiseHangar).find(h=>(h.craftInventory?.[kind]||0)>0)||null}
function baySlots(bay){bay._slotUntil??=[];while(bay._slotUntil.length<(bay.launchSlots||1))bay._slotUntil.push(0);return bay._slotUntil}
function acquireBaySlot(s,t,kind='launch'){for(const bay of launchBays(s)){const slots=baySlots(bay),i=slots.findIndex(x=>x<=t);if(i<0)continue;const spec=CRAFT[kind]||CRAFT.fighter,cycle=(kind==='recovery'?(bay.recoveryCycle||3):(bay.launchCycle||2))*((spec.launchTime||1));return{bay,slots,i,cycle}}return null}
function countCraft(s,kind){return hangars(s).reduce((n,h)=>n+(initialiseHangar(h).craftInventory?.[kind]||0),0)}
function initialCraft(s,kind){return hangars(s).reduce((n,h)=>n+(initialiseHangar(h).initialCraft?.[kind]||0),0)}
function deployedCraft(b,s,kind){return (b.ordnance||[]).filter(o=>o.kind===kind&&o.owner===s&&o.hp>0).length}
function launchCraft(b,s,kind,target=null){const spec=CRAFT[kind];if(!spec)return false;serviceHangars(s,b.t);const h=sourceHangarFor(s,kind),slot=acquireBaySlot(s,b.t,kind);if(!h||!slot||!payPower(s,slot.bay,'offence'))return false;h.craftInventory[kind]--;slot.slots[slot.i]=b.t+slot.cycle;const p=worldPoint(s,slot.bay),a=s.angle+(slot.bay.mountDir||0),serial=(s._craftSerial=(s._craftSerial||0)+1);const common={kind,team:s.team,owner:s,homeShip:s,homeShipUid:s.uid,name:`${s.name} ${spec.name.toLowerCase()} ${serial}`,x:p.x,y:p.y,vx:s.vx+Math.cos(a)*95,vy:s.vy+Math.sin(a)*95,angle:a,hp:spec.hp,maxHp:spec.hp,accel:spec.accel,turnRate:spec.turnRate,target,r:spec.r,ttl:9999,fuel:spec.maxFuel,maxFuel:spec.maxFuel,returnFuel:spec.returnFuel,shotCooldown:.4,returning:false,recoveryShip:null};if(kind==='fighter'){common.aiState='forming';common.capIndex=serial-1;common.target=null;common.interceptTarget=null;common.strikeTarget=null}if(kind==='sensorDrone'){common.accel=spec.accel;common.picketAngle=a;common.picketDistance=5200;common.sensorStrength=spec.sensorStrength;}b.ordnance.push(common);b.log(`${s.name}: ${spec.name} launched.`);return true}
function fighterDoctrine(s){return FIGHTER_DOCTRINES[s.fighterDoctrine||'balanced']||FIGHTER_DOCTRINES.balanced}
function maybeAutoLaunchFighter(b,s,e){if(!e||s.runSilent)return;const initial=initialCraft(s,'fighter'),ready=countCraft(s,'fighter'),deployed=deployedCraft(b,s,'fighter'),d=fighterDoctrine(s),reserve=s.fighterReserveFraction??(1-d.launchFraction),reserveCount=Math.ceil(initial*reserve),desired=Math.max(1,Math.ceil(initial*d.launchFraction));if(ready<=reserveCount||deployed>=desired)return;launchCraft(b,s,'fighter',null)}

Battle.prototype.hitRay=function(attacker,target,damage,kind,ray){if(kind==='laser'){const sh=target.modules.find(m=>m.type==='shield'&&m.hp>0&&!m.disabled&&(m.charge||0)>0);if(sh){const absorbed=Math.min(damage,sh.charge*3);sh.charge-=absorbed/3;attacker.damageDone+=absorbed*.05;damage-=absorbed;if(damage<=0)return}}return BASE_HIT.call(this,attacker,target,damage,kind,ray)};
Battle.prototype.fireWeapons=function(s,e,powerBudget){const result=BASE_FIRE.call(this,s,e,powerBudget);e=e&&!e.dead?e:chosenEnemy(this,s);for(const m of s.modules){if(m.hp<=0||m.disabled||(m.cooldownLeft||0)>0)continue;if(m.type==='missile'&&(m.ammo||0)>0&&e){const bearing=Math.atan2(e.y-s.y,e.x-s.x),aim=wrap(s.angle+(m.mountDir||0)),arc=m.arc||Math.PI/12;if(Math.abs(wrap(bearing-aim))<=arc)launchMissile(this,s,m,e,null,'offence')}}maybeAutoLaunchFighter(this,s,e);return result};

function steer(o,target,dt,useFuel=true){if(!target||!useFuel||!(o.fuel>0))return;const wanted=Math.atan2(target.y-o.y,target.x-o.x),err=wrap(wanted-o.angle),turn=clamp(err,-o.turnRate*dt,o.turnRate*dt);o.angle=wrap(o.angle+turn);o.vx+=Math.cos(o.angle)*o.accel*dt;o.vy+=Math.sin(o.angle)*o.accel*dt;o.fuel=Math.max(0,o.fuel-dt)}
function predictiveAim(o,target){const dx=target.x-o.x,dy=target.y-o.y,d=Math.hypot(dx,dy),rvx=(target.vx||0)-o.vx,rvy=(target.vy||0)-o.vy,speed=Math.max(220,Math.hypot(o.vx,o.vy)+o.accel*Math.min(o.fuel||0,2)*.45),lead=clamp(d/speed,0,4);return{x:target.x+rvx*lead,y:target.y+rvy*lead}}
function ballisticApproach(o,t){const rx=t.x-o.x,ry=t.y-o.y,rvx=(t.vx||0)-o.vx,rvy=(t.vy||0)-o.vy,rv2=rvx*rvx+rvy*rvy;if(rv2<1e-6)return{time:Infinity,miss:Math.hypot(rx,ry)};const time=-((rx*rvx)+(ry*rvy))/rv2;if(time<=0)return{time:0,miss:Math.hypot(rx,ry)};return{time,miss:Math.hypot(rx+rvx*time,ry+rvy*time)}}
function missileNeedsTerminalBurn(o,target){const a=ballisticApproach(o,target),hitRadius=(target.r||target.radius||8)+(o.r||1.3)+4;return a.time<=2.2||a.miss>hitRadius*1.25}
function burnMissile(o,a,dt){o.vx+=Math.cos(a)*o.accel*dt;o.vy+=Math.sin(a)*o.accel*dt;o.fuel=Math.max(0,o.fuel-dt)}
function friendlyAvoidanceAngle(b,o,wanted,target){let best=null;const fx=Math.cos(wanted),fy=Math.sin(wanted);for(const s of b.ships){if(s.dead||s.team!==o.team||s===o.owner||s===target)continue;const rx=s.x-o.x,ry=s.y-o.y,ahead=rx*fx+ry*fy;if(ahead<=0||ahead>1600)continue;const lateral=Math.abs(rx*fy-ry*fx),clear=(s.radius||15)+80;if(lateral>=clear)continue;const side=Math.sign(rx*fy-ry*fx)||1,severity=1-lateral/clear;if(!best||severity>best.severity)best={side,severity}}return best?wrap(wanted-best.side*(.28+.42*best.severity)):wanted}
function steerMissile(b,o,target,dt){if(!(o.fuel>0)){o.motorMode='spent';return}o.maxFuel??=o.fuel;o.terminalReserve??=MISSILE_TERMINAL_RESERVE;if(b.t<(o.guidanceActiveAt??0)){const a=o.launchAngle??o.angle;o.angle=a;o.motorMode='clearance';burnMissile(o,a,dt);return}if(!target){o.motorMode='idle';return}const reserve=Math.min(o.terminalReserve,o.maxFuel),inReserve=o.fuel<=reserve+1e-6;if(inReserve&&!missileNeedsTerminalBurn(o,target)){o.motorMode='reserve';return}const aim=predictiveAim(o,target),base=Math.atan2(aim.y-o.y,aim.x-o.x),wanted=friendlyAvoidanceAngle(b,o,base,target),err=wrap(wanted-o.angle),turn=clamp(err,-o.turnRate*dt,o.turnRate*dt);o.angle=wrap(o.angle+turn);o.motorMode=inReserve?'terminal':'midcourse';burnMissile(o,o.angle,dt)}
function damageOrdnance(o,damage){o.hp-=damage;return o.hp<=0}
function defenceRank(s,o){const order=s.defencePriority||['missile','boardingShuttle','fighter','sensorDrone'];const i=order.indexOf(o.kind);return i<0?order.length:i}
function pointDefence(b,dt){for(const s of b.ships){if(s.dead)continue;const hostiles=b.ordnance.filter(o=>o.team!==s.team&&o.hp>0&&dist(o,s)<2600);if(!hostiles.length)continue;hostiles.sort((a,c)=>defenceRank(s,a)-defenceRank(s,c)||dist(a,s)-dist(c,s));for(const w of s.modules){if(w.hp<=0||w.disabled||(w.cooldownLeft||0)>0)continue;if(!['gun','laser','missile'].includes(w.type))continue;const o=hostiles.find(x=>x.hp>0);if(!o)break;const bearing=Math.atan2(o.y-s.y,o.x-s.x),aim=wrap(s.angle+(w.mountDir||0)),arc=(w.arc||Math.PI/12)*1.4;if(Math.abs(wrap(bearing-aim))>arc)continue;const d=dist(o,s);if(w.type==='laser'&&d<Math.min(w.range||9000,3500)){if(!payPower(s,w,'defence'))continue;damageOrdnance(o,(w.damage||20)*1.8);w.cooldownLeft=w.cooldown||.8;s.shots++}else if(w.type==='gun'&&(w.ammo||0)>0&&d<2300){if(!payPower(s,w,'defence'))continue;damageOrdnance(o,(w.damage||40)*.9);w.ammo--;w.cooldownLeft=w.cooldown||1.3;s.shots++}else if(w.type==='missile'&&(w.ammo||0)>0&&d<5000)launchMissile(b,s,w,null,o,'defence')}}}}

function friendlyFleetCentre(b,team){const ships=b.ships.filter(s=>s.team===team&&!s.dead&&!s.escaped&&!s.surrendered);if(!ships.length)return null;return{x:ships.reduce((n,s)=>n+s.x,0)/ships.length,y:ships.reduce((n,s)=>n+s.y,0)/ships.length,vx:ships.reduce((n,s)=>n+(s.vx||0),0)/ships.length,vy:ships.reduce((n,s)=>n+(s.vy||0),0)/ships.length,ships}}
function capStation(b,f){const fleet=friendlyFleetCentre(b,f.team),home=!f.homeShip?.dead?f.homeShip:fleet?.ships?.[0];if(!fleet||!home)return home||null;const enemies=b.ships.filter(s=>s.team!==f.team&&!s.dead),nearest=enemies.sort((a,c)=>dist(a,fleet)-dist(c,fleet))[0],threatAngle=nearest?Math.atan2(nearest.y-fleet.y,nearest.x-fleet.x):(home.angle||0),count=Math.max(1,(b.ordnance||[]).filter(o=>o.kind==='fighter'&&o.team===f.team&&o.hp>0).length),slot=(f.capIndex||0)%count,spread=count===1?0:(slot/(count-1)-.5)*Math.PI*1.15,angle=threatAngle+spread,radius=CAP_RADIUS*(.78+((f.capIndex||0)%3)*.12);return{x:fleet.x+Math.cos(angle)*radius,y:fleet.y+Math.sin(angle)*radius,vx:fleet.vx,vy:fleet.vy}}
function threatToFleet(b,f,o){const fleet=friendlyFleetCentre(b,f.team);if(!fleet||!o||o.hp<=0||o.team===f.team)return Infinity;const d=dist(o,fleet);if(d>CAP_INTERCEPT_RADIUS)return Infinity;const dx=fleet.x-o.x,dy=fleet.y-o.y,r=Math.max(1,Math.hypot(dx,dy)),closing=((o.vx-fleet.vx)*dx+(o.vy-fleet.vy)*dy)/r;const kindScore={missile:0,boardingShuttle:220,fighter:420,sensorDrone:760}[o.kind]??1100;return kindScore+d-Math.max(0,closing)*2.3}
function desiredInterceptors(o){if(o.kind==='boardingShuttle')return 2;if(o.kind==='fighter')return 2;if(o.kind==='sensorDrone')return 1;return (o.hp||1)>45?2:1}
function assignedInterceptors(b,o,excluding=null){return(b.ordnance||[]).filter(f=>f!==excluding&&f.kind==='fighter'&&f.hp>0&&f.aiState==='intercept'&&f.interceptTarget===o).length}
function chooseIntercept(b,f){const threats=(b.ordnance||[]).filter(o=>o!==f&&o.team!==f.team&&o.hp>0&&['missile','boardingShuttle','fighter','sensorDrone'].includes(o.kind)).map(o=>({o,score:threatToFleet(b,f,o)})).filter(x=>Number.isFinite(x.score)).sort((a,c)=>a.score-c.score);return threats.find(x=>assignedInterceptors(b,x.o,f)<desiredInterceptors(x.o))?.o||null}
function moduleFrac(s,type){const ms=(s.modules||[]).filter(m=>m.type===type);if(!ms.length)return 1;const max=ms.reduce((n,m)=>n+(m.maxHp||m.hp||1),0)||1;return ms.reduce((n,m)=>n+Math.max(0,m.hp||0),0)/max}
function hullFrac(s){const ms=s.modules||[],max=ms.reduce((n,m)=>n+(m.maxHp||m.hp||0),0)||1;return ms.reduce((n,m)=>n+Math.max(0,m.hp||0),0)/max}
function pointDefenceThreat(s){return(s.modules||[]).filter(m=>m.hp>0&&!m.disabled&&['pdc','gun','laser'].includes(m.type)).reduce((n,m)=>n+(m.type==='pdc'?1.2:m.type==='laser'?.7:.45),0)}
function vulnerabilityScore(s){const engines=moduleFrac(s,'engine'),weapons=Math.min(moduleFrac(s,'gun'),moduleFrac(s,'missile'),moduleFrac(s,'laser')),hp=hullFrac(s),pd=pointDefenceThreat(s);return clamp((1-engines)*.40+(1-weapons)*.22+(1-hp)*.30+Math.max(0,2-pd)*.08,0,1.2)}
function chooseStrikeTarget(b,f){const d=fighterDoctrine(f.owner||f.homeShip||{});if(!d.pounce)return null;return aliveEnemies(b,f.owner||f.homeShip).map(s=>({s,v:vulnerabilityScore(s)})).filter(x=>x.v>=d.weakness).sort((a,c)=>c.v-a.v||pointDefenceThreat(a.s)-pointDefenceThreat(c.s)||dist(f,a.s)-dist(f,c.s))[0]?.s||null}
function fighterAttack(b,f,dt){f.shotCooldown=Math.max(0,f.shotCooldown-dt);if(f.aiState==='intercept'){const o=f.interceptTarget;if(o&&o.hp>0&&dist(o,f)<950&&f.shotCooldown<=0){damageOrdnance(o,24);f.shotCooldown=.45}return}if(f.aiState!=='strike')return;const target=f.strikeTarget;if(!target||target.dead)return;if(dist(f,target)<720&&f.shotCooldown<=0){const m=chosenModule(f.owner,target);if(m){const [rx,ry]=rot(m.x,m.y,target.angle),tx=target.x+rx,ty=target.y+ry;b.hitRay(f.owner,target,18,'fighter',{x:f.x,y:f.y,dx:tx-f.x,dy:ty-f.y,penetration:.85});f.shotCooldown=.38}}}
function recoveryCongestion(s,b,t){const bays=launchBays(s);if(!bays.length)return 9999;let busy=0,total=0;for(const bay of bays){for(const until of baySlots(bay)){total++;if(until>t)busy++}}return total?busy/total:1}
function compatibleRecoveryShips(b,f){return b.ships.filter(s=>s.team===f.team&&!s.dead&&launchBays(s).length&&freeHangarFor(s,f.kind))}
function chooseRecoveryShip(b,f){const candidates=compatibleRecoveryShips(b,f);if(!candidates.length)return null;const critical=f.fuel<Math.max(10,f.returnFuel*.35)||f.hp/f.maxHp<.22;return candidates.sort((a,c)=>{const score=s=>{let v=dist(f,s)+recoveryCongestion(s,b,b.t)*1400;if(!critical&&s===f.homeShip)v-=2200;if(s===f.homeShip&&recoveryCongestion(s,b,b.t)>.8)v+=900;return v};return score(a)-score(c)})[0]}
function attemptDock(b,f,s){const d=dist(f,s),rv=Math.hypot(f.vx-s.vx,f.vy-s.vy);if(d>Math.max(55,(s.radius||15)+30)||rv>95)return false;const slot=acquireBaySlot(s,b.t,'recovery'),h=freeHangarFor(s,f.kind);if(!slot||!h)return false;slot.slots[slot.i]=b.t+(slot.bay.recoveryCycle||3)*(CRAFT[f.kind]?.recoveryTime||1);initialiseHangar(h);h.craftService.push({kind:f.kind,readyAt:slot.slots[slot.i]+(CRAFT[f.kind]?.serviceTime||8)});f.hp=0;f.recovered=true;b.log(`${f.name} recovered aboard ${s.name}${s===f.homeShip?'':' after diverting'}.`);return true}
function updateReturningCraft(b,f,dt){let ship=f.recoveryShip;if(!ship||ship.dead||!freeHangarFor(ship,f.kind)){ship=chooseRecoveryShip(b,f);f.recoveryShip=ship}if(!ship){f.x+=f.vx*dt;f.y+=f.vy*dt;return}steer(f,ship,dt,true);f.x+=f.vx*dt;f.y+=f.vy*dt;attemptDock(b,f,ship)}
function updateFighter(b,f,dt){
 if(!f.returning&&(f.fuel<=f.returnFuel||f.hp/f.maxHp<.35||f.recallRequested)){f.returning=true;f.aiState='return';f.interceptTarget=null;f.strikeTarget=null;f.recoveryShip=chooseRecoveryShip(b,f)}
 if(f.returning){updateReturningCraft(b,f,dt);return}
 if(f.interceptTarget?.hp<=0||f.interceptTarget?.team===f.team)f.interceptTarget=null;
 if(f.strikeTarget?.dead||vulnerabilityScore(f.strikeTarget)<fighterDoctrine(f.owner||{}).weakness*.72)f.strikeTarget=null;
 let intercept=f.interceptTarget||chooseIntercept(b,f);
 if(intercept){f.aiState='intercept';f.interceptTarget=intercept;f.strikeTarget=null;steer(f,intercept,dt,true);fighterAttack(b,f,dt);f.x+=f.vx*dt;f.y+=f.vy*dt;return}
 const strike=f.strikeTarget||chooseStrikeTarget(b,f);
 if(strike&&pointDefenceThreat(strike)<=3.4){f.aiState='strike';f.strikeTarget=strike;steer(f,strike,dt,true);fighterAttack(b,f,dt);if(dist(f,strike)<520&&pointDefenceThreat(strike)>1.5){f.strikeTarget=null;f.aiState='cap'}f.x+=f.vx*dt;f.y+=f.vy*dt;return}
 f.interceptTarget=null;f.strikeTarget=null;f.aiState='cap';const station=capStation(b,f);if(station){const d=dist(f,station);if(d>280)steer(f,station,dt,true);else{f.fuel=Math.max(0,f.fuel-dt*.055);const match=.08;f.vx+=(station.vx-f.vx)*match;f.vy+=(station.vy-f.vy)*match}}f.x+=f.vx*dt;f.y+=f.vy*dt;
}
function updateSensorDrone(b,d,dt){if(!d.returning&&(d.fuel<=d.returnFuel||d.recallRequested||d.homeShip?.dead)){d.returning=true;d.recoveryShip=chooseRecoveryShip(b,d)}if(d.returning){updateReturningCraft(b,d,dt);return}const home=d.homeShip;if(!home||home.dead){d.returning=true;d.recoveryShip=chooseRecoveryShip(b,d);d.x+=d.vx*dt;d.y+=d.vy*dt;return}const target={x:home.x+Math.cos(d.picketAngle)*d.picketDistance,y:home.y+Math.sin(d.picketAngle)*d.picketDistance};if(dist(d,target)>260)steer(d,target,dt,true);else d.fuel=Math.max(0,d.fuel-dt*.08);d.x+=d.vx*dt;d.y+=d.vy*dt}
function activeTargetOrdnance(b,o){const t=o.targetOrdnance;return t&&t.hp>0&&(b.ordnance||[]).includes(t)?t:null}
function ballisticMissDistance(o,t){return ballisticApproach(o,t).miss}
function plausibleBallisticThreat(b,o,t){if(!t)return false;const radius=(t.r||t.radius||8)+Math.max(18,Math.hypot(o.vx-(t.vx||0),o.vy-(t.vy||0))*.035);return ballisticMissDistance(o,t)<=radius}
function segmentCircleHit(ax,ay,bx,by,cx,cy,r){const dx=bx-ax,dy=by-ay,fx=ax-cx,fy=ay-cy,a=dx*dx+dy*dy;if(a<1e-9)return Math.hypot(fx,fy)<=r?0:null;const bb=2*(fx*dx+fy*dy),cc=fx*fx+fy*fy-r*r,disc=bb*bb-4*a*cc;if(disc<0)return null;const root=Math.sqrt(disc),ts=[(-bb-root)/(2*a),(-bb+root)/(2*a)].filter(t=>t>=0&&t<=1);return ts.length?Math.min(...ts):null}
function missileShipCollision(b,o,ax,ay,bx,by){let hit=null;for(const s of b.ships){if(s.dead)continue;if(s===o.owner&&b.t<(o.ownerSafeUntil??0))continue;const u=segmentCircleHit(ax,ay,bx,by,s.x,s.y,(s.radius||15)+(o.r||1.3));if(u==null)continue;if(!hit||u<hit.u)hit={s,u}}if(!hit)return false;const s=hit.s,hx=ax+(bx-ax)*hit.u,hy=ay+(by-ay)*hit.u;if(s.team===o.team)b.log(`${o.owner?.name||'Missile'}: missile struck friendly ${s.name}.`);b.hitRay(o.owner,s,o.damage,'missile',{x:hx,y:hy,dx:o.vx-(s.vx||0),dy:o.vy-(s.vy||0),penetration:o.penetration||1.3,shieldHardness:o.shieldHardness||1});o.x=hx;o.y=hy;o.hp=0;return true}
function updateOrdnance(b,dt){b.ordnance??=[];for(const s of b.ships)if(!s.dead)serviceHangars(s,b.t);pointDefence(b,dt);for(const o of b.ordnance){if(o.hp<=0)continue;if(Number.isFinite(o.ttl))o.ttl-=dt;if(o.kind==='missile'){const ordnanceTarget=activeTargetOrdnance(b,o);if(o.targetOrdnance&&!ordnanceTarget)o.targetOrdnance=null;const t=ordnanceTarget||(!o.target?.dead?o.target:null),ax=o.x,ay=o.y;steerMissile(b,o,t,dt);const bx=o.x+o.vx*dt,by=o.y+o.vy*dt;if(missileShipCollision(b,o,ax,ay,bx,by))continue;o.x=bx;o.y=by;if(o.fuel<=0&&o.fuelExhaustedAt==null)o.fuelExhaustedAt=b.t;if(ordnanceTarget&&dist(o,ordnanceTarget)<(ordnanceTarget.r||8)+4){damageOrdnance(ordnanceTarget,o.damage*.8);o.hp=0}else if(o.fuelExhaustedAt!=null&&b.t-o.fuelExhaustedAt>=SPENT_MISSILE_GRACE&&!plausibleBallisticThreat(b,o,t)){o.hp=0;o.garbageCollected=true}}else if(o.kind==='fighter')updateFighter(b,o,dt);else if(o.kind==='sensorDrone')updateSensorDrone(b,o,dt)}b.ordnance=b.ordnance.filter(o=>o.hp>0&&(o.kind==='missile'||o.ttl>0))}
Battle.prototype.updateProjectiles=function(dt){BASE_UPDATE.call(this,dt);updateOrdnance(this,dt)};

export function setFighterReserve(ship,fraction){ship.fighterReserveFraction=clamp(fraction,0,1)}
export function setFighterDoctrine(ship,id){if(FIGHTER_DOCTRINES[id])ship.fighterDoctrine=id;return ship.fighterDoctrine||'balanced'}
export function launchSensorDrone(b,ship){return launchCraft(b,ship,'sensorDrone',null)}
export function recallCraft(ship,b,kind=null){for(const o of b.ordnance||[])if(o.team===ship.team&&o.owner===ship&&(!kind||o.kind===kind))o.recallRequested=true}
export function craftInventory(ship){const out={fighter:0,sensorDrone:0,servicing:0,deployed:0};for(const h of hangars(ship)){initialiseHangar(h);for(const k of ['fighter','sensorDrone'])out[k]+=h.craftInventory?.[k]||0;out.servicing+=(h.craftService||[]).length}return out}
