import {campaign,saveCampaign,persistBattleResults} from './campaign-core.js';
import {registerBattleHook} from './battle-hooks.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SEARCH={
 geometry:{name:'ARGOSY launch geometry',summary:'Recover the exact phase and field orientation used when ARGOSY left ORISON.',cost:6,days:1,text:'ORISON’s launch bus preserves the outbound field phase to within a few milliseconds. The solution is deliberately asymmetric: it was meant to work once and leave no stable return geometry behind.'},
 clock:{name:'Courier clock correlation',summary:'Use the Lacuna courier recorder to anchor ORISON’s damaged timing reference.',cost:5,days:1,text:'The courier clock bridges Lacuna and ORISON well enough to remove a decades-old timing ambiguity. The destination solution shifts by several light-seconds from ORISON’s degraded estimate.'},
 mass:{name:'Destination mass fit',summary:'Infer PEREGRINE’s local gravity field from the way the original route solution was shaped.',cost:8,days:2,text:'The route terminus was built around a modest stellar system, not open interstellar space. A faint modern infrared source sits inside the reconstructed error volume.'}
};
function fresh(){return{search:{geometry:false,clock:false,mass:false},routeSolved:false,prep:null,quality:0,attempts:0,arrived:false,clues:[],complete:false}}
function ensure(){campaign.mainPlot??={};campaign.mainPlot.peregrine??=fresh();const p=campaign.mainPlot.peregrine;p.search??={geometry:false,clock:false,mass:false};p.clues??=[];return p}
function core(){return campaign.mainPlot?.orisonCore}
function unlocked(){return campaign.location==='Lacuna Reach'&&core()?.complete&&core()?.nextLead==='PEREGRINE'&&!!core()?.disclosure}
function add(text){const p=ensure();p.clues.push({day:campaign.day,text});campaign.log??=[];campaign.log.push(`Day ${campaign.day}: PEREGRINE — ${text}`)}
function baseQuality(){const c=core();let q=.48+(c?.recorderIntegrity||0)*.20+(c?.corePath==='restore'?.14:.04);if(c?.disclosure==='share')q+=.06;return clamp(q,.45,.9)}
function solveIfReady(){const p=ensure();if(p.routeSolved||!Object.values(p.search).every(Boolean))return;p.routeSolved=true;p.quality=baseQuality();add('PEREGRINE route reconstructed. It is a viable one-way solution, but ORISON deliberately destroyed the local return key. Committing the fleet means accepting that there may be no route back until something is found at the far endpoint.');}
export function peregrineSummary(){const p=ensure();return{...p,available:unlocked()||p.arrived,pending:campaign.pendingEncounter?.kind==='peregrineTransit',search:Object.entries(SEARCH).map(([id,r])=>({id,...r,resolved:!!p.search[id],available:unlocked()&&!p.search[id]})),canPrep:p.routeSolved&&!p.prep&&!campaign.pendingEncounter,canTransit:p.routeSolved&&!!p.prep&&!p.arrived&&!campaign.pendingEncounter}}
export function investigatePeregrineLead(id){const p=ensure(),r=SEARCH[id];if(!unlocked())return{ok:false,reason:'The PEREGRINE lead is not yet available.'};if(!r)return{ok:false,reason:'Unknown route reconstruction operation.'};if(p.search[id])return{ok:false,reason:'That reconstruction is already complete.'};if(campaign.supplies<r.cost)return{ok:false,reason:`This operation requires ${r.cost} supplies.`};campaign.supplies-=r.cost;campaign.day+=r.days;p.search[id]=true;add(`${r.name}: ${r.text}`);solveIfReady();saveCampaign(campaign);return{ok:true}}
export function preparePeregrineRoute(mode){const p=ensure();if(!p.routeSolved)return{ok:false,reason:'Reconstruct the PEREGRINE route first.'};if(p.prep)return{ok:false,reason:'The route preparation decision is already recorded.'};if(!['stabilise','lean'].includes(mode))return{ok:false,reason:'Unknown route preparation.'};const cost=mode==='stabilise'?12:4,days=mode==='stabilise'?2:1;if(campaign.supplies<cost)return{ok:false,reason:`This preparation requires ${cost} supplies.`};campaign.supplies-=cost;campaign.day+=days;p.prep=mode;if(mode==='stabilise'){p.quality=clamp(p.quality+.18,0,1);add('Fleet fabricates a full field-conditioning package and spends two days validating the outbound solution against ORISON’s surviving hardware. Transit margin improves, but the route remains one-way.')}else add('Fleet prepares only the minimum field package needed to energise the reconstructed solution. Stores are conserved, but there is less margin for timing drift and route shear.');saveCampaign(campaign);return{ok:true}}
export function queuePeregrineTransit(){const p=ensure();if(!p.routeSolved||!p.prep)return{ok:false,reason:'Finish route reconstruction and preparation first.'};if(p.arrived)return{ok:false,reason:'The fleet is already at PEREGRINE.'};if(campaign.pendingEncounter)return{ok:false,reason:'Another encounter is pending.'};if(campaign.supplies<10)return{ok:false,reason:'Energising the one-way route requires 10 supplies of field hardware and expendables.'};campaign.supplies-=10;p.attempts=(p.attempts||0)+1;campaign.pendingEncounter={kind:'peregrineTransit',title:'One-way transit to PEREGRINE',quality:p.quality,attempt:p.attempts};campaign.day+=1;add(`PEREGRINE route energised for attempt ${p.attempts}. ORISON has no surviving return key; the fleet commits to the outbound solution.`);saveCampaign(campaign);return{ok:true,encounter:campaign.pendingEncounter}}

function scenario(b){return b?.nonCombatScenario==='peregrineTransit'}
function players(b){return(b.ships||[]).filter(s=>s.team==='P'&&!s.dead&&!s.civilianEscort)}
function init(b){if(b.peregrineTransitState)return b.peregrineTransitState;const enc=campaign.pendingEncounter||{};b.peregrineTransitState={startedAt:b.t,duration:62,nextPulse:b.t+4,pulses:0,quality:clamp(enc.quality??.6,.35,1),finished:false};b.log('PEREGRINE transit: outbound field locked. No stable return geometry exists behind the fleet.');return b.peregrineTransitState}
registerBattleHook('beforeApplySystems','peregrine-transit-flight',({battle,ship})=>{if(!scenario(battle)||ship.team!=='P'||ship.dead)return;ship.throttle=.12;ship.desiredAngle=.02*Math.sin(battle.t*.08);ship.order='Hold one-way route solution'},202);
registerBattleHook('afterStep','peregrine-transit-shear',({battle})=>{if(!scenario(battle))return;const st=init(battle);if(st.finished)return;const ps=players(battle);if(!ps.length){st.finished=true;battle.winner='E';return}if(battle.t>=st.nextPulse){st.pulses++;const severity=.018+(1-st.quality)*.055;for(const s of ps){const live=(s.modules||[]).filter(m=>m.hp>0);if(!live.length)continue;const hits=st.quality<.65?2:1;for(let i=0;i<hits;i++){const m=live[Math.floor(battle.rng.next()*live.length)];const max=m.maxHp||m.hp||1,frac=battle.rng.range(severity,severity*1.65);m.hp=Math.max(0,m.hp-max*frac)}s.vx+=battle.rng.range(-34,34);s.vy+=battle.rng.range(-42,42)}st.nextPulse=battle.t+battle.rng.range(4.8,7.5);battle.log(`PEREGRINE route shear ${st.pulses}: field solution departs nominal envelope.`)}if(battle.t-st.startedAt<st.duration){battle.winner=null;return}st.finished=true;battle.winner='P';battle.log('PEREGRINE endpoint capture: local stars and inertial references stabilise around the fleet.')},245);
registerBattleHook('afterStep','peregrine-transit-outcome',({battle})=>{if(!scenario(battle)||!battle.winner||battle._peregrineResolved)return;const enc=campaign.pendingEncounter;if(enc?.kind!=='peregrineTransit')return;battle._peregrineResolved=true;battle._campaignPersisted=true;persistBattleResults(battle);campaign.pendingEncounter=null;campaign.day+=1;const p=ensure(),st=init(battle);if(battle.winner==='P'){p.arrived=true;p.complete=true;campaign.location='Peregrine';campaign.knownSystems??=[];if(!campaign.knownSystems.includes('Peregrine'))campaign.knownSystems.push('Peregrine');campaign.mainPlot.act='peregrine-arrival';add(`Fleet emerges at PEREGRINE after ${st.pulses} major shear events. The route collapses behind it; no usable return key is detected.`);add('The endpoint is not dead. Passive sensors immediately resolve several maintained power sources, regular traffic vectors and a low-power navigation lattice using protocols descended from ORISON’s continuity standard. Someone built a lasting human presence here.')}else add('PEREGRINE transit failed before endpoint capture. No surviving fleet element completed the route.');saveCampaign(campaign)},-104);
export function peregrineBattleSummary(b){if(!scenario(b))return null;const st=init(b);return{quality:st.quality,pulses:st.pulses,timeRemaining:Math.max(0,st.duration-(b.t-st.startedAt)),ships:players(b).length}}
if(typeof window!=='undefined')window.__peregrineTransit={peregrineSummary,investigatePeregrineLead,preparePeregrineRoute,queuePeregrineTransit,peregrineBattleSummary:()=>peregrineBattleSummary(window.__fleetBattle)};
