import {campaign,saveCampaign} from './campaign-core.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const TOPICS={
 founders:{name:'The founders’ account',summary:'Ask what the Twenty-Nine recorded about Lacuna, ORISON and the decision to keep moving.',finding:'The Council opens a founding testimony assembled from ARGOSY crew statements. The Twenty-Nine did not believe one hidden enemy caused everything. They recorded an accidental Lacuna resonance when two obsolete route solutions overlapped, followed by ORISON’s deliberate evacuation. Their central lesson was narrower and more frightening: coupled route fields can disturb both endpoints, and repeated activations can accumulate errors faster than operators can see them.'},
 taboo:{name:'Why route activation became taboo',summary:'Ask what happened at PEREGRINE after ARGOSY arrived and why even experimental energisation is forbidden.',finding:'ARGOSY’s arrival was followed by a delayed field wake that overloaded PEREGRINE’s primitive receiver hardware and injured several founders. Years later, engineers attempted a low-energy outbound calibration. They aborted before opening a route, but the test reproduced the same precursor harmonics seen in the founding wake. The Continuity Council then prohibited full route energisation and split all surviving geometry between independent custodians.'},
 geometry:{name:'The surviving return geometry',summary:'Ask directly whether PEREGRINE can reconstruct a path back toward ORISON and Lacuna.',finding:'The Council admits that the founders did not destroy everything. A cold reciprocal seed survives, divided into three custody blocks held by Navigation, Habitat Authority and the Twenty-Nine Archive. None is sufficient to energise a route alone. Combined with your ORISON launch record, the fragments could reconstruct a destination-side return solution — but only after non-energising modelling proves the coupled field will not repeat the Burn.'}
};
function fresh(){return{meetingOpened:false,topics:{founders:false,taboo:false,geometry:false},topicsComplete:false,inspection:false,routePolicy:null,seedAccess:null,trustAtMeeting:null,history:[],complete:false,nextLead:null}}
function ensure(){campaign.mainPlot??={};campaign.mainPlot.peregrineCouncil??=fresh();const s=campaign.mainPlot.peregrineCouncil;s.topics??={founders:false,taboo:false,geometry:false};s.history??=[];return s}
function contact(){return campaign.mainPlot?.peregrineContact}
function available(){return campaign.location==='Peregrine'&&!!contact()?.complete&&contact()?.nextLead==='PEREGRINE_COUNCIL'}
function trust(delta){const c=contact();if(!c)return 0;c.trust=clamp((c.trust||0)+delta,-8,10);return c.trust}
function add(text){const s=ensure();s.history.push({day:campaign.day,text});campaign.log??=[];campaign.log.push(`Day ${campaign.day}: PEREGRINE Council — ${text}`)}
function finishTopics(){const s=ensure();if(s.topicsComplete||!Object.values(s.topics).every(Boolean))return;s.topicsComplete=true;add('Council dialogue establishes a consistent founding record: PEREGRINE’s isolation is deliberate risk control, not ignorance. A reciprocal seed exists, but no single institution can activate it.')}
export function peregrineCouncilSummary(){const s=ensure(),c=contact();return{...s,available:available(),trust:c?.trust||0,identity:c?.identity||null,topicsList:Object.entries(TOPICS).map(([id,t])=>({id,...t,resolved:!!s.topics[id],available:s.meetingOpened&&!s.topics[id]})),canOpen:available()&&!s.meetingOpened,canInspect:s.meetingOpened&&!s.inspection&&(c?.trust||0)<2,canChoose:s.topicsComplete&&!s.routePolicy}}
export function openCouncilMeeting(){const s=ensure(),c=contact();if(!available())return{ok:false,reason:'PEREGRINE first contact has not reached the Council stage.'};if(s.meetingOpened)return{ok:false,reason:'The Council meeting is already open.'};s.meetingOpened=true;s.trustAtMeeting=c?.trust||0;campaign.day+=1;if((c?.trust||0)>=2)add('The Peregrine Continuity Council accepts a direct meeting aboard its central habitat. Chair Mara Venn opens with the authenticated ORISON names on the table: “You crossed a road we inherited as a warning. Before we discuss reopening it, you need to understand why we kept it dead.”');else add('The Council agrees to a remote conference under Outer Watch supervision. Chair Mara Venn is explicit that first contact did not establish trust: “We will answer history before we discuss access. Your fleet remains outside the inner docking envelope.”');saveCampaign(campaign);return{ok:true}}
export function acceptCouncilInspection(){const s=ensure();if(!s.meetingOpened)return{ok:false,reason:'Open the Council meeting first.'};if(s.inspection)return{ok:false,reason:'The inspection is already complete.'};if((contact()?.trust||0)>=2)return{ok:false,reason:'The Council is not requiring additional verification.'};s.inspection=true;campaign.day+=1;trust(2);add('Fleet accepts a passive drive-and-field inspection by PEREGRINE engineers and transmits the ORISON route package for checksum verification. No weapon or command access is granted. The successful comparison reduces immediate suspicion.');saveCampaign(campaign);return{ok:true}}
export function askCouncilTopic(id){const s=ensure(),t=TOPICS[id];if(!s.meetingOpened)return{ok:false,reason:'Open the Council meeting first.'};if(!t)return{ok:false,reason:'Unknown Council topic.'};if(s.topics[id])return{ok:false,reason:'That Council topic is already resolved.'};s.topics[id]=true;campaign.day+=1;add(`${t.name}: ${t.finding}`);finishTopics();saveCampaign(campaign);return{ok:true}}
export function chooseReturnRoutePolicy(policy){const s=ensure();if(!s.topicsComplete)return{ok:false,reason:'Complete the Council dialogue before deciding return-route custody.'};if(s.routePolicy)return{ok:false,reason:'Return-route policy is already recorded.'};if(!['joint','defer','demand'].includes(policy))return{ok:false,reason:'Unknown return-route policy.'};s.routePolicy=policy;campaign.day+=1;
 if(policy==='joint'){
   trust(2);s.seedAccess='full-supervised';s.nextLead='PEREGRINE_RETURN_ENGINEERING';add('Fleet accepts joint custody. The Council releases all three reciprocal-seed blocks into a supervised modelling environment while retaining independent abort authority. No route may be energised until simulation and unmanned probe work clears the coupled-field risk.');
 }else if(policy==='defer'){
   trust(3);s.seedAccess='archive-only';s.nextLead='PEREGRINE_RETURN_ENGINEERING';add('Fleet agrees not to energise a return route yet. The Council provides a non-operational merged archive for modelling and historical analysis but keeps the live custody blocks separated. The option to revisit supervised reconstruction remains open if the evidence improves.');
 }else{
   trust(-3);s.seedAccess='partial';s.nextLead='PEREGRINE_RETURN_ENGINEERING';add('Fleet insists that being stranded gives it a right to the return geometry. The Council refuses sole transfer, releases only the Navigation block and public error model, and moves the other two custody blocks under armed protection. Engineering can proceed, but with poorer data and a political confrontation now attached to it.');
 }
 s.complete=true;campaign.mainPlot.act='peregrine-return-engineering';saveCampaign(campaign);return{ok:true,trust:contact()?.trust||0,seedAccess:s.seedAccess}}
if(typeof window!=='undefined')window.__peregrineCouncil={peregrineCouncilSummary,openCouncilMeeting,acceptCouncilInspection,askCouncilTopic,chooseReturnRoutePolicy};
