export const G={dt:0.05,projectileTTL:24,c:299792458};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const cross=(ax,ay,bx,by)=>ax*by-ay*bx;
const len=(x,y)=>Math.hypot(x,y);
const rot=(x,y,a)=>[x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];
const dot=(ax,ay,bx,by)=>ax*bx+ay*by;
const DEFAULT_TARGET_PRIORITY=['weapons','engine','reactor','bridge','shield','radiator','armor','hull'];

function solveIntercept(rx,ry,vx,vy,speed){
  const a=vx*vx+vy*vy-speed*speed,b=2*(rx*vx+ry*vy),c=rx*rx+ry*ry;let t=null;
  if(Math.abs(a)<1e-9){if(Math.abs(b)>1e-9){const q=-c/b;if(q>0)t=q;}}
  else{const d=b*b-4*a*c;if(d>=0){const r=Math.sqrt(d),xs=[(-b-r)/(2*a),(-b+r)/(2*a)].filter(x=>x>0);if(xs.length)t=Math.min(...xs);}}
  return t;
}
function interceptAngleState(shooter,state,speed){
  const rx=state.x-shooter.x,ry=state.y-shooter.y,vx=state.vx-shooter.vx,vy=state.vy-shooter.vy,t=solveIntercept(rx,ry,vx,vy,speed);
  return t==null?Math.atan2(ry,rx):Math.atan2(ry+vy*t,rx+vx*t);
}
export class RNG{constructor(seed=1){this.s=seed>>>0||1}next(){let x=this.s;x^=x<<13;x^=x>>>17;x^=x<<5;this.s=x>>>0;return this.s/4294967296}range(a,b){return a+(b-a)*this.next()}}

const MODULE_DEFAULTS={
  hull:{mass:12,hp:260},armor:{mass:18,hp:420,absorb:0.68},reactor:{mass:22,hp:180,power:24e6},
  engine:{mass:12,hp:150,force:1.8e6,powerUse:5e6},gun:{mass:8,hp:120,powerUse:.2e6,ammo:100,projectileMass:18,muzzle:1300,damage:95,cooldown:1.25,penetration:1},
  laser:{mass:7,hp:105,powerUse:4e6,damage:60,cooldown:.7,range:4800,penetration:.7},missile:{mass:10,hp:110,powerUse:.4e6,ammo:12,damage:220,cooldown:4},
  shield:{mass:14,hp:130,powerUse:6e6,capacity:500,recharge:45},bridge:{mass:7,hp:140},radiator:{mass:8,hp:120}
};
function mod(type,x,y,opts={}){return{type,x,y,...MODULE_DEFAULTS[type],...opts,id:opts.id||`${type}-${Math.random().toString(36).slice(2,8)}`,cooldownLeft:0,active:false,disabled:false}}

export function buildBroadsideFrigate(team='A'){
 const ms=[mod('hull',0,0,{mass:95,hp:1250,id:'keel'}),mod('armor',0,0,{mass:75,hp:1050,id:'belt'}),mod('bridge',2,0,{id:'bridge'}),mod('reactor',-4,0,{id:'reactor',power:34e6}),mod('shield',0,0,{id:'shield-belt',capacity:620,recharge:42}),mod('engine',-10,-3,{id:'engine-port',force:1.5e6,dir:0}),mod('engine',-10,3,{id:'engine-starboard',force:1.5e6,dir:0}),mod('engine',7,-5,{id:'retro-port',force:.55e6,dir:Math.PI}),mod('engine',7,5,{id:'retro-starboard',force:.55e6,dir:Math.PI}),mod('gun',0,-6,{id:'port-1',mountDir:-Math.PI/2,ammo:90}),mod('gun',5,-6,{id:'port-2',mountDir:-Math.PI/2,ammo:90}),mod('gun',-5,-6,{id:'port-3',mountDir:-Math.PI/2,ammo:90}),mod('gun',0,6,{id:'stbd-1',mountDir:Math.PI/2,ammo:90}),mod('gun',5,6,{id:'stbd-2',mountDir:Math.PI/2,ammo:90}),mod('gun',-5,6,{id:'stbd-3',mountDir:Math.PI/2,ammo:90})];
 return shipFromModules('Resolute-class broadside frigate',team,ms,{length:24,width:14,ai:'broadside'});
}
export function buildPursuitFrigate(team='B'){
 const ms=[mod('hull',0,0,{mass:60,hp:850,id:'keel'}),mod('armor',3,0,{mass:26,hp:340,id:'bow-armor'}),mod('bridge',1,0,{id:'bridge'}),mod('reactor',-2,0,{id:'reactor',power:30e6}),mod('shield',6,0,{id:'shield-bow',capacity:620,recharge:50}),mod('engine',-9,-4,{id:'main-port',force:2.15e6,dir:0}),mod('engine',-9,4,{id:'main-starboard',force:2.15e6,dir:0}),mod('engine',0,-6,{id:'turn-port-a',force:.75e6,dir:Math.PI/2}),mod('engine',0,6,{id:'turn-stbd-a',force:.75e6,dir:-Math.PI/2}),mod('engine',7,-5,{id:'retro-port',force:.65e6,dir:Math.PI}),mod('engine',7,5,{id:'retro-starboard',force:.65e6,dir:Math.PI}),mod('gun',7,-2.8,{id:'bow-gun-1',mountDir:0,ammo:130,muzzle:1450,damage:82,cooldown:.9}),mod('gun',7,2.8,{id:'bow-gun-2',mountDir:0,ammo:130,muzzle:1450,damage:82,cooldown:.9}),mod('laser',5,0,{id:'bow-laser',mountDir:0,range:3600,damage:45,cooldown:.55})];
 return shipFromModules('Vigilant-class pursuit frigate',team,ms,{length:22,width:13,ai:'pursuit'});
}

export function shipFromModules(name,team,modules,opts={}){
 const s={name,team,modules,x:0,y:0,vx:0,vy:0,angle:0,omega:0,length:opts.length||20,width:opts.width||12,ai:opts.ai||'pursuit',grid:opts.grid||null,targetPriority:[...(opts.targetPriority||DEFAULT_TARGET_PRIORITY)],dead:false,kills:0,shots:0,hits:0,damageDone:0,order:'',desiredAngle:0,throttle:0,timeAlive:0};recalc(s);return s;
}
export function recalc(s){s.mass=s.modules.filter(m=>m.hp>0).reduce((a,m)=>a+(m.mass||0),0)*1000;s.inertia=Math.max(1,s.modules.filter(m=>m.hp>0).reduce((a,m)=>a+(m.mass||0)*1000*(m.x*m.x+m.y*m.y+4),0));s.radius=Math.hypot(s.length/2,s.width/2);s.power=s.modules.filter(m=>m.type==='reactor'&&m.hp>0).reduce((a,m)=>a+m.power*(m.hp/(m.maxHp||m.hp)),0)}
function initModule(m){m.maxHp=m.hp;if(m.type==='shield')m.charge=m.capacity;return m}
export function initialiseShip(s){s.modules.forEach(initModule);recalc(s);return s}
function aliveMods(s,type){return s.modules.filter(m=>m.type===type&&m.hp>0&&!m.disabled)}
function localToWorld(s,m){const [rx,ry]=rot(m.x,m.y,s.angle);return[s.x+rx,s.y+ry]}
function worldToLocal(s,x,y){return rot(x-s.x,y-s.y,-s.angle)}
function targetPointState(s,m){const [rx,ry]=rot(m.x,m.y,s.angle);return{x:s.x+rx,y:s.y+ry,vx:s.vx-s.omega*ry,vy:s.vy+s.omega*rx}}
function groupOf(m){return ['gun','laser','missile'].includes(m.type)?'weapons':m.type}
function segAabb(ox,oy,dx,dy,minx,miny,maxx,maxy){let t0=0,t1=Infinity;for(const [o,d,mn,mx] of [[ox,dx,minx,maxx],[oy,dy,miny,maxy]]){if(Math.abs(d)<1e-9){if(o<mn||o>mx)return null;continue}let a=(mn-o)/d,b=(mx-o)/d;if(a>b)[a,b]=[b,a];t0=Math.max(t0,a);t1=Math.min(t1,b);if(t1<t0)return null}return t1>=0?Math.max(0,t0):null}
function moduleRayT(s,m,ox,oy,dx,dy){if(!m.gridCells?.length||!s.grid)return null;const cs=s.grid.cellMetres;let best=null;for(const [cx,cy] of m.gridCells){const minx=(cx-s.grid.width/2)*cs,miny=(cy-s.grid.height/2)*cs,t=segAabb(ox,oy,dx,dy,minx,miny,minx+cs,miny+cs);if(t!=null&&(best==null||t<best))best=t}return best}
function isExposed(target,m,attacker){if(!target.grid||!m.gridCells?.length)return true;const [ax,ay]=worldToLocal(target,attacker.x,attacker.y),dx=ax-m.x,dy=ay-m.y;for(const o of target.modules){if(o===m||o.hp<=0||!o.gridCells?.length)continue;const t=moduleRayT(target,o,m.x,m.y,dx,dy);if(t!=null&&t>1e-4&&t<1)return false}return true}
function selectTarget(attacker,target){const alive=target.modules.filter(m=>m.hp>0&&!m.disabled);for(const p of attacker.targetPriority||DEFAULT_TARGET_PRIORITY){const cs=alive.filter(m=>groupOf(m)===p&&isExposed(target,m,attacker));if(cs.length)return cs.sort((a,b)=>Math.hypot(a.x,a.y)-Math.hypot(b.x,b.y))[0]}for(const p of attacker.targetPriority||DEFAULT_TARGET_PRIORITY){const m=alive.find(x=>groupOf(x)===p);if(m)return m}return alive[0]}

export class Battle{
 constructor(a=buildBroadsideFrigate('A'),b=buildPursuitFrigate('B'),seed=1){this.rng=new RNG(seed);this.t=0;this.ships=[initialiseShip(a),initialiseShip(b)];this.projectiles=[];this.events=[];this.winner=null;Object.assign(this.ships[0],{x:-1400,y:-350,angle:.12});Object.assign(this.ships[1],{x:1400,y:350,angle:Math.PI+.1})}
 log(text){this.events.push({t:this.t,text});if(this.events.length>180)this.events.shift()}
 step(dt=G.dt){if(this.winner)return;this.t+=dt;for(const s of this.ships)if(!s.dead){s.timeAlive+=dt;this.ai(s,this.enemy(s))}for(const s of this.ships)if(!s.dead)this.applySystems(s,dt);this.updateProjectiles(dt);this.collisions();this.checkDeaths();if(this.t>240&&!this.winner){this.winner='draw';this.log('Battle ended by time limit.')}}
 enemy(s){return this.ships.find(o=>o!==s)}
 ai(s,e){if(!e||e.dead)return;const dx=e.x-s.x,dy=e.y-s.y,d=Math.hypot(dx,dy),bearing=Math.atan2(dy,dx),rvx=e.vx-s.vx,rvy=e.vy-s.vy,closing=dot(rvx,rvy,dx/d,dy/d);if(s.ai==='broadside'){const side=wrap(bearing-s.angle)>0?1:-1;s.desiredAngle=wrap(bearing-side*Math.PI/2);s.throttle=d>2300?.78:d<1100?-.25:.18;s.order=d>2300?'Close to gunnery range':d<1100?'Open the range':'Hold broadside'}else{s.desiredAngle=bearing;s.throttle=d>1900?1:d<650?-.55:.34;s.order=d<650?'Brake and avoid overshoot':Math.abs(closing)>900?'Match vector':'Keep bow on target'}}
 applySystems(s,dt){recalc(s);for(const m of s.modules){m.active=false;m.cooldownLeft=Math.max(0,(m.cooldownLeft||0)-dt)}for(const sh of aliveMods(s,'shield'))sh.charge=Math.min(sh.capacity,sh.charge+sh.recharge*dt);let powerBudget=aliveMods(s,'reactor').reduce((a,m)=>a+m.power*(m.hp/m.maxHp),0);const angleErr=wrap(s.desiredAngle-s.angle),turnCmd=clamp(angleErr*1.8-s.omega*1.4,-1,1),throttle=s.throttle;for(const eng of aliveMods(s,'engine')){if(powerBudget<eng.powerUse*.2)continue;const [dx,dy]=rot(Math.cos(eng.dir),Math.sin(eng.dir),s.angle),[rx,ry]=rot(eng.x,eng.y,s.angle),torqueSign=Math.sign(cross(rx,ry,dx,dy)),forwardness=dot(dx,dy,Math.cos(s.angle),Math.sin(s.angle));let cmd=0;if(Math.abs(torqueSign)>.1)cmd+=Math.max(0,turnCmd*torqueSign)*.72;if(throttle>=0&&forwardness>.45)cmd+=throttle;if(throttle<0&&forwardness<-.45)cmd+=-throttle;cmd=clamp(cmd,0,1);if(cmd<.03)continue;const use=eng.powerUse*cmd;if(use>powerBudget)cmd*=powerBudget/use;powerBudget-=eng.powerUse*cmd;eng.active=true;eng.output=cmd;const F=eng.force*cmd*(.45+.55*eng.hp/eng.maxHp);s.vx+=dx*F/s.mass*dt;s.vy+=dy*F/s.mass*dt;s.omega+=cross(rx,ry,dx*F,dy*F)/s.inertia*dt}s.x+=s.vx*dt;s.y+=s.vy*dt;s.angle=wrap(s.angle+s.omega*dt);this.fireWeapons(s,this.enemy(s),powerBudget)}
 fireWeapons(s,e,powerBudget){if(!e||e.dead)return;const targetMod=selectTarget(s,e),state=targetPointState(e,targetMod),dx=state.x-s.x,dy=state.y-s.y,d=len(dx,dy),bearing=Math.atan2(dy,dx);for(const w of s.modules.filter(m=>(m.type==='gun'||m.type==='laser')&&m.hp>0&&!m.disabled)){if(w.cooldownLeft>0||powerBudget<w.powerUse)continue;const aim=wrap(s.angle+(w.mountDir||0)),err=Math.abs(wrap(bearing-aim)),arc=w.type==='gun'?.32:.24;if(err>arc)continue;if(w.type==='gun'){if(w.ammo<=0)continue;const lead=interceptAngleState(s,state,w.muzzle);if(Math.abs(wrap(lead-aim))>arc)continue;const shotAng=lead+this.rng.range(-.010,.010),[mx,my]=localToWorld(s,w),rvx=Math.cos(shotAng)*w.muzzle,rvy=Math.sin(shotAng)*w.muzzle;this.projectiles.push({team:s.team,owner:s,x:mx,y:my,vx:s.vx+rvx,vy:s.vy+rvy,mass:w.projectileMass,damage:w.damage,penetration:w.penetration||1,r:1.2,ttl:G.projectileTTL,targetId:targetMod.id});const ix=-w.projectileMass*rvx,iy=-w.projectileMass*rvy;s.vx+=ix/s.mass;s.vy+=iy/s.mass;const [rx,ry]=rot(w.x,w.y,s.angle);s.omega+=cross(rx,ry,ix,iy)/s.inertia;w.ammo--;s.shots++}else{if(d>w.range)continue;this.hitRay(s,e,w.damage,'laser',{x:s.x,y:s.y,dx:state.x-s.x,dy:state.y-s.y,penetration:w.penetration||.7});s.shots++;s.hits++;const impulse=w.damage*1e6/G.c;s.vx-=Math.cos(aim)*impulse/s.mass;s.vy-=Math.sin(aim)*impulse/s.mass}w.cooldownLeft=w.cooldown;powerBudget-=w.powerUse}}
 updateProjectiles(dt){for(const p of this.projectiles){p.px=p.x;p.py=p.y;p.x+=p.vx*dt;p.y+=p.vy*dt;p.ttl-=dt}this.projectiles=this.projectiles.filter(p=>p.ttl>0&&!p.dead)}
 collisions(){for(const p of this.projectiles){for(const s of this.ships){if(s.dead||s.team===p.team)continue;const ax=p.px??p.x,ay=p.py??p.y,bx=p.x,by=p.y,abx=bx-ax,aby=by-ay,den=abx*abx+aby*aby||1,u=clamp(((s.x-ax)*abx+(s.y-ay)*aby)/den,0,1),hx=ax+abx*u,hy=ay+aby*u;if(len(hx-s.x,hy-s.y)<=s.radius){const ivx=p.mass*p.vx,ivy=p.mass*p.vy;s.vx+=ivx/s.mass;s.vy+=ivy/s.mass;s.omega+=cross(hx-s.x,hy-s.y,ivx,ivy)/s.inertia;this.hitRay(p.owner,s,p.damage,'shell',{x:ax,y:ay,dx:p.vx-s.vx,dy:p.vy-s.vy,penetration:p.penetration||1});p.owner.hits++;p.dead=true;break}}}}
 hitRay(attacker,target,damage,kind,ray){let remain=damage;const shield=aliveMods(target,'shield').find(sh=>sh.charge>0);if(shield){const absorb=Math.min(shield.charge,remain);shield.charge-=absorb;remain-=absorb;attacker.damageDone+=absorb*.15}if(remain<=0)return;if(!target.grid){this.legacyHit(attacker,target,remain,ray);return}const [ox,oy]=worldToLocal(target,ray.x,ray.y),[dx,dy]=rot(ray.dx,ray.dy,-target.angle),hits=[];for(const m of target.modules){if(m.hp<=0||!m.gridCells?.length)continue;const t=moduleRayT(target,m,ox,oy,dx,dy);if(t!=null)hits.push({m,t})}hits.sort((a,b)=>a.t-b.t);const seen=new Set();let energy=remain*(ray.penetration||1);for(const h of hits){const m=h.m;if(seen.has(m.id)||m.hp<=0)continue;seen.add(m.id);const resistance=m.type==='armor'?1.0:m.type==='hull'?.35:.62,applied=Math.min(m.hp,energy*resistance),before=m.hp;m.hp=Math.max(0,m.hp-applied);attacker.damageDone+=Math.min(before,applied);energy-=m.type==='armor'?applied/(m.absorb||.68):applied*.72;if(m.hp===0)this.moduleDestroyed(attacker,target,m);if(energy<=1)break}const keel=target.modules.find(m=>m.id==='keel');if(keel&&energy>1){const frameLoss=Math.min(keel.hp,energy*.08);keel.hp-=frameLoss;attacker.damageDone+=frameLoss}}
 legacyHit(attacker,target,remain,ray){const [lx,ly]=worldToLocal(target,ray.x,ray.y),cs=target.modules.filter(m=>m.hp>0).map(m=>({m,d:Math.hypot(m.x-lx,m.y-ly)})).sort((a,b)=>a.d-b.d),chosen=cs[0]?.m;if(!chosen)return;const before=chosen.hp;chosen.hp=Math.max(0,chosen.hp-remain);attacker.damageDone+=Math.min(before,remain);if(chosen.hp===0)this.moduleDestroyed(attacker,target,chosen)}
 moduleDestroyed(attacker,target,m){this.log(`${target.name}: ${m.id} destroyed by ${attacker.name}.`);if(m.type==='reactor'&&this.rng.next()<.18){for(const n of target.modules)if(n.hp>0&&n!==m)n.hp=Math.max(0,n.hp-220*this.rng.range(.15,.65));this.log(`${target.name}: reactor cascade damages nearby systems.`)}}
 checkDeaths(){for(const s of this.ships){if(s.dead)continue;const hull=s.modules.find(m=>m.id==='keel'),bridge=aliveMods(s,'bridge').length,reactor=aliveMods(s,'reactor').length;if(!hull||hull.hp<=0||!bridge||(!reactor&&aliveMods(s,'engine').length===0)){s.dead=true;this.log(`${s.name} is combat ineffective.`)}}const living=this.ships.filter(s=>!s.dead);if(living.length<=1){this.winner=living[0]?.team||'draw';if(living[0])living[0].kills++}}
 summary(){return{time:this.t,winner:this.winner,ships:this.ships.map(s=>({name:s.name,team:s.team,dead:s.dead,mass:s.mass,shots:s.shots,hits:s.hits,damage:s.damageDone,speed:len(s.vx,s.vy),omega:s.omega,targetPriority:s.targetPriority,modules:s.modules.map(m=>({id:m.id,type:m.type,hp:m.hp,maxHp:m.maxHp,ammo:m.ammo,charge:m.charge}))}))}}
}
export function runBattle(seed=1,maxSteps=6000){const b=new Battle(buildBroadsideFrigate('A'),buildPursuitFrigate('B'),seed);for(let i=0;i<maxSteps&&!b.winner;i++)b.step();return b.summary()}
