import {campaign,saveCampaign} from './campaign-core.js';
import {FACTIONS,SYSTEM_POWERS,relation,changeRelation} from './factions-system.js?v=77';
import {ensureStrategicFactionState,factionStrategicSummary,factionForcePlan,commitFactionForce} from './faction-strategy.js?v=98';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SYSTEMS=Object.keys(SYSTEM_POWERS);
const FRONT_DURATION=30,CEASEFIRE_DAYS=45,CONTROL_LIMIT=32;
export const STRATEGIC_MISSIONS={
 patrol:{label:'Patrol',text:'Screen the operating area, preserve freedom of movement and suppress opportunistic raids.'},
 convoyEscort:{label:'Convoy escort',text:'Protect logistics and replenishment. Lowers exhaustion and improves fleet staying power.'},
 raid:{label:'Raid',text:'Short offensive sweep against logistics and isolated traffic. Useful while a front is fluid, but deliberately bounded.'},
 blockade:{label:'Blockade',text:'Apply pressure after gaining an operational edge. Expensive to sustain and subject to strong diminishing returns.'},
 reinforce:{label:'Reinforce',text:'Concentrate locally for a threatened front. Strong short-term defence at a readiness cost.'},
 reserve:{label:'Reserve',text:'Remain available at the home base without committing to active operations.'},
 refit:{label:'Refit',text:'Withdraw for repairs, replenishment and crew recovery.'}
};
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(tag,day=campaign.day){let x=hash(`${campaign.seed||1}|${day}|${tag}`);x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}
function fresh(){return{version:2,nextFleetId:1,nextFrontId:1,lastDay:campaign.day||1,fleets:[],fronts:[],history:[]}}
function state(){campaign.strategicFronts??=fresh();const s=campaign.strategicFronts;s.fleets??=[];s.fronts??=[];s.history??=[];s.nextFleetId??=1;s.nextFrontId??=1;s.lastDay??=campaign.day||1;if((s.version||1)<2){for(const f of s.fleets){f.mission??=(f.status==='refitting'?'refit':f.status==='reserve'?'reserve':'patrol');f.missionSince??=campaign.day;f.missionUntil??=campaign.day+4} s.version=2}return s}
function log(text){const s=state();s.history.push({day:campaign.day,text});s.history=s.history.slice(-100);campaign.log??=[];campaign.log.push(`Day ${campaign.day}: STRATEGIC FRONT — ${text}`);campaign.log=campaign.log.slice(-140)}
function presence(system,id){return campaign.factionPresence?.[system]?.[id]??(SYSTEM_POWERS[system]||[]).find(x=>x.id===id)?.presence??0}
function basePresence(system,id){return(SYSTEM_POWERS[system]||[]).find(x=>x.id===id)?.presence??0}
function frontBetween(a,b,system){return state().fronts.find(f=>f.system===system&&((f.a===a&&f.b===b)||(f.a===b&&f.b===a))&&['active','ceasefire'].includes(f.status))}
function objectiveFor(a,b){const ka=FACTIONS[a]?.kind,kb=FACTIONS[b]?.kind;if(FACTIONS[a]?.lawful!==FACTIONS[b]?.lawful)return'security';if(ka==='government'&&kb==='government')return'limited-pressure';return'interdiction'}
function travelDays(id,system,n){return FACTIONS[id]?.home===system?0:3+Math.floor(rnd(`travel:${id}:${system}:${n}`)*5)}
function fleetStrength(plan){return clamp(18+(plan.count||1)*18+(plan.maxClass||1)*8,28,100)}
function setMission(f,mission,day,target=null,minDays=3,maxDays=6){if(!STRATEGIC_MISSIONS[mission])mission='patrol';const changed=f.mission!==mission||f.missionTarget!==target;f.mission=mission;f.missionTarget=target;f.missionSince=day;f.missionUntil=day+minDays+Math.floor(rnd(`mission-duration:${f.id}:${mission}`,day)*Math.max(1,maxDays-minDays+1));if(changed)log(`${FACTIONS[f.factionId]?.short||f.factionId} task force ${f.id} switches to ${STRATEGIC_MISSIONS[mission].label.toLowerCase()}${target?` around ${target}`:''}.`)}
function reusableReserve(id){return state().fleets.filter(f=>f.factionId===id&&f.status==='reserve'&&!f.frontId).sort((a,b)=>(b.strength*b.readiness)-(a.strength*a.readiness))[0]||null}
function createFleet(id,system,frontId,role){const s=state();let f=reusableReserve(id);if(f){const t=travelDays(id,system,`${f.id}:reuse:${campaign.day}`);f.frontId=frontId;f.role=role;f.destination=system;f.etaDay=campaign.day+t;f.status=t?'enroute':'deployed';setMission(f,t?'reinforce':role==='defend'?'patrol':'raid',campaign.day,system,3,5);log(`${FACTIONS[id].short} recommits existing task force ${f.id} from reserve to ${system}.`);return f}const n=s.nextFleetId++,plan=factionForcePlan(id,FACTIONS[id]?.home||system,2,role==='defend'?'defence':'general');if((plan.count||0)<1)return null;commitFactionForce(id,plan);const t=travelDays(id,system,n),str=fleetStrength(plan);f={id:`SF${n}`,factionId:id,frontId,role,origin:FACTIONS[id]?.home||system,system:t?FACTIONS[id]?.home||system:system,destination:system,etaDay:campaign.day+t,status:t?'enroute':'deployed',strength:str,maxStrength:str,readiness:88,damage:0,shipCount:plan.count,maxClass:plan.maxClass,createdDay:campaign.day,lastDay:campaign.day,mission:t?'reinforce':role==='defend'?'patrol':'raid',missionTarget:system,missionSince:campaign.day,missionUntil:campaign.day+4};s.fleets.push(f);return f}
export function createStrategicFront(a,b,system,objective=objectiveFor(a,b)){if(!FACTIONS[a]||!FACTIONS[b]||a===b||!SYSTEMS.includes(system))return{ok:false,reason:'Invalid front participants or system.'};if(frontBetween(a,b,system))return{ok:false,reason:'A front or ceasefire already exists here.'};const s=state(),id=`FR${s.nextFrontId++}`,f={id,a,b,system,objective,status:'active',startedDay:campaign.day,lastDay:campaign.day,control:0,exhaustion:{[a]:0,[b]:0},playerContribution:{[a]:0,[b]:0},winner:null,endsBy:campaign.day+FRONT_DURATION,ceasefireUntil:null,history:[]};s.fronts.push(f);createFleet(a,system,id,'attack');createFleet(b,system,id,'defend');log(`${FACTIONS[a].short} and ${FACTIONS[b].short} enter a limited ${objective} front in ${system}. The objective is bounded; neither side can destroy or annex the other through this front.`);saveCampaign(campaign);return{ok:true,front:f}}
function seedFronts(){const s=state();if(s.seeded)return;s.seeded=true;const candidates=[];for(const system of SYSTEMS){const ids=Object.keys(FACTIONS).filter(id=>presence(system,id)>.08);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const a=ids[i],b=ids[j],r=relation(a,b);if(r>-46)continue;if(FACTIONS[a].lawful&&FACTIONS[b].lawful&&r>-72)continue;candidates.push({a,b,system,score:-r+Math.min(presence(system,a),presence(system,b))*30})}}candidates.sort((x,y)=>y.score-x.score);for(const c of candidates.slice(0,3))if(!frontBetween(c.a,c.b,c.system))createStrategicFront(c.a,c.b,c.system);saveCampaign(campaign)}
function sideFleet(front,id){return state().fleets.find(f=>f.frontId===front.id&&f.factionId===id&&f.status!=='retired')}
function enemyOf(front,id){return front.a===id?front.b:front.a}
function leadFor(front,id){return front.a===id?front.control:-front.control}
function missionBias(f,front,day){const id=f.factionId,enemy=enemyOf(front,id),lead=leadFor(front,id),ownEx=front.exhaustion[id]||0,enemyEx=front.exhaustion[enemy]||0,fs=factionStrategicSummary(id,front.system),kind=FACTIONS[id]?.kind;if(f.damage>55||f.readiness<36)return'refit';if(fs?.posture==='critical'||ownEx>62)return'convoyEscort';if(lead<-12)return'reinforce';if(lead>16)return ownEx>45?'convoyEscort':'patrol';if(f.role==='defend'&&lead<2)return rnd(`mission:${f.id}:def:${day}`,day)<.55?'patrol':'reinforce';if(kind==='pirate')return rnd(`mission:${f.id}:pirate:${day}`,day)<.65?'raid':'patrol';if(kind==='merchant'||kind==='industrial')return rnd(`mission:${f.id}:trade:${day}`,day)<.62?'convoyEscort':'patrol';if(lead>5&&enemyEx<60&&f.readiness>58)return rnd(`mission:${f.id}:pressure:${day}`,day)<.42?'blockade':'raid';return rnd(`mission:${f.id}:general:${day}`,day)<.45?'raid':'patrol'}
function assignFleetMission(f,front,day,force=false){if(!f||f.status==='refitting'){if(f)setMission(f,'refit',day,f.origin,3,6);return}if(f.status==='reserve'){setMission(f,'reserve',day,f.origin,4,8);return}if(!front||front.status!=='active'){if(f.status==='deployed')setMission(f,'patrol',day,f.system,4,7);return}if(!force&&f.missionUntil&&day<f.missionUntil)return;const mission=missionBias(f,front,day);if(mission==='refit'){f.status='refitting';f.destination=f.origin;f.etaDay=day+4+Math.floor(rnd(`mission-refit:${f.id}`,day)*5);setMission(f,'refit',day,f.origin,4,7);return}setMission(f,mission,day,front.system,3,6)}
function missionStrengthMultiplier(f,front){switch(f.mission){case'reinforce':return 1.16;case'patrol':return f.role==='defend'?1.08:1.03;case'convoyEscort':return 1.01;case'raid':return 1.04;case'blockade':return leadFor(front,f.factionId)>0?1.05:.92;default:return 1}}
function fleetEffective(f,front,side){if(!f||f.status!=='deployed')return 0;const home=FACTIONS[f.factionId]?.home===front.system;let x=f.strength*(f.readiness/100)*(1-f.damage/130)*missionStrengthMultiplier(f,front);if(side==='defend')x*=1.12;if(home)x*=1.12;const own=presence(front.system,f.factionId),enemy=presence(front.system,enemyOf(front,f.factionId));if(own<enemy)x*=1+clamp((enemy-own)*.25,0,.18);return x}
function updateFleetTravel(f,day){if(f.status==='enroute'&&day>=f.etaDay){f.system=f.destination;f.status='deployed';f.lastDay=day;const front=state().fronts.find(x=>x.id===f.frontId);assignFleetMission(f,front,day,true);log(`${FACTIONS[f.factionId].short} task force ${f.id} reaches ${f.system}.`)}else if(f.status==='refitting'&&day>=f.etaDay){f.system=f.origin;f.destination=f.frontId?state().fronts.find(x=>x.id===f.frontId)?.system:f.origin;f.strength=Math.min(f.maxStrength,f.strength+Math.max(12,f.maxStrength*.28));f.readiness=Math.min(92,f.readiness+28);f.damage=Math.max(0,f.damage-35);if(f.frontId&&state().fronts.find(x=>x.id===f.frontId)?.status==='active'){f.etaDay=day+travelDays(f.factionId,f.destination,`${f.id}:${day}`);f.status=f.etaDay===day?'deployed':'enroute';setMission(f,'reinforce',day,f.destination,3,5)}else{f.status='reserve';setMission(f,'reserve',day,f.origin,4,8)}f.lastDay=day}}
function applyFleetAttrition(f,loss){if(!f||loss<=0)return;const capped=Math.min(loss,f.maxStrength*.075);f.strength=Math.max(f.maxStrength*.18,f.strength-capped);f.readiness=clamp(f.readiness-capped*.45,20,100);f.damage=clamp(f.damage+capped*.38,0,85);const fs=campaign.factions?.[f.factionId];if(fs){fs.military=Math.max(8,(fs.military||0)-capped*.025);fs.readiness=Math.max(12,(fs.readiness||0)-capped*.035)}if(f.strength<=f.maxStrength*.26||f.readiness<30){f.status='refitting';f.destination=f.origin;f.etaDay=campaign.day+4+Math.floor(rnd(`refit:${f.id}:${campaign.day}`)*5);setMission(f,'refit',campaign.day,f.origin,4,7);log(`${FACTIONS[f.factionId].short} task force ${f.id} disengages to refit rather than fight to destruction.`)}}
export function persistentFleetFor(factionId,system=campaign.location){seedFronts();return state().fleets.filter(f=>f.factionId===factionId&&f.system===system&&f.status==='deployed').sort((a,b)=>b.strength-a.strength)[0]||null}
export function applyPersistentFleetBattleLoss(fleetId,weight=1){const f=state().fleets.find(x=>x.id===fleetId);if(!f)return null;applyFleetAttrition(f,Math.max(0,weight)*2.2);saveCampaign(campaign);return f}
function resilience(id){const st=campaign.factions?.[id]||{},low=Math.max(0,22-(st.military||0));return 1+low*.025+(st.posture==='critical'?.18:0)+(st.posture==='defensive'?.08:0)}
function applyMissionEffects(front,f,enemy,day){if(!f||f.status!=='deployed')return 0;const id=f.factionId,other=enemyOf(front,id),lead=leadFor(front,id),ownEx=front.exhaustion[id]||0;let edge=0;if(f.mission==='convoyEscort'){front.exhaustion[id]=Math.max(0,ownEx-.28);f.readiness=clamp(f.readiness+.18,20,100)}else if(f.mission==='reinforce'){edge+=.055;f.readiness=clamp(f.readiness-.22,20,100);front.exhaustion[id]=clamp(ownEx+.08,0,100)}else if(f.mission==='raid'){const brake=lead>12?.45:1,success=clamp(.34+(f.readiness-(enemy?.readiness||60))/180,0.18,.62)*brake;front.exhaustion[other]=clamp((front.exhaustion[other]||0)+success*.22,0,100);edge+=success*.032;f.readiness=clamp(f.readiness-.12,20,100)}else if(f.mission==='blockade'){const allowed=lead>3?1:0,brake=clamp(1-Math.max(0,lead-8)/22,.18,1),pressure=allowed*brake*clamp(f.readiness/80,.45,1);front.exhaustion[other]=clamp((front.exhaustion[other]||0)+pressure*.30,0,100);front.exhaustion[id]=clamp(ownEx+pressure*.13,0,100);f.readiness=clamp(f.readiness-pressure*.18,20,100);edge+=pressure*.038}else if(f.mission==='patrol'){f.readiness=clamp(f.readiness+.035,20,100)}return clamp(edge,-.08,.08)}
function stepFront(front,day){if(front.status==='ceasefire'){if(day>=front.ceasefireUntil){front.status='resolved';for(const f of state().fleets.filter(x=>x.frontId===front.id&&x.status!=='retired')){f.frontId=null;f.status='reserve';f.system=f.origin;f.destination=f.origin;setMission(f,'reserve',day,f.origin,4,8)}log(`${FACTIONS[front.a].short}–${FACTIONS[front.b].short} ceasefire at ${front.system} settles into a cold front.`)}return}if(front.status!=='active')return;front.lastDay=day;const fa=sideFleet(front,front.a),fb=sideFleet(front,front.b);assignFleetMission(fa,front,day);assignFleetMission(fb,front,day);const ea=fleetEffective(fa,front,'attack')*resilience(front.a),eb=fleetEffective(fb,front,'defend')*resilience(front.b);if(ea<=0||eb<=0)return;const edge=(ea-eb)/Math.max(1,ea+eb),diminish=1-Math.min(.8,Math.abs(front.control)/CONTROL_LIMIT*.78),pa=clamp(front.playerContribution[front.a]||0,0,6),pb=clamp(front.playerContribution[front.b]||0,0,6),playerEdge=(pa-pb)*.022,missionEdge=applyMissionEffects(front,fa,fb,day)-applyMissionEffects(front,fb,fa,day),drift=clamp((edge+playerEdge+missionEdge)*3.2*diminish,-1.6,1.6);front.control=clamp(front.control+drift,-CONTROL_LIMIT,CONTROL_LIMIT);front.playerContribution[front.a]=pa*.72;front.playerContribution[front.b]=pb*.72;const intensity=.65+Math.abs(edge)*.6;applyFleetAttrition(fa,intensity*(.8-edge*.55));applyFleetAttrition(fb,intensity*(.8+edge*.55));front.exhaustion[front.a]=clamp((front.exhaustion[front.a]||0)+.65+Math.max(0,edge)*.55+(front.control>12?.35:0),0,100);front.exhaustion[front.b]=clamp((front.exhaustion[front.b]||0)+.65+Math.max(0,-edge)*.55+(front.control<-12?.35:0),0,100);if(Math.abs(front.control)>=CONTROL_LIMIT*.92||day>=front.endsBy||Math.max(front.exhaustion[front.a],front.exhaustion[front.b])>=72)resolveFront(front,front.control>4?front.a:front.control<-4?front.b:null,day)}
function resolveFront(front,winner,day=campaign.day){front.status='ceasefire';front.winner=winner;front.ceasefireUntil=day+CEASEFIRE_DAYS;const loser=winner?(winner===front.a?front.b:front.a):null;if(winner&&loser){campaign.factionPresence??={};campaign.factionPresence[front.system]??={};const wp=presence(front.system,winner),lp=presence(front.system,loser),wb=basePresence(front.system,winner),lb=basePresence(front.system,loser);campaign.factionPresence[front.system][winner]=clamp(wp+.045,Math.max(0,wb*.35),Math.max(wb+.12,.18));campaign.factionPresence[front.system][loser]=clamp(lp-.045,Math.max(.04,lb*.35),Math.max(lb+.12,.18));changeRelation(winner,loser,-2);log(`${FACTIONS[winner].short} gains a limited operational advantage over ${FACTIONS[loser].short} in ${front.system}. Presence shifts modestly; no territory or faction is eliminated. A ${CEASEFIRE_DAYS}-day ceasefire begins.`)}else log(`${FACTIONS[front.a].short} and ${FACTIONS[front.b].short} exhaust the ${front.system} front without a decisive result. A ${CEASEFIRE_DAYS}-day ceasefire begins.`);for(const f of state().fleets.filter(x=>x.frontId===front.id)){if(f.status==='deployed'){f.status='refitting';f.destination=f.origin;f.etaDay=day+3+Math.floor(rnd(`postfront:${f.id}`,day)*5);setMission(f,'refit',day,f.origin,3,6)}}}
function recoverFactions(){ensureStrategicFactionState();for(const [id,s] of Object.entries(campaign.factions||{})){const floor=FACTIONS[id]?.lawful?10:8;if((s.military||0)<floor)s.military=Math.min(floor,s.military+.18);if((s.power||0)<10)s.power=Math.min(10,s.power+.10);if(s.status==='fragmented')s.status='reduced'}}
export function recordPlayerFrontContribution(frontId,factionId,points=1){const f=state().fronts.find(x=>x.id===frontId&&x.status==='active');if(!f||![f.a,f.b].includes(factionId))return{ok:false,reason:'No active front for that faction.'};const before=f.playerContribution[factionId]||0;f.playerContribution[factionId]=clamp(before+Math.max(0,points),0,6);saveCampaign(campaign);return{ok:true,accepted:f.playerContribution[factionId]-before,cap:6}}
export function setStrategicFleetMission(fleetId,mission){const f=state().fleets.find(x=>x.id===fleetId);if(!f)return{ok:false,reason:'Unknown strategic fleet.'};if(!STRATEGIC_MISSIONS[mission])return{ok:false,reason:'Unknown mission.'};const front=state().fronts.find(x=>x.id===f.frontId);if(['raid','blockade','reinforce','convoyEscort'].includes(mission)&&(!front||front.status!=='active'))return{ok:false,reason:'That mission requires an active front.'};if(mission==='blockade'&&leadFor(front,f.factionId)<=0)return{ok:false,reason:'A blockade requires at least a small operational advantage.'};if(mission==='refit'){f.status='refitting';f.destination=f.origin;f.etaDay=campaign.day+4+Math.floor(rnd(`manual-refit:${f.id}`,campaign.day)*5)}setMission(f,mission,campaign.day,front?.system||f.origin,3,6);saveCampaign(campaign);return{ok:true,fleet:f}}
export function advanceStrategicFronts(targetDay=campaign.day){seedFronts();const s=state(),end=Math.floor(targetDay||campaign.day);let d=s.lastDay||end,steps=0;while(d<end&&steps<180){d++;for(const f of s.fleets)updateFleetTravel(f,d);for(const front of s.fronts)stepFront(front,d);for(const f of s.fleets.filter(x=>!x.frontId&&x.status==='reserve'))assignFleetMission(f,null,d);recoverFactions();steps++}s.lastDay=end;if(steps)saveCampaign(campaign);return steps}
export function strategicFrontSummary(){seedFronts();advanceStrategicFronts(campaign.day);const s=state();return{missions:STRATEGIC_MISSIONS,fronts:s.fronts.map(f=>({...f,aName:FACTIONS[f.a]?.short||f.a,bName:FACTIONS[f.b]?.short||f.b,fleets:s.fleets.filter(x=>x.frontId===f.id).map(x=>({...x,factionName:FACTIONS[x.factionId]?.short||x.factionId,missionLabel:STRATEGIC_MISSIONS[x.mission]?.label||x.mission}))})),fleets:s.fleets.map(f=>({...f,factionName:FACTIONS[f.factionId]?.short||f.factionId,missionLabel:STRATEGIC_MISSIONS[f.mission]?.label||f.mission})),history:[...s.history]}}
seedFronts();advanceStrategicFronts(campaign.day);
if(typeof window!=='undefined'){window.__strategicFronts={createStrategicFront,advanceStrategicFronts,strategicFrontSummary,recordPlayerFrontContribution,persistentFleetFor,applyPersistentFleetBattleLoss,setStrategicFleetMission,STRATEGIC_MISSIONS};setInterval(()=>advanceStrategicFronts(campaign.day),1500)}