import {campaign,saveCampaign} from './campaign-core.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const GOODS=['machinery','food','metals','medicine','luxuries','restricted'];
const BASE={
 'Sol Gateway':{industry:1.12,market:1,stocks:{machinery:78,food:72,metals:74,medicine:86,luxuries:70,restricted:54},prod:{machinery:4.8,food:3.5,metals:3.8,medicine:5.2,luxuries:3.2,restricted:1.8},demand:{machinery:3.5,food:4.2,metals:3.2,medicine:3.2,luxuries:2.6,restricted:1.6}},
 'Haven Reach':{industry:.96,market:.9,stocks:{machinery:72,food:74,metals:65,medicine:72,luxuries:60,restricted:45},prod:{machinery:4.3,food:4.5,metals:3.2,medicine:3.4,luxuries:2.5,restricted:1.0},demand:{machinery:3.8,food:4.1,metals:3.3,medicine:3.1,luxuries:2.4,restricted:1.3}},
 'Pelagos':{industry:.94,market:1,stocks:{machinery:66,food:68,metals:60,medicine:64,luxuries:88,restricted:52},prod:{machinery:3.7,food:3.9,metals:2.8,medicine:2.6,luxuries:6.0,restricted:1.2},demand:{machinery:4.0,food:4.5,metals:3.5,medicine:3.3,luxuries:2.0,restricted:1.5}},
 'Kestrel':{industry:.68,market:.52,stocks:{machinery:38,food:58,metals:76,medicine:36,luxuries:34,restricted:30},prod:{machinery:1.7,food:3.9,metals:5.6,medicine:1.1,luxuries:1.0,restricted:.6},demand:{machinery:4.5,food:3.7,metals:2.4,medicine:3.5,luxuries:1.5,restricted:1.0}},
 'Nadir':{industry:.5,market:.5,stocks:{machinery:34,food:42,metals:54,medicine:32,luxuries:42,restricted:72},prod:{machinery:1.2,food:2.5,metals:3.4,medicine:.8,luxuries:1.2,restricted:3.2},demand:{machinery:3.3,food:3.8,metals:2.6,medicine:3.0,luxuries:1.2,restricted:1.4}},
 'Lacuna Reach':{industry:.22,market:.15,stocks:{machinery:28,food:46,metals:34,medicine:24,luxuries:12,restricted:18},prod:{machinery:.5,food:1.6,metals:.7,medicine:.3,luxuries:.1,restricted:.2},demand:{machinery:1.8,food:1.7,metals:1.3,medicine:1.2,luxuries:.2,restricted:.4}},
 'Peregrine':{industry:.58,market:.25,stocks:{machinery:48,food:74,metals:46,medicine:52,luxuries:24,restricted:44},prod:{machinery:2.2,food:3.6,metals:1.8,medicine:1.8,luxuries:.5,restricted:1.5},demand:{machinery:2.5,food:2.8,metals:2.1,medicine:1.7,luxuries:.5,restricted:.9}}
};
function fresh(){return{version:1,lastDay:campaign.day||1,nodes:{},history:[]}}
function state(){campaign.strategicEconomy??=fresh();const s=campaign.strategicEconomy;s.nodes??={};s.history??=[];s.lastDay??=campaign.day||1;for(const [system,b] of Object.entries(BASE)){if(!s.nodes[system])s.nodes[system]={system,stocks:{...b.stocks},industrialOutput:b.industry,tradeSecurity:1,shortages:[],lastDay:campaign.day||1};for(const g of GOODS)if(!Number.isFinite(s.nodes[system].stocks[g]))s.nodes[system].stocks[g]=b.stocks[g]??50}return s}
function log(text){const s=state();s.history.push({day:campaign.day,text});s.history=s.history.slice(-100);campaign.log??=[];campaign.log.push(`Day ${campaign.day}: ECONOMY — ${text}`);campaign.log=campaign.log.slice(-180)}
function blockadePressure(system){let p=0;for(const front of campaign.strategicFronts?.fronts||[]){if(front.status!=='active'||front.system!==system)continue;for(const f of campaign.strategicFronts?.fleets||[]){if(f.frontId!==front.id||f.status!=='deployed')continue;if(f.mission==='blockade')p+=.22*(f.readiness||60)/100;if(f.mission==='raid')p+=.07*(f.readiness||60)/100}}return clamp(p,0,.6)}
function tradeSecurity(system){const edges=campaign.strategicLogistics?.lastEdges||null;let vals=[];if(edges)vals=edges.filter(e=>e.a===system||e.b===system).map(e=>e.reliability);if(!vals.length){const node=campaign.strategicLogistics?.nodes?.[system],d=node?.disruption||0;return clamp(.96-d/130-blockadePressure(system),.18,1)}return clamp(vals.reduce((a,b)=>a+b,0)/vals.length-blockadePressure(system)*.35,.15,1)}
function logisticsSecurity(system){const node=campaign.strategicLogistics?.nodes?.[system],d=node?.disruption||0;return clamp((1-d/120)*tradeSecurity(system),.12,1)}
function economicOutput(system,node){const b=BASE[system],mach=node.stocks.machinery??50,met=node.stocks.metals??50,food=node.stocks.food??50,security=logisticsSecurity(system);return clamp(b.industry*(.52+.48*security)*(.62+.38*clamp(mach/55,.25,1.25))*(.78+.22*clamp(met/55,.3,1.2))*(.88+.12*clamp(food/50,.35,1.2)),.18,1.18)}
function importFlow(system,good,node,security){const b=BASE[system],stock=node.stocks[good]??50,need=Math.max(0,(b.demand[good]||1)-(b.prod[good]||0));const scarcity=clamp((60-stock)/45,0,1.2);return need*security*(.65+b.market*.55)+scarcity*security*(.55+b.market*.65)}
function exportDrain(system,good,node,security){const b=BASE[system],stock=node.stocks[good]??50,surplus=Math.max(0,(b.prod[good]||0)-(b.demand[good]||0));return surplus*security*clamp((stock-55)/45,0,.8)}
function stepSystem(system,node){const b=BASE[system],security=tradeSecurity(system),output=economicOutput(system,node),before=new Set(node.shortages||[]);for(const g of GOODS){const prod=(b.prod[g]||0)*output,demand=(b.demand[g]||0)*(1+blockadePressure(system)*.08),imports=importFlow(system,g,node,security),exports=exportDrain(system,g,node,security);node.stocks[g]=clamp((node.stocks[g]??50)+prod+imports-demand-exports,0,100)}node.tradeSecurity=security;node.industrialOutput=economicOutput(system,node);node.shortages=GOODS.filter(g=>(node.stocks[g]??50)<25);node.lastDay=campaign.day;const after=new Set(node.shortages);for(const g of after)if(!before.has(g))log(`${system} reports a shortage of ${g}.`);for(const g of before)if(!after.has(g))log(`${system} shortage of ${g} eases as production or imports recover.`)}
function nudgeFactionWealth(){for(const [id,fs] of Object.entries(campaign.factions||{})){let num=0,den=0;for(const [system,node] of Object.entries(state().nodes)){const p=campaign.factionPresence?.[system]?.[id]||0;if(p<=.02)continue;num+=node.industrialOutput*node.tradeSecurity*p;den+=p}if(!den)continue;const health=num/den,delta=clamp((health-.72)*.055,-.025,.025);fs.wealth=clamp((fs.wealth??20)+delta,8,100)}}
function stepDay(){for(const [system,node] of Object.entries(state().nodes))stepSystem(system,node);nudgeFactionWealth()}
export function advanceStrategicEconomy(targetDay=campaign.day){const s=state();let d=Math.floor(s.lastDay||targetDay),end=Math.max(d,Math.floor(targetDay||d)),steps=0;while(d<end&&steps<365){d++;stepDay();s.lastDay=d;steps++}if(steps)saveCampaign(campaign);return steps}
export function marketModifier(good,system){advanceStrategicEconomy(campaign.day);const n=state().nodes[system],b=BASE[system];if(!n||!b)return 1;const stock=n.stocks[good]??50,scarcity=clamp((55-stock)/45,-.45,1.1),securityPenalty=(1-n.tradeSecurity)*.55,blockade=blockadePressure(system)*.35;return clamp(1+scarcity*.72+securityPenalty+blockade,.58,2.45)}
export function marketAvailable(good,system=campaign.location){advanceStrategicEconomy(campaign.day);const n=state().nodes[system],b=BASE[system];if(!n||!b||!GOODS.includes(good))return 0;const stock=n.stocks[good]??0;return Math.max(0,Math.floor(stock*(.08+b.market*.08)))}
export function recordMarketTrade(good,qty,buy,system=campaign.location){const n=state().nodes[system];if(!n||!GOODS.includes(good))return;const impact=Math.max(0,qty)*.35;n.stocks[good]=clamp((n.stocks[good]??50)+(buy?-impact:impact),0,100);n.shortages=GOODS.filter(g=>(n.stocks[g]??50)<25);saveCampaign(campaign)}
export function economyNode(system=campaign.location){advanceStrategicEconomy(campaign.day);const n=state().nodes[system];return n?{...n,stocks:{...n.stocks}}:null}
export function economySummary(){advanceStrategicEconomy(campaign.day);const s=state();return{day:campaign.day,nodes:Object.values(s.nodes).map(n=>({...n,stocks:{...n.stocks}})),history:[...s.history]}}

advanceStrategicEconomy(campaign.day);
if(typeof window!=='undefined'){window.__strategicEconomy={economySummary,economyNode,marketModifier,marketAvailable,recordMarketTrade,advanceStrategicEconomy};setInterval(()=>advanceStrategicEconomy(campaign.day),1150)}
