import {campaign,saveCampaign} from './campaign-core.js';
import {FACTIONS,SYSTEM_POWERS,relation,changeRelation} from './factions-system.js?v=77';
import {ensureStrategicFactionState,factionStrategicSummary,factionForcePlan,commitFactionForce} from './faction-strategy.js?v=98';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SYSTEMS=Object.keys(SYSTEM_POWERS);
const FRONT_DURATION=30,CEASEFIRE_DAYS=45,CONTROL_LIMIT=32;
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(tag,day=campaign.day){let x=hash(`${campaign.seed||1}|${day}|${tag}`);x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}
function fresh(){return{version:1,nextFleetId:1,nextFrontId:1,lastDay:campaign.day||1,fleets:[],fronts:[],history:[]}}
function state(){campaign.strategicFronts??=fresh();const s=campaign.strategicFronts;s.fleets??=[];s.fronts??=[];s.history??=[];s.nextFleetId??=1;s.nextFrontId??=1;s.lastDay??=campaign.day||1;return s}
function log(text){const s=state();s.history.push({day:campaign.day,text});s.history=s.history.slice(-80);campaign.log??=[];campaign.log.push(`Day ${campaign.day}: STRATEGIC FRONT — ${text}`);campaign.log=campaign.log.slice(-120)}
function presence(system,id){return campaign.factionPresence?.[system]?.[id]??(SYSTEM_POWERS[system]||[]).find(x=>x.id===id)?.presence??0}
function basePresence(system,id){return(SYSTEM_POWERS[system]||[]).find(x=>x.id===id)?.presence??0}
function frontBetween(a,b,system){return state().fronts.find(f=>f.system===system&&((f.a===a&&f.b===b)||(f.a===b&&f.b===a))&&['active','ceasefire'].includes(f.status))}
function objectiveFor(a,b){const ka=FACTIONS[a]?.kind,kb=FACTIONS[b]?.kind;if(FACTIONS[a]?.lawful!==FACTIONS[b]?.lawful)return 'security';if(ka==='government'&&kb==='government')return'limited-pressure';return'interdiction'}
function travelDays(id,system,n){const home=FACTIONS[id]?.home;return home===system?0:3+Math.floor(rnd(`travel:${id}:${system}:${n}`)*5)}
function fleetStrength(plan){return clamp(18+(plan.count||1)*18+(plan.maxClass||1)*8,28,100)}
function createFleet(id,system,frontId,role){const s=state(),n=s.nextFleetId++,plan=factionForcePlan(id,FACTIONS[id]?.home||system,2,role==='defend'?'defence':'general');if((plan.count||0)<1)return null;commitFactionForce(id,plan);const t=travelDays(id,system,n),str=fleetStrength(plan),f={id:`SF${n}`,factionId:id,frontId,role,origin:FACTIONS[id]?.home||system,system:t?FACTIONS[id]?.home||system:system,destination:system,etaDay:campaign.day+t,status:t?'enroute':'deployed',strength:str,maxStrength:str,readiness:88,damage:0,shipCount:plan.count,maxClass:plan.maxClass,createdDay:campaign.day,lastDay:campaign.day};s.fleets.push(f);return f}
export function createStrategicFront(a,b,system,objective=objectiveFor(a,b)){if(!FACTIONS[a]||!FACTIONS[b]||a===b||!SYSTEMS.includes(system))return{ok:false,reason:'Invalid front participants or system.'};if(frontBetween(a,b,system))return{ok:false,reason:'A front or ceasefire already exists here.'};const s=state(),id=`FR${s.nextFrontId++}`,f={id,a,b,system,objective,status:'active',startedDay:campaign.day,lastDay:campaign.day,control:0,exhaustion:{[a]:0,[b]:0},playerContribution:{[a]:0,[b]:0},winner:null,endsBy:campaign.day+FRONT_DURATION,ceasefireUntil:null,history:[]};s.fronts.push(f);createFleet(a,system,id,'attack');createFleet(b,system,id,'defend');log(`${FACTIONS[a].short} and ${FACTIONS[b].short} enter a limited ${objective} front in ${system}. The objective is bounded; neither side can destroy or annex the other through this front.`);saveCampaign(campaign);return{ok:true,front:f}}
function seedFronts(){const s=state();if(s.seeded)return;s.seeded=true;const candidates=[];for(const system of SYSTEMS){const ids=Object.keys(FACTIONS).filter(id=>presence(system,id)>.08);for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const a=ids[i],b=ids[j],r=relation(a,b);if(r>-46)continue;if(FACTIONS[a].lawful&&FACTIONS[b].lawful&&r>-72)continue;const score=-r+Math.min(presence(system,a),presence(system,b))*30;candidates.push({a,b,system,score})}}candidates.sort((x,y)=>y.score-x.score);for(const c of candidates.slice(0,3))if(!frontBetween(c.a,c.b,c.system))createStrategicFront(c.a,c.b,c.system);saveCampaign(campaign)}
function fleetEffective(f,front,side){if(!f||f.status!=='deployed')return 0;const fs=factionStrategicSummary(f.factionId,front.system),home=FACTIONS[f.factionId]?.home===front.system;let x=f.strength*(f.readiness/100)*(1-f.damage/130);if(side==='defend')x*=1.12;if(home)x*=1.12;const own=presence(front.system,f.factionId),enemy=presence(front.system,f.factionId===front.a?front.b:front.a);if(own<enemy)x*=1+clamp((enemy-own)*.25,0,.18);return x}
function sideFleet(front,id){return state().fleets.find(f=>f.frontId===front.id&&f.factionId===id&&!['retired'].includes(f.status))}
function updateFleetTravel(f,day){if(f.status==='enroute'&&day>=f.etaDay){f.system=f.destination;f.status='deployed';f.lastDay=day;log(`${FACTIONS[f.factionId].short} task force ${f.id} reaches ${f.system}.`)}else if(f.status==='refitting'&&day>=f.etaDay){f.system=f.origin;f.destination=f.frontId?state().fronts.find(x=>x.id===f.frontId)?.system:f.origin;f.strength=Math.min(f.maxStrength,f.strength+Math.max(12,f.maxStrength*.28));f.readiness=Math.min(92,f.readiness+28);f.damage=Math.max(0,f.damage-35);if(f.frontId&&state().fronts.find(x=>x.id===f.frontId)?.status==='active'){f.etaDay=day+travelDays(f.factionId,f.destination,f.id+day);f.status=f.etaDay===day?'deployed':'enroute'}else f.status='reserve';f.lastDay=day}}
function applyFleetAttrition(f,loss){if(!f||loss<=0)return;const capped=Math.min(loss,f.maxStrength*.075);f.strength=Math.max(f.maxStrength*.18,f.strength-capped);f.readiness=clamp(f.readiness-capped*.45,20,100);f.damage=clamp(f.damage+capped*.38,0,85);const fs=campaign.factions?.[f.factionId];if(fs){fs.military=Math.max(8,(fs.military||0)-capped*.025);fs.readiness=Math.max(12,(fs.readiness||0)-capped*.035)}if(f.strength<=f.maxStrength*.26||f.readiness<30){f.status='refitting';f.destination=f.origin;f.etaDay=campaign.day+4+Math.floor(rnd(`refit:${f.id}:${campaign.day}`)*5);log(`${FACTIONS[f.factionId].short} task force ${f.id} disengages to refit rather than fight to destruction.`)}}
function resilience(id){const st=campaign.factions?.[id]||{},base=FACTIONS[id]?.kind==='government'?14:10;const low=Math.max(0,22-(st.military||0));return 1+low*.025+(st.posture==='critical'?.18:0)+(st.posture==='defensive'?.08:0)+base*.002}
function stepFront(front,day){if(front.status==='ceasefire'){if(day>=front.ceasefireUntil){front.status='resolved';for(const f of state().fleets.filter(x=>x.frontId===front.id&&!['retired'].includes(x.status))){f.frontId=null;f.status='reserve';f.system=f.origin;f.destination=f.origin}log(`${FACTIONS[front.a].short}–${FACTIONS[front.b].short} ceasefire at ${front.system} settles into a cold front.`)}return}if(front.status!=='active')return;front.lastDay=day;for(const f of state().fleets.filter(x=>x.frontId===front.id))updateFleetTravel(f,day);const fa=sideFleet(front,front.a),fb=sideFleet(front,front.b),ea=fleetEffective(fa,front,'attack')*resilience(front.a),eb=fleetEffective(fb,front,'defend')*resilience(front.b);if(ea<=0||eb<=0)return;const total=ea+eb,edge=(ea-eb)/Math.max(1,total),diminish=1-Math.min(.8,Math.abs(front.control)/CONTROL_LIMIT*.78);const pa=clamp(front.playerContribution[front.a]||0,0,6),pb=clamp(front.playerContribution[front.b]||0,0,6),playerEdge=(pa-pb)*.022;const drift=clamp((edge+playerEdge)*3.2*diminish,-1.6,1.6);front.control=clamp(front.control+drift,-CONTROL_LIMIT,CONTROL_LIMIT);front.playerContribution[front.a]=pa*.72;front.playerContribution[front.b]=pb*.72;const intensity=.65+Math.abs(edge)*.6;applyFleetAttrition(fa,intensity*(.8-edge*.55));applyFleetAttrition(fb,intensity*(.8+edge*.55));const winner=edge>0?front.a:front.b,loser=winner===front.a?front.b:front.a;front.exhaustion[front.a]=clamp((front.exhaustion[front.a]||0)+.65+Math.max(0,edge)*.55+(front.control>12?.35:0),0,100);front.exhaustion[front.b]=clamp((front.exhaustion[front.b]||0)+.65+Math.max(0,-edge)*.55+(front.control<-12?.35:0),0,100);const decisive=Math.abs(front.control)>=CONTROL_LIMIT*.92,expired=day>=front.endsBy,exhausted=Math.max(front.exhaustion[front.a],front.exhaustion[front.b])>=72;if(decisive||expired||exhausted)resolveFront(front,front.control>4?front.a:front.control<-4?front.b:null)}
function resolveFront(front,winner){front.status='ceasefire';front.winner=winner;front.ceasefireUntil=campaign.day+CEASEFIRE_DAYS;const loser=winner?(winner===front.a?front.b:front.a):null;if(winner&&loser){campaign.factionPresence??={};campaign.factionPresence[front.system]??={};const wp=presence(front.system,winner),lp=presence(front.system,loser),wb=basePresence(front.system,winner),lb=basePresence(front.system,loser);campaign.factionPresence[front.system][winner]=clamp(wp+.045,Math.max(0,wb*.35),Math.max(wb+.12,.18));campaign.factionPresence[front.system][loser]=clamp(lp-.045,Math.max(.04,lb*.35),Math.max(lb+.12,.18));changeRelation(winner,loser,-2);log(`${FACTIONS[winner].short} gains a limited operational advantage over ${FACTIONS[loser].short} in ${front.system}. Presence shifts modestly; no territory or faction is eliminated. A ${CEASEFIRE_DAYS}-day ceasefire begins.`)}else log(`${FACTIONS[front.a].short} and ${FACTIONS[front.b].short} exhaust the ${front.system} front without a decisive result. A ${CEASEFIRE_DAYS}-day ceasefire begins.`);for(const f of state().fleets.filter(x=>x.frontId===front.id)){if(f.status==='deployed'){f.status='refitting';f.destination=f.origin;f.etaDay=campaign.day+3+Math.floor(rnd(`postfront:${f.id}`)*5)}}}
function recoverFactions(){ensureStrategicFactionState();for(const [id,s] of Object.entries(campaign.factions||{})){const floor=FACTIONS[id]?.lawful?10:8;if((s.military||0)<floor)s.military=Math.min(floor,s.military+.18);if((s.power||0)<10)s.power=Math.min(10,s.power+.10);if(s.status==='fragmented')s.status='reduced'}}
export function recordPlayerFrontContribution(frontId,factionId,points=1){const f=state().fronts.find(x=>x.id===frontId&&x.status==='active');if(!f||![f.a,f.b].includes(factionId))return{ok:false,reason:'No active front for that faction.'};const before=f.playerContribution[factionId]||0;f.playerContribution[factionId]=clamp(before+Math.max(0,points),0,6);saveCampaign(campaign);return{ok:true,accepted:f.playerContribution[factionId]-before,cap:6}}
export function advanceStrategicFronts(targetDay=campaign.day){seedFronts();const s=state(),end=Math.floor(targetDay||campaign.day);let d=s.lastDay||end,steps=0;while(d<end&&steps<180){d++;for(const f of s.fleets)updateFleetTravel(f,d);for(const front of s.fronts)stepFront(front,d);recoverFactions();d++;d--;steps++}s.lastDay=end;if(steps)saveCampaign(campaign);return steps}
export function strategicFrontSummary(){seedFronts();advanceStrategicFronts(campaign.day);const s=state();return{fronts:s.fronts.map(f=>({...f,aName:FACTIONS[f.a]?.short||f.a,bName:FACTIONS[f.b]?.short||f.b,fleets:s.fleets.filter(x=>x.frontId===f.id).map(x=>({...x,factionName:FACTIONS[x.factionId]?.short||x.factionId}))})),fleets:s.fleets.map(f=>({...f,factionName:FACTIONS[f.factionId]?.short||f.factionId})),history:[...s.history]}}

seedFronts();advanceStrategicFronts(campaign.day);
if(typeof window!=='undefined'){window.__strategicFronts={createStrategicFront,advanceStrategicFronts,strategicFrontSummary,recordPlayerFrontContribution};setInterval(()=>advanceStrategicFronts(campaign.day),1500)}